// Code generated by gst; DO NOT EDIT.

package model

import "github.com/hydroan/gst/apidoc"

func init() {
	apidoc.Register("cluster/model", "Cached", apidoc.StructDoc{
		Comment: "Cached is an entry of the replicated cache every replica keeps: written on\nthe replica that answers the request, read back from the local store of\nwhichever replica answers the next one. It is what makes the propagation\nbetween replicas observable from outside — the store itself is process\nmemory, with no shared tier behind it.",
	})
	apidoc.Register("cluster/model", "CachedReq", apidoc.StructDoc{
		Comment: "CachedReq is the entry to write: the key it is filed under and the value\nevery other replica must end up holding for it.",
	})
	apidoc.Register("cluster/model", "CachedRsp", apidoc.StructDoc{
		Comment: "CachedRsp reports which replica answered and what its own store holds for\nthe key, so a client reading every replica in turn sees the propagation.",
	})
	apidoc.Register("cluster/model", "CounterStep", apidoc.StructDoc{
		Comment: "CounterStep is one number of the counter the leader work keeps: every second\nthe leader appends the next number, in a transaction under its lease. Seq is\nunique, so no number is written twice, and Tenure names the leadership that\nwrote it: the numbers of one tenure form one unbroken run, and the runs\nfollow each other, unless two leaderships ever wrote at the same time. The\ncounter lives in the database, so a replica taking the leadership over\ncontinues from the last number.",
		Fields: map[string]string{
			"Replica": "the replica that led, see helper.Replica",
			"Tenure":  "one id per leadership, drawn as it starts",
		},
	})
	apidoc.Register("cluster/model", "Rebuild", apidoc.StructDoc{
		Comment: "Rebuild is the action a client triggers: work that must not run twice at\nonce across the deployment. The service runs it under the \"rebuild\" lock.",
	})
	apidoc.Register("cluster/model", "RebuildReq", apidoc.StructDoc{
		Comment: "RebuildReq says how long the rebuild takes: long enough to send a second\nrequest while it runs and see that one refused.",
	})
	apidoc.Register("cluster/model", "RebuildRsp", apidoc.StructDoc{
		Comment: "RebuildRsp reports which replica ran the rebuild and for how long.",
	})
	apidoc.Register("cluster/model", "Run", apidoc.StructDoc{
		Comment: "Run is one piece of work a replica did: a cron round or a run under the\nlock. It is written as the work starts — CreatedAt is the start — and marked\nended once the work runs to its end, both in a transaction on the work's\ncontext: a run cut short, by its lease lost or its process stopping, keeps\nno end. Listing the runs across the replicas shows who did what and how\noften, and whether two runs of one job or one lock ever overlapped.",
		Fields: map[string]string{
			"EndedAt": "when the work ran to its end; nil while it runs or once it was cut short",
			"Kind":    "\"cron\" or \"lock\"",
			"Name":    "the job or the lock",
			"Replica": "the replica that ran it, see helper.Replica",
		},
	})
}
