// Code generated by gst; DO NOT EDIT.

package model

import "github.com/hydroan/gst/apidoc"

func init() {
	apidoc.Register("cluster/model", "Cached", apidoc.StructDoc{
		Comment: "Cached is an entry of the replicated cache every replica keeps: written on\nthe replica that answers the request, read back from the local store of\nwhichever replica answers the next one. It is what makes the propagation\nbetween replicas observable from outside — the store itself is process\nmemory, with no shared tier behind it.",
	})
	apidoc.Register("cluster/model", "CachedCreateRsp", apidoc.StructDoc{
		Comment: "CachedCreateRsp reports which replica wrote the entry and what it wrote.",
	})
	apidoc.Register("cluster/model", "CachedDeleteRsp", apidoc.StructDoc{
		Comment: "CachedDeleteRsp reports which replica removed the entry.",
	})
	apidoc.Register("cluster/model", "CachedExchangeRsp", apidoc.StructDoc{
		Comment: "CachedExchangeRsp answers one key of an exchange stream: which replica\nanswered and what its own store holds for the key.",
	})
	apidoc.Register("cluster/model", "CachedGetRsp", apidoc.StructDoc{
		Comment: "CachedGetRsp reports which replica answered and what its own store\nholds for the key, so a client reading every replica in turn sees the\npropagation.",
	})
	apidoc.Register("cluster/model", "CachedKeyReq", apidoc.StructDoc{
		Comment: "CachedKeyReq names an entry to look up.",
	})
	apidoc.Register("cluster/model", "CachedLoadRsp", apidoc.StructDoc{
		Comment: "CachedLoadRsp reports what a load stream did.",
		Fields: map[string]string{
			"Count":   "how many entries the stream wrote",
			"Replica": "the replica that took the entries in",
		},
	})
	apidoc.Register("cluster/model", "CachedReq", apidoc.StructDoc{
		Comment: "CachedReq is the entry to write.",
		Fields: map[string]string{
			"Key":   "what the entry is filed under",
			"Value": "what every other replica must end up holding for it",
		},
	})
	apidoc.Register("cluster/model", "CounterStep", apidoc.StructDoc{
		Comment: "CounterStep is one number of the counter the leader work keeps: every second\nthe leader appends the next number, in a transaction under its lease. Seq is\nunique, so no number is written twice, and Tenure names the leadership that\nwrote it: the numbers of one tenure form one unbroken run, and the runs\nfollow each other, unless two leaderships ever wrote at the same time. The\ncounter lives in the database, so a replica taking the leadership over\ncontinues from the last number.",
		Fields: map[string]string{
			"Replica": "the replica that led, see helper.Replica",
			"Tenure":  "one id per leadership, drawn as it starts",
		},
	})
	apidoc.Register("cluster/model", "CounterStepWatchReq", apidoc.StructDoc{
		Comment: "CounterStepWatchReq says where a watch starts.",
		Fields: map[string]string{
			"After": "the numbers after it are streamed, so a client that lost its stream resumes from the last number it saw",
		},
	})
	apidoc.Register("cluster/model", "Flag", apidoc.StructDoc{
		Comment: "Flag is a switch every replica reads from the shared database: turned on or\noff through any replica, over HTTP or gRPC, it is what all of them see from\nthen on. It declares the whole standard set of actions, the batch ones\nincluded, so every standard rpc has a table behind it in this project. The\nCreate hook in service/flag checks the name and fills in the percent of a\nflag turned on without one: a binding tag would apply to a patch too, which\ncarries only the fields it changes.",
		Fields: map[string]string{
			"Percent": "the share of traffic the flag applies to, 0 to 100",
		},
	})
	apidoc.Register("cluster/model", "Rebuild", apidoc.StructDoc{
		Comment: "Rebuild is the action a client triggers: work that must not run twice at\nonce across the deployment. The service runs it under the \"rebuild\" lock.",
	})
	apidoc.Register("cluster/model", "RebuildReq", apidoc.StructDoc{
		Comment: "RebuildReq says how the rebuild runs.",
		Fields: map[string]string{
			"InTransaction": "asks for the lock to be taken from inside a transaction, which the framework refuses",
			"Seconds":       "how long the rebuild takes: long enough to send a second request while it runs and see that one refused",
		},
	})
	apidoc.Register("cluster/model", "RebuildRsp", apidoc.StructDoc{
		Comment: "RebuildRsp reports which replica ran the rebuild and for how long.",
	})
	apidoc.Register("cluster/model", "Run", apidoc.StructDoc{
		Comment: "Run is one piece of work a replica did: a cron round or a run under the\nlock. It is written as the work starts — CreatedAt is the start — and marked\nended once the work runs to its end, both in a transaction on the work's\ncontext: a run cut short, by its lease lost or its process stopping, keeps\nno end. Listing the runs across the replicas shows who did what and how\noften, and whether two runs of one job or one lock ever overlapped.",
		Fields: map[string]string{
			"EndedAt": "when the work ran to its end; nil while it runs or once it was cut short",
			"Kind":    "\"cron\" or \"lock\"",
			"Name":    "the job or the lock",
			"Replica": "the replica that ran it, see helper.Replica",
		},
	})
	apidoc.Register("cluster/model", "StepDown", apidoc.StructDoc{
		Comment: "StepDown is the request that ends the leadership on the replica that takes\nit: the leader work returns a failure of its own instead of running until\nits context ends, which is how a deployment sees what the framework does\nwith work that gives the name back early.",
	})
	apidoc.Register("cluster/model", "StepDownRsp", apidoc.StructDoc{
		Comment: "StepDownRsp reports what the request met.",
		Fields: map[string]string{
			"Asked":   "whether that replica had leader work to end",
			"Replica": "the replica that took the request",
		},
	})
}
