// Code generated by gst; DO NOT EDIT.
// source: model/progress.go

package model

import (
	"github.com/hydroan/gst"
	"gorm.io/gorm"
)

// ProgressCols are the typed column references of Progress.
var ProgressCols = struct {
	Count     gst.NumericColumn[int64]
	CreatedAt gst.TimeColumn
	CreatedBy gst.Column[string]
	DeletedAt gst.Column[gorm.DeletedAt]
	ID        gst.Column[string]
	Name      gst.Column[string]
	Replica   gst.Column[string]
	UpdatedAt gst.TimeColumn
	UpdatedBy gst.Column[string]
}{
	Count:     gst.NewNumericColumn[*Progress, int64]("count"),
	CreatedAt: gst.NewTimeColumn[*Progress]("created_at"),
	CreatedBy: gst.NewColumn[*Progress, string]("created_by"),
	DeletedAt: gst.NewColumn[*Progress, gorm.DeletedAt]("deleted_at"),
	ID:        gst.NewColumn[*Progress, string]("id"),
	Name:      gst.NewColumn[*Progress, string]("name"),
	Replica:   gst.NewColumn[*Progress, string]("replica"),
	UpdatedAt: gst.NewTimeColumn[*Progress]("updated_at"),
	UpdatedBy: gst.NewColumn[*Progress, string]("updated_by"),
}
