// Code generated by gst; DO NOT EDIT.
// source: model/config/file.go

package config

import (
	types "github.com/hydroan/gst/types"
	gorm "gorm.io/gorm"
)

// FileCols are the typed column references of File.
var FileCols = struct {
	Checksum    types.Column[string]
	Content     types.Column[string]
	CreatedAt   types.TimeColumn
	CreatedBy   types.Column[string]
	DeletedAt   types.Column[gorm.DeletedAt]
	Encrypted   types.Column[bool]
	Environment types.Column[string]
	Format      types.Column[FileFormat]
	ID          types.Column[string]
	Name        types.Column[string]
	NamespaceID types.Column[string]
	Size        types.NumericColumn[int]
	UpdatedAt   types.TimeColumn
	UpdatedBy   types.Column[string]
}{
	Checksum:    types.NewColumn[string]("checksum"),
	Content:     types.NewColumn[string]("content"),
	CreatedAt:   types.NewTimeColumn("created_at"),
	CreatedBy:   types.NewColumn[string]("created_by"),
	DeletedAt:   types.NewColumn[gorm.DeletedAt]("deleted_at"),
	Encrypted:   types.NewColumn[bool]("encrypted"),
	Environment: types.NewColumn[string]("environment"),
	Format:      types.NewColumn[FileFormat]("format"),
	ID:          types.NewColumn[string]("id"),
	Name:        types.NewColumn[string]("name"),
	NamespaceID: types.NewColumn[string]("namespace_id"),
	Size:        types.NewNumericColumn[int]("size"),
	UpdatedAt:   types.NewTimeColumn("updated_at"),
	UpdatedBy:   types.NewColumn[string]("updated_by"),
}
