package model

import (
	"reflect"
	"sync"

	"github.com/hydroan/gst/internal/modelregistry"
	"github.com/hydroan/gst/types"
)

var (
	mu               sync.Mutex
	registeredModels []types.Model
)

var (
	_ types.Model = (*Base)(nil)
	_ types.Model = (*AutoBase)(nil)
	_ types.Model = (*Empty)(nil)
)

type (
	// Base provides common fields and default hooks for database-backed resources.
	Base = modelregistry.Base

	// AutoBase provides the same common fields and default hooks as Base but
	// uses an auto-increment integer primary key assigned by the database.
	AutoBase = modelregistry.AutoBase

	// Query enables framework-owned list query parameters when embedded by a
	// model. It already includes Pagination and Cursor.
	Query = modelregistry.Query

	// Pagination enables page and size query parameters when embedded by a model.
	Pagination = modelregistry.Pagination

	// Cursor enables cursor query parameters when embedded by a model.
	Cursor = modelregistry.Cursor

	// Empty marks a model as an action-only type that does not map to a database table.
	Empty = modelregistry.Empty

	// Index declares one secondary index on a model's table, the single way
	// models declare indexes: a model implements the optional
	// Indexes() []model.Index method, and gorm struct tag indexes are banned
	// in business projects by gg check. Index names are always generated by
	// the framework.
	Index = modelregistry.Index

	// Version opts a model into optimistic locking when declared as a
	// top-level field (`Version model.Version`). See the type's documentation
	// for the full per-operation contract; in short: updates must carry the
	// version they read and fail with database.ErrStaleObject when the row
	// moved on, deletes are checked when a version is carried, and successful
	// updates bump the version for everyone else.
	Version = modelregistry.Version
)

// RegisteredModels returns independent model values registered through Register.
//
// It is primarily used by tools that need to inspect registered model definitions,
// such as migration schema generation. Mutating the returned values does not
// change the registered models.
func RegisteredModels() []any {
	mu.Lock()
	defer mu.Unlock()

	models := make([]any, 0, len(registeredModels))
	for _, m := range registeredModels {
		models = append(models, newModelSnapshot(m))
	}
	return models
}

// Register registers a database-backed model for table setup.
//
// Models that embed Empty are ignored because they do not represent
// database tables.
//
// Register only manages the schema. Baseline data (seed rows) belongs to the
// application: create it explicitly through the standard database chain in a
// startup hook such as router.OnRoutesReady, where model hooks, auditing,
// and transactions all apply.
//
// Example:
//
//	// Create table 'users'
//	Register[*model.User]()
//
// NOTE:
//  1. Register is usually called from the generated model/model.go file.
//  2. Ensure the model package is imported by the application entrypoint.
//  3. The function is safe for concurrent use.
func Register[M types.Model]() {
	if !modelregistry.IsValid[M]() {
		return
	}

	mu.Lock()
	defer mu.Unlock()

	table := reflect.New(reflect.TypeOf(*new(M)).Elem()).Interface().(M) //nolint:errcheck
	registeredModels = append(registeredModels, newModelSnapshot(table))
	modelregistry.EnqueueTable(table)
}

func newModelSnapshot(m types.Model) types.Model {
	typ := reflect.TypeOf(m)
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	return reflect.New(typ).Interface().(types.Model) //nolint:errcheck
}
