package model

import (
	"github.com/hydroan/gst/internal/modelregistry"
	"github.com/hydroan/gst/types"
)

var (
	_ types.Model = (*Base)(nil)
	_ types.Model = (*AutoBase)(nil)
	_ types.Model = (*Empty)(nil)
)

type (
	// Base provides common fields and default hooks for database-backed resources.
	Base = modelregistry.Base

	// AutoBase provides the same common fields and default hooks as Base but
	// uses an auto-increment integer primary key assigned by the database.
	AutoBase = modelregistry.AutoBase

	// Query enables framework-owned list query parameters when embedded by a
	// model. It already includes Pagination and Cursor.
	Query = modelregistry.Query

	// Pagination enables page and size query parameters when embedded by a model.
	Pagination = modelregistry.Pagination

	// Cursor enables cursor query parameters when embedded by a model.
	Cursor = modelregistry.Cursor

	// Empty marks a model as an action-only type that does not map to a database table.
	Empty = modelregistry.Empty

	// Index declares one secondary index on a model's table, the single way
	// models declare indexes: a model implements the optional
	// Indexes() []model.Index method, and gorm struct tag indexes are banned
	// in business projects by gg check. Index names are always generated by
	// the framework.
	Index = modelregistry.Index

	// Version opts a model into optimistic locking when declared as a
	// top-level field (`Version model.Version`). See the type's documentation
	// for the full per-operation contract; in short: updates must carry the
	// version they read and fail with database.ErrStaleObject when the row
	// moved on, deletes are checked when a version is carried, and successful
	// updates bump the version for everyone else.
	Version = modelregistry.Version
)

// RegisteredModels returns independent model values registered through
// Register. Mutating the returned values does not change what is registered.
//
// Searching this repository makes it look unused by anything but cmd/gg, and
// makes the forwarder look like one the tool could skip by reading the
// registry directly. It cannot. Those call sites sit inside the program
// templates gg writes out and builds against the business project's own
// go.mod, which makes them business-module code, and the internal registry
// behind this forwarder is out of reach from there. What breaks if this goes
// is "gg gen" and "gg migrate", not anything in this repository.
func RegisteredModels() []any {
	return modelregistry.RegisteredModels()
}

// Register registers a database-backed model for table setup.
//
// Models that embed Empty are ignored because they do not represent
// database tables.
//
// Register only manages the schema. Baseline data (seed rows) belongs to the
// application: create it explicitly through the standard database chain in a
// startup hook such as router.OnRoutesReady, where model hooks, auditing,
// and transactions all apply.
//
// Example:
//
//	// Create table 'users'
//	Register[*model.User]()
//
// NOTE:
//  1. Register is usually called from the generated model/model.go file.
//  2. Ensure the model package is imported by the application entrypoint.
//  3. The function is safe for concurrent use.
func Register[M types.Model]() {
	modelregistry.RegisterTable[M]()
}
