// Code generated by gst; DO NOT EDIT.

package pb

import (
	"tmpapp/model"

	"github.com/hydroan/gst/grpc"
)

// FeedService serves the rpcs of the FeedService service through the actions
// of Feed: every handler decodes its request message into what the action's
// call takes, runs the call and encodes what it answers into the response
// message.
type FeedService struct {
	UnimplementedFeedServiceServer
}

// FeedToProto encodes Feed values into their message, nil into nil.
func FeedToProto(m *model.Feed) *Feed {
	if m == nil {
		return nil
	}
	p := new(Feed)
	p.Id = m.ID
	p.CreatedBy = m.CreatedBy
	p.UpdatedBy = m.UpdatedBy
	p.CreatedAt = grpc.Timestamp(m.CreatedAt)
	p.UpdatedAt = grpc.Timestamp(m.UpdatedAt)
	p.Topic = m.Topic
	return p
}

// FeedFromProto decodes Feed messages into values, nil into nil.
func FeedFromProto(p *Feed) *model.Feed {
	if p == nil {
		return nil
	}
	m := new(model.Feed)
	m.ID = p.GetId()
	m.CreatedBy = p.GetCreatedBy()
	m.UpdatedBy = p.GetUpdatedBy()
	m.CreatedAt = grpc.Time(p.GetCreatedAt())
	m.UpdatedAt = grpc.Time(p.GetUpdatedAt())
	m.Topic = p.GetTopic()
	return m
}

// FeedEventToProto encodes FeedEvent values into their message, nil into
// nil.
func FeedEventToProto(m *model.FeedEvent) *FeedEvent {
	if m == nil {
		return nil
	}
	p := new(FeedEvent)
	p.Seq = m.Seq
	p.Body = m.Body
	return p
}

// FeedEventFromProto decodes FeedEvent messages into values, nil into nil.
func FeedEventFromProto(p *FeedEvent) *model.FeedEvent {
	if p == nil {
		return nil
	}
	m := new(model.FeedEvent)
	m.Seq = p.GetSeq()
	m.Body = p.GetBody()
	return m
}

// FeedUploadRspToProto encodes FeedUploadRsp values into their message, nil
// into nil.
func FeedUploadRspToProto(m *model.FeedUploadRsp) *FeedUploadRsp {
	if m == nil {
		return nil
	}
	p := new(FeedUploadRsp)
	p.Accepted = m.Accepted
	return p
}

// FeedUploadRspFromProto decodes FeedUploadRsp messages into values, nil
// into nil.
func FeedUploadRspFromProto(p *FeedUploadRsp) *model.FeedUploadRsp {
	if p == nil {
		return nil
	}
	m := new(model.FeedUploadRsp)
	m.Accepted = p.GetAccepted()
	return m
}

// FeedWatchReqToProto encodes FeedWatchReq values into their message, nil
// into nil.
func FeedWatchReqToProto(m *model.FeedWatchReq) *FeedWatchReq {
	if m == nil {
		return nil
	}
	p := new(FeedWatchReq)
	p.Topic = m.Topic
	return p
}

// FeedWatchReqFromProto decodes FeedWatchReq messages into values, nil into
// nil.
func FeedWatchReqFromProto(p *FeedWatchReq) *model.FeedWatchReq {
	if p == nil {
		return nil
	}
	m := new(model.FeedWatchReq)
	m.Topic = p.GetTopic()
	return m
}
