// Code generated by gst; DO NOT EDIT.

package pb

import (
	"tmpapp/model"

	"github.com/hydroan/gst/grpc"
	gstmodel "github.com/hydroan/gst/model"
)

// feedService serves the rpcs of the FeedService service through the actions
// of Feed: every handler decodes its request message into what the action's
// call takes, runs the call and encodes what it answers into the response
// message.
type feedService struct {
	UnimplementedFeedServiceServer
}

// The calls of the actions of Feed, one per rpc of FeedService, built once
// at package initialization.
var (
	tailFeedByFeed   = grpc.ServerStreamCall[*model.Feed, *gstmodel.Empty, *model.FeedTailRsp]("/api/feeds/:feed/tail")
	uploadFeedByFeed = grpc.ClientStreamCall[*model.Feed, *model.FeedUploadReq, *model.FeedUploadRsp]("/api/feeds/:feed/upload")
	chatFeed         = grpc.BidiStreamCall[*model.Feed, *model.FeedChatReq, *model.FeedChatRsp]("/api/feeds/chat")
	ingestFeed       = grpc.ClientStreamCall[*model.Feed, *model.FeedIngestReq, *gstmodel.Empty]("/api/feeds/ingest")
	watchFeed        = grpc.ServerStreamCall[*model.Feed, *model.FeedWatchReq, *model.FeedWatchRsp]("/api/feeds/watch")
)

// TailFeedByFeed serves the Stream action of Feed declared on
// feeds/:feed/tail, served over gRPC alone.
func (feedService) TailFeedByFeed(req *TailFeedByFeedRequest, srv FeedService_TailFeedByFeedServer) error {
	return tailFeedByFeed(srv.Context(), map[string]string{"feed": req.GetFeed()}, new(gstmodel.Empty), func(rsp *model.FeedTailRsp) error {
		return srv.Send(&TailFeedByFeedResponse{Result: FeedEventToProto(rsp)})
	})
}

// UploadFeedByFeed serves the Stream action of Feed declared on
// feeds/:feed/upload, served over gRPC alone.
func (feedService) UploadFeedByFeed(srv FeedService_UploadFeedByFeedServer) error {
	first, err := grpc.FirstMessage(srv.Recv)
	if err != nil {
		return err
	}
	params := map[string]string{"feed": first.GetFeed()}
	n := 1
	result, err := uploadFeedByFeed(srv.Context(), params, func() (*model.FeedUploadReq, error) {
		if msg := first; msg != nil {
			first = nil
			return FeedEventFromProto(msg.GetPayload())
		}
		msg, recvErr := srv.Recv()
		if recvErr != nil {
			return nil, recvErr
		}
		n++
		if err := grpc.SameParams(n, params, map[string]string{"feed": msg.GetFeed()}); err != nil {
			return nil, err
		}
		return FeedEventFromProto(msg.GetPayload())
	})
	if err != nil {
		return err
	}
	return srv.SendAndClose(&UploadFeedByFeedResponse{Result: FeedUploadRspToProto(result)})
}

// ChatFeed serves the Stream action of Feed declared on feeds/chat, served
// over gRPC alone.
func (feedService) ChatFeed(srv FeedService_ChatFeedServer) error {
	return chatFeed(srv.Context(), nil, func() (*model.FeedChatReq, error) {
		msg, recvErr := srv.Recv()
		if recvErr != nil {
			return nil, recvErr
		}
		return FeedEventFromProto(msg.GetPayload())
	}, func(rsp *model.FeedChatRsp) error {
		return srv.Send(&ChatFeedResponse{Result: FeedEventToProto(rsp)})
	})
}

// IngestFeed serves the Stream action of Feed declared on feeds/ingest,
// served over gRPC alone.
func (feedService) IngestFeed(srv FeedService_IngestFeedServer) error {
	if _, err := ingestFeed(srv.Context(), nil, func() (*model.FeedIngestReq, error) {
		msg, recvErr := srv.Recv()
		if recvErr != nil {
			return nil, recvErr
		}
		return FeedEventFromProto(msg.GetPayload())
	}); err != nil {
		return err
	}
	return srv.SendAndClose(&IngestFeedResponse{})
}

// WatchFeed serves the Stream action of Feed declared on feeds/watch, served
// over gRPC alone.
func (feedService) WatchFeed(req *WatchFeedRequest, srv FeedService_WatchFeedServer) error {
	payload, err := FeedWatchReqFromProto(req.GetPayload())
	if err != nil {
		return err
	}
	return watchFeed(srv.Context(), nil, payload, func(rsp *model.FeedWatchRsp) error {
		return srv.Send(&WatchFeedResponse{Result: FeedEventToProto(rsp)})
	})
}

// FeedToProto encodes Feed values into their message, nil into nil.
func FeedToProto(m *model.Feed) *Feed {
	if m == nil {
		return nil
	}
	p := new(Feed)
	p.Id = grpc.UTF8(m.ID)
	p.CreatedBy = grpc.UTF8(m.CreatedBy)
	p.UpdatedBy = grpc.UTF8(m.UpdatedBy)
	p.CreatedAt = grpc.Timestamp(m.CreatedAt)
	p.UpdatedAt = grpc.Timestamp(m.UpdatedAt)
	p.Topic = grpc.UTF8(m.Topic)
	return p
}

// FeedFromProto decodes Feed messages into values, nil into nil. A value a
// field cannot hold, an integer out of its range, a string that is no JSON
// number, a time outside the years 1 to 9999, bytes that are no JSON
// document or a number that is not finite, is refused with InvalidArgument.
func FeedFromProto(p *Feed) (*model.Feed, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.Feed)
	var err error
	m.ID = p.GetId()
	m.CreatedBy = p.GetCreatedBy()
	m.UpdatedBy = p.GetUpdatedBy()
	m.CreatedAt, err = grpc.Time("created_at", p.GetCreatedAt())
	if err != nil {
		return nil, err
	}
	m.UpdatedAt, err = grpc.Time("updated_at", p.GetUpdatedAt())
	if err != nil {
		return nil, err
	}
	m.Topic = p.GetTopic()
	return m, nil
}

// FeedEventToProto encodes FeedEvent values into their message, nil into
// nil.
func FeedEventToProto(m *model.FeedEvent) *FeedEvent {
	if m == nil {
		return nil
	}
	p := new(FeedEvent)
	p.Seq = m.Seq
	p.Body = grpc.UTF8(m.Body)
	return p
}

// FeedEventFromProto decodes FeedEvent messages into values, nil into nil.
func FeedEventFromProto(p *FeedEvent) (*model.FeedEvent, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.FeedEvent)
	m.Seq = p.GetSeq()
	m.Body = p.GetBody()
	return m, nil
}

// FeedUploadRspToProto encodes FeedUploadRsp values into their message, nil
// into nil.
func FeedUploadRspToProto(m *model.FeedUploadRsp) *FeedUploadRsp {
	if m == nil {
		return nil
	}
	p := new(FeedUploadRsp)
	p.Accepted = m.Accepted
	return p
}

// FeedUploadRspFromProto decodes FeedUploadRsp messages into values, nil
// into nil.
func FeedUploadRspFromProto(p *FeedUploadRsp) (*model.FeedUploadRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.FeedUploadRsp)
	m.Accepted = p.GetAccepted()
	return m, nil
}

// FeedWatchReqToProto encodes FeedWatchReq values into their message, nil
// into nil.
func FeedWatchReqToProto(m *model.FeedWatchReq) *FeedWatchReq {
	if m == nil {
		return nil
	}
	p := new(FeedWatchReq)
	p.Topic = grpc.UTF8(m.Topic)
	return p
}

// FeedWatchReqFromProto decodes FeedWatchReq messages into values, nil into
// nil.
func FeedWatchReqFromProto(p *FeedWatchReq) (*model.FeedWatchReq, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.FeedWatchReq)
	m.Topic = p.GetTopic()
	return m, nil
}
