// Code generated by gst; DO NOT EDIT.

package pb

import (
	"context"
	"tmpapp/model"

	"github.com/hydroan/gst/grpc"
)

// noteService serves the rpcs of the NoteService service through the actions
// of Note: every handler decodes its request message into what the action's
// call takes, runs the call and encodes what it answers into the response
// message.
type noteService struct {
	UnimplementedNoteServiceServer
}

// The calls of the actions of Note, one per rpc of NoteService, built once
// at package initialization.
var (
	createNote = grpc.CreateCall[*model.Note]("/api/notes")
	getNote    = grpc.GetCall[*model.Note]("/api/notes/:id")
)

// CreateNote serves the Create action of Note on /api/notes.
func (noteService) CreateNote(ctx context.Context, req *CreateNoteRequest) (*CreateNoteResponse, error) {
	in, err := NoteFromProto(req.GetNote())
	if err != nil {
		return nil, err
	}
	m, err := createNote(ctx, nil, in)
	if err != nil {
		return nil, err
	}
	return &CreateNoteResponse{Note: NoteToProto(m)}, nil
}

// GetNote serves the Get action of Note on /api/notes/:id.
func (noteService) GetNote(ctx context.Context, req *GetNoteRequest) (*GetNoteResponse, error) {
	m, err := getNote(ctx, map[string]string{"id": req.GetId()}, req.GetId(), grpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()})
	if err != nil {
		return nil, err
	}
	return &GetNoteResponse{Note: NoteToProto(m)}, nil
}

// NoteToProto encodes Note values into their message, nil into nil.
func NoteToProto(m *model.Note) *Note {
	if m == nil {
		return nil
	}
	p := new(Note)
	p.Id = grpc.UTF8(m.ID)
	p.CreatedBy = grpc.UTF8(m.CreatedBy)
	p.UpdatedBy = grpc.UTF8(m.UpdatedBy)
	p.CreatedAt = grpc.Timestamp(m.CreatedAt)
	p.UpdatedAt = grpc.Timestamp(m.UpdatedAt)
	p.Title = grpc.UTF8(m.Title)
	p.Tags = m.Tags
	return p
}

// NoteFromProto decodes Note messages into values, nil into nil. A value a
// field cannot hold, an integer out of its range, a string that is no JSON
// number, a time outside the years 1 to 9999, bytes that are no JSON
// document or a number that is not finite, is refused with InvalidArgument.
func NoteFromProto(p *Note) (*model.Note, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.Note)
	var err error
	m.ID = p.GetId()
	m.CreatedBy = p.GetCreatedBy()
	m.UpdatedBy = p.GetUpdatedBy()
	m.CreatedAt, err = grpc.Time("created_at", p.GetCreatedAt())
	if err != nil {
		return nil, err
	}
	m.UpdatedAt, err = grpc.Time("updated_at", p.GetUpdatedAt())
	if err != nil {
		return nil, err
	}
	m.Title = p.GetTitle()
	m.Tags = p.GetTags()
	return m, nil
}
