// Code generated by gst; DO NOT EDIT.

package pb

import (
	"context"
	"tmpapp/model"

	gstgrpc "github.com/hydroan/gst/grpc"
)

// NoteService serves the rpcs of the NoteService service through the actions
// of Note: every handler decodes its request message into what the action's
// call takes, runs the call and encodes what it answers into the response
// message.
type NoteService struct {
	UnimplementedNoteServiceServer
}

// The calls of the actions of Note, one per rpc of NoteService, built once
// at package initialization.
var (
	createNote = gstgrpc.CreateCall[*model.Note]("notes")
	getNote    = gstgrpc.GetCall[*model.Note]("notes/:id")
)

// CreateNote serves the Create action of Note on notes.
func (NoteService) CreateNote(ctx context.Context, req *CreateNoteRequest) (*CreateNoteResponse, error) {
	m, err := createNote(ctx, nil, NoteFromProto(req.GetNote()))
	if err != nil {
		return nil, err
	}
	return &CreateNoteResponse{Note: NoteToProto(m)}, nil
}

// GetNote serves the Get action of Note on notes.
func (NoteService) GetNote(ctx context.Context, req *GetNoteRequest) (*GetNoteResponse, error) {
	m, err := getNote(ctx, map[string]string{"id": req.GetId()}, req.GetId(), gstgrpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()})
	if err != nil {
		return nil, err
	}
	return &GetNoteResponse{Note: NoteToProto(m)}, nil
}

// NoteToProto encodes Note values into their message, nil into nil.
func NoteToProto(m *model.Note) *Note {
	if m == nil {
		return nil
	}
	p := new(Note)
	p.Id = m.ID
	p.CreatedBy = m.CreatedBy
	p.UpdatedBy = m.UpdatedBy
	p.CreatedAt = gstgrpc.Timestamp(m.CreatedAt)
	p.UpdatedAt = gstgrpc.Timestamp(m.UpdatedAt)
	p.Title = m.Title
	p.Tags = m.Tags
	return p
}

// NoteFromProto decodes Note messages into values, nil into nil.
func NoteFromProto(p *Note) *model.Note {
	if p == nil {
		return nil
	}
	m := new(model.Note)
	m.ID = p.GetId()
	m.CreatedBy = p.GetCreatedBy()
	m.UpdatedBy = p.GetUpdatedBy()
	m.CreatedAt = gstgrpc.Time(p.GetCreatedAt())
	m.UpdatedAt = gstgrpc.Time(p.GetUpdatedAt())
	m.Title = p.GetTitle()
	m.Tags = p.GetTags()
	return m
}
