// Code generated by gst; DO NOT EDIT.

package pb

import (
	"context"
	"tmpapp/model"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/grpc"
	gstmodel "github.com/hydroan/gst/model"
)

// reportService serves the rpcs of the ReportService service through the
// actions of Report: every handler decodes its request message into what the
// action's call takes, runs the call and encodes what it answers into the
// response message.
type reportService struct {
	UnimplementedReportServiceServer
}

// The calls of the actions of Report, one per rpc of ReportService, built
// once at package initialization.
var getReport = grpc.ServiceCall[*model.Report, *gstmodel.Empty, *model.ReportRsp](consts.Get, "/api/reports/summary")

// GetReport serves the Get action of Report on /api/reports/summary.
func (reportService) GetReport(ctx context.Context, req *GetReportRequest) (*GetReportResponse, error) {
	result, err := getReport(ctx, nil, grpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()}, new(gstmodel.Empty))
	if err != nil {
		return nil, err
	}
	return &GetReportResponse{Result: ReportRspToProto(result)}, nil
}

// ReportRspToProto encodes ReportRsp values into their message, nil into
// nil.
func ReportRspToProto(m *model.ReportRsp) *ReportRsp {
	if m == nil {
		return nil
	}
	p := new(ReportRsp)
	p.Total = m.Total
	return p
}

// ReportRspFromProto decodes ReportRsp messages into values, nil into nil.
func ReportRspFromProto(p *ReportRsp) (*model.ReportRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.ReportRsp)
	m.Total = p.GetTotal()
	return m, nil
}
