// Code generated by gst; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cached.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateCachedRequest is the request of CachedService.CreateCached.
type CreateCachedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the CachedReq the action takes.
	Payload       *CachedReq `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCachedRequest) Reset() {
	*x = CreateCachedRequest{}
	mi := &file_cached_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCachedRequest) ProtoMessage() {}

func (x *CreateCachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCachedRequest.ProtoReflect.Descriptor instead.
func (*CreateCachedRequest) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCachedRequest) GetPayload() *CachedReq {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CreateCachedResponse is the response of CachedService.CreateCached.
type CreateCachedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the CachedRsp the action answers with.
	Result        *CachedRsp `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCachedResponse) Reset() {
	*x = CreateCachedResponse{}
	mi := &file_cached_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCachedResponse) ProtoMessage() {}

func (x *CreateCachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCachedResponse.ProtoReflect.Descriptor instead.
func (*CreateCachedResponse) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCachedResponse) GetResult() *CachedRsp {
	if x != nil {
		return x.Result
	}
	return nil
}

// DeleteCachedRequest is the request of CachedService.DeleteCached.
type DeleteCachedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the id of the Cached to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCachedRequest) Reset() {
	*x = DeleteCachedRequest{}
	mi := &file_cached_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCachedRequest) ProtoMessage() {}

func (x *DeleteCachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCachedRequest.ProtoReflect.Descriptor instead.
func (*DeleteCachedRequest) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCachedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteCachedResponse is the response of CachedService.DeleteCached.
type DeleteCachedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the CachedRsp the action answers with.
	Result        *CachedRsp `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCachedResponse) Reset() {
	*x = DeleteCachedResponse{}
	mi := &file_cached_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCachedResponse) ProtoMessage() {}

func (x *DeleteCachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCachedResponse.ProtoReflect.Descriptor instead.
func (*DeleteCachedResponse) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCachedResponse) GetResult() *CachedRsp {
	if x != nil {
		return x.Result
	}
	return nil
}

// GetCachedRequest is the request of CachedService.GetCached.
type GetCachedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the id of the Cached.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// expand is the associations to expand, as the _expand query parameter names them.
	Expand []string `protobuf:"bytes,2,rep,name=expand,proto3" json:"expand,omitempty"`
	// depth is the depth of the expansion, as the _depth query parameter.
	Depth         uint32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCachedRequest) Reset() {
	*x = GetCachedRequest{}
	mi := &file_cached_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCachedRequest) ProtoMessage() {}

func (x *GetCachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCachedRequest.ProtoReflect.Descriptor instead.
func (*GetCachedRequest) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{4}
}

func (x *GetCachedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCachedRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *GetCachedRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// GetCachedResponse is the response of CachedService.GetCached.
type GetCachedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the CachedRsp the action answers with.
	Result        *CachedRsp `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCachedResponse) Reset() {
	*x = GetCachedResponse{}
	mi := &file_cached_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCachedResponse) ProtoMessage() {}

func (x *GetCachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCachedResponse.ProtoReflect.Descriptor instead.
func (*GetCachedResponse) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{5}
}

func (x *GetCachedResponse) GetResult() *CachedRsp {
	if x != nil {
		return x.Result
	}
	return nil
}

// ExchangeCachedRequest is the request of CachedService.ExchangeCached.
type ExchangeCachedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the CachedKeyReq the action takes.
	Payload       *CachedKeyReq `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCachedRequest) Reset() {
	*x = ExchangeCachedRequest{}
	mi := &file_cached_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCachedRequest) ProtoMessage() {}

func (x *ExchangeCachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCachedRequest.ProtoReflect.Descriptor instead.
func (*ExchangeCachedRequest) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{6}
}

func (x *ExchangeCachedRequest) GetPayload() *CachedKeyReq {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ExchangeCachedResponse is the response of CachedService.ExchangeCached.
type ExchangeCachedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the CachedRsp the action answers with.
	Result        *CachedRsp `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCachedResponse) Reset() {
	*x = ExchangeCachedResponse{}
	mi := &file_cached_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCachedResponse) ProtoMessage() {}

func (x *ExchangeCachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCachedResponse.ProtoReflect.Descriptor instead.
func (*ExchangeCachedResponse) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{7}
}

func (x *ExchangeCachedResponse) GetResult() *CachedRsp {
	if x != nil {
		return x.Result
	}
	return nil
}

// LoadCachedRequest is the request of CachedService.LoadCached.
type LoadCachedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the CachedReq the action takes.
	Payload       *CachedReq `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCachedRequest) Reset() {
	*x = LoadCachedRequest{}
	mi := &file_cached_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCachedRequest) ProtoMessage() {}

func (x *LoadCachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCachedRequest.ProtoReflect.Descriptor instead.
func (*LoadCachedRequest) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{8}
}

func (x *LoadCachedRequest) GetPayload() *CachedReq {
	if x != nil {
		return x.Payload
	}
	return nil
}

// LoadCachedResponse is the response of CachedService.LoadCached.
type LoadCachedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the CachedLoadRsp the action answers with.
	Result        *CachedLoadRsp `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCachedResponse) Reset() {
	*x = LoadCachedResponse{}
	mi := &file_cached_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCachedResponse) ProtoMessage() {}

func (x *LoadCachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCachedResponse.ProtoReflect.Descriptor instead.
func (*LoadCachedResponse) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{9}
}

func (x *LoadCachedResponse) GetResult() *CachedLoadRsp {
	if x != nil {
		return x.Result
	}
	return nil
}

// CachedReq is the entry to write: the key it is filed under and the value
// every other replica must end up holding for it.
type CachedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedReq) Reset() {
	*x = CachedReq{}
	mi := &file_cached_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedReq) ProtoMessage() {}

func (x *CachedReq) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedReq.ProtoReflect.Descriptor instead.
func (*CachedReq) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{10}
}

func (x *CachedReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CachedReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// CachedRsp reports which replica answered and what its own store holds for
// the key, so a client reading every replica in turn sees the propagation.
type CachedRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replica       string                 `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedRsp) Reset() {
	*x = CachedRsp{}
	mi := &file_cached_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedRsp) ProtoMessage() {}

func (x *CachedRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedRsp.ProtoReflect.Descriptor instead.
func (*CachedRsp) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{11}
}

func (x *CachedRsp) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

func (x *CachedRsp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CachedRsp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CachedRsp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// CachedKeyReq names an entry to look up.
type CachedKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedKeyReq) Reset() {
	*x = CachedKeyReq{}
	mi := &file_cached_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedKeyReq) ProtoMessage() {}

func (x *CachedKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedKeyReq.ProtoReflect.Descriptor instead.
func (*CachedKeyReq) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{12}
}

func (x *CachedKeyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// CachedLoadRsp reports how many entries a load stream wrote and which
// replica took them in.
type CachedLoadRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replica       string                 `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedLoadRsp) Reset() {
	*x = CachedLoadRsp{}
	mi := &file_cached_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedLoadRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedLoadRsp) ProtoMessage() {}

func (x *CachedLoadRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cached_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedLoadRsp.ProtoReflect.Descriptor instead.
func (*CachedLoadRsp) Descriptor() ([]byte, []int) {
	return file_cached_proto_rawDescGZIP(), []int{13}
}

func (x *CachedLoadRsp) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

func (x *CachedLoadRsp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_cached_proto protoreflect.FileDescriptor

const file_cached_proto_rawDesc = "" +
	"\n" +
	"\fcached.proto\x12\acluster\"C\n" +
	"\x13CreateCachedRequest\x12,\n" +
	"\apayload\x18\x01 \x01(\v2\x12.cluster.CachedReqR\apayload\"B\n" +
	"\x14CreateCachedResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.cluster.CachedRspR\x06result\"%\n" +
	"\x13DeleteCachedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x14DeleteCachedResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.cluster.CachedRspR\x06result\"P\n" +
	"\x10GetCachedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06expand\x18\x02 \x03(\tR\x06expand\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\rR\x05depth\"?\n" +
	"\x11GetCachedResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.cluster.CachedRspR\x06result\"H\n" +
	"\x15ExchangeCachedRequest\x12/\n" +
	"\apayload\x18\x01 \x01(\v2\x15.cluster.CachedKeyReqR\apayload\"D\n" +
	"\x16ExchangeCachedResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.cluster.CachedRspR\x06result\"A\n" +
	"\x11LoadCachedRequest\x12,\n" +
	"\apayload\x18\x01 \x01(\v2\x12.cluster.CachedReqR\apayload\"D\n" +
	"\x12LoadCachedResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.cluster.CachedLoadRspR\x06result\"3\n" +
	"\tCachedReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"c\n" +
	"\tCachedRsp\x12\x18\n" +
	"\areplica\x18\x01 \x01(\tR\areplica\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\" \n" +
	"\fCachedKeyReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"?\n" +
	"\rCachedLoadRsp\x12\x18\n" +
	"\areplica\x18\x01 \x01(\tR\areplica\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count2\x8d\x03\n" +
	"\rCachedService\x12K\n" +
	"\fCreateCached\x12\x1c.cluster.CreateCachedRequest\x1a\x1d.cluster.CreateCachedResponse\x12K\n" +
	"\fDeleteCached\x12\x1c.cluster.DeleteCachedRequest\x1a\x1d.cluster.DeleteCachedResponse\x12B\n" +
	"\tGetCached\x12\x19.cluster.GetCachedRequest\x1a\x1a.cluster.GetCachedResponse\x12U\n" +
	"\x0eExchangeCached\x12\x1e.cluster.ExchangeCachedRequest\x1a\x1f.cluster.ExchangeCachedResponse(\x010\x01\x12G\n" +
	"\n" +
	"LoadCached\x12\x1a.cluster.LoadCachedRequest\x1a\x1b.cluster.LoadCachedResponse(\x01B\x0fZ\rcluster/pb;pbb\x06proto3"

var (
	file_cached_proto_rawDescOnce sync.Once
	file_cached_proto_rawDescData []byte
)

func file_cached_proto_rawDescGZIP() []byte {
	file_cached_proto_rawDescOnce.Do(func() {
		file_cached_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cached_proto_rawDesc), len(file_cached_proto_rawDesc)))
	})
	return file_cached_proto_rawDescData
}

var file_cached_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cached_proto_goTypes = []any{
	(*CreateCachedRequest)(nil),    // 0: cluster.CreateCachedRequest
	(*CreateCachedResponse)(nil),   // 1: cluster.CreateCachedResponse
	(*DeleteCachedRequest)(nil),    // 2: cluster.DeleteCachedRequest
	(*DeleteCachedResponse)(nil),   // 3: cluster.DeleteCachedResponse
	(*GetCachedRequest)(nil),       // 4: cluster.GetCachedRequest
	(*GetCachedResponse)(nil),      // 5: cluster.GetCachedResponse
	(*ExchangeCachedRequest)(nil),  // 6: cluster.ExchangeCachedRequest
	(*ExchangeCachedResponse)(nil), // 7: cluster.ExchangeCachedResponse
	(*LoadCachedRequest)(nil),      // 8: cluster.LoadCachedRequest
	(*LoadCachedResponse)(nil),     // 9: cluster.LoadCachedResponse
	(*CachedReq)(nil),              // 10: cluster.CachedReq
	(*CachedRsp)(nil),              // 11: cluster.CachedRsp
	(*CachedKeyReq)(nil),           // 12: cluster.CachedKeyReq
	(*CachedLoadRsp)(nil),          // 13: cluster.CachedLoadRsp
}
var file_cached_proto_depIdxs = []int32{
	10, // 0: cluster.CreateCachedRequest.payload:type_name -> cluster.CachedReq
	11, // 1: cluster.CreateCachedResponse.result:type_name -> cluster.CachedRsp
	11, // 2: cluster.DeleteCachedResponse.result:type_name -> cluster.CachedRsp
	11, // 3: cluster.GetCachedResponse.result:type_name -> cluster.CachedRsp
	12, // 4: cluster.ExchangeCachedRequest.payload:type_name -> cluster.CachedKeyReq
	11, // 5: cluster.ExchangeCachedResponse.result:type_name -> cluster.CachedRsp
	10, // 6: cluster.LoadCachedRequest.payload:type_name -> cluster.CachedReq
	13, // 7: cluster.LoadCachedResponse.result:type_name -> cluster.CachedLoadRsp
	0,  // 8: cluster.CachedService.CreateCached:input_type -> cluster.CreateCachedRequest
	2,  // 9: cluster.CachedService.DeleteCached:input_type -> cluster.DeleteCachedRequest
	4,  // 10: cluster.CachedService.GetCached:input_type -> cluster.GetCachedRequest
	6,  // 11: cluster.CachedService.ExchangeCached:input_type -> cluster.ExchangeCachedRequest
	8,  // 12: cluster.CachedService.LoadCached:input_type -> cluster.LoadCachedRequest
	1,  // 13: cluster.CachedService.CreateCached:output_type -> cluster.CreateCachedResponse
	3,  // 14: cluster.CachedService.DeleteCached:output_type -> cluster.DeleteCachedResponse
	5,  // 15: cluster.CachedService.GetCached:output_type -> cluster.GetCachedResponse
	7,  // 16: cluster.CachedService.ExchangeCached:output_type -> cluster.ExchangeCachedResponse
	9,  // 17: cluster.CachedService.LoadCached:output_type -> cluster.LoadCachedResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cached_proto_init() }
func file_cached_proto_init() {
	if File_cached_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cached_proto_rawDesc), len(file_cached_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cached_proto_goTypes,
		DependencyIndexes: file_cached_proto_depIdxs,
		MessageInfos:      file_cached_proto_msgTypes,
	}.Build()
	File_cached_proto = out.File
	file_cached_proto_goTypes = nil
	file_cached_proto_depIdxs = nil
}
