// Code generated by gst; DO NOT EDIT.

package pb

import (
	"cluster/model"
	"context"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/grpc"
	gstmodel "github.com/hydroan/gst/model"
)

// cachedService serves the rpcs of the CachedService service through the
// actions of Cached: every handler decodes its request message into what the
// action's call takes, runs the call and encodes what it answers into the
// response message.
type cachedService struct {
	UnimplementedCachedServiceServer
}

// The calls of the actions of Cached, one per rpc of CachedService, built
// once at package initialization.
var (
	createCached   = grpc.ServiceCall[*model.Cached, *model.CachedReq, *model.CachedCreateRsp](consts.Create, "/api/caches")
	deleteCached   = grpc.ServiceCall[*model.Cached, *gstmodel.Empty, *model.CachedDeleteRsp](consts.Delete, "/api/caches/:id")
	getCached      = grpc.ServiceCall[*model.Cached, *gstmodel.Empty, *model.CachedGetRsp](consts.Get, "/api/caches/:id")
	exchangeCached = grpc.BidiStreamCall[*model.Cached, *model.CachedKeyReq, *model.CachedExchangeRsp]("/api/caches/exchange")
	loadCached     = grpc.ClientStreamCall[*model.Cached, *model.CachedReq, *model.CachedLoadRsp]("/api/caches/load")
)

// CreateCached serves the Create action of Cached on /api/caches.
func (cachedService) CreateCached(ctx context.Context, req *CreateCachedRequest) (*CreateCachedResponse, error) {
	payload, err := CachedReqFromProto(req.GetPayload())
	if err != nil {
		return nil, err
	}
	result, err := createCached(ctx, nil, grpc.Query{}, payload)
	if err != nil {
		return nil, err
	}
	return &CreateCachedResponse{Result: CachedCreateRspToProto(result)}, nil
}

// DeleteCached serves the Delete action of Cached on /api/caches/:id.
func (cachedService) DeleteCached(ctx context.Context, req *DeleteCachedRequest) (*DeleteCachedResponse, error) {
	result, err := deleteCached(ctx, map[string]string{"id": req.GetId()}, grpc.Query{}, new(gstmodel.Empty))
	if err != nil {
		return nil, err
	}
	return &DeleteCachedResponse{Result: CachedDeleteRspToProto(result)}, nil
}

// GetCached serves the Get action of Cached on /api/caches/:id.
func (cachedService) GetCached(ctx context.Context, req *GetCachedRequest) (*GetCachedResponse, error) {
	result, err := getCached(ctx, map[string]string{"id": req.GetId()}, grpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()}, new(gstmodel.Empty))
	if err != nil {
		return nil, err
	}
	return &GetCachedResponse{Result: CachedGetRspToProto(result)}, nil
}

// ExchangeCached serves the Stream action of Cached declared on
// caches/exchange, served over gRPC alone.
func (cachedService) ExchangeCached(srv CachedService_ExchangeCachedServer) error {
	return exchangeCached(srv.Context(), nil, func() (*model.CachedKeyReq, error) {
		msg, recvErr := srv.Recv()
		if recvErr != nil {
			return nil, recvErr
		}
		return CachedKeyReqFromProto(msg.GetPayload())
	}, func(rsp *model.CachedExchangeRsp) error {
		return srv.Send(&ExchangeCachedResponse{Result: CachedExchangeRspToProto(rsp)})
	})
}

// LoadCached serves the Stream action of Cached declared on caches/load,
// served over gRPC alone.
func (cachedService) LoadCached(srv CachedService_LoadCachedServer) error {
	result, err := loadCached(srv.Context(), nil, func() (*model.CachedReq, error) {
		msg, recvErr := srv.Recv()
		if recvErr != nil {
			return nil, recvErr
		}
		return CachedReqFromProto(msg.GetPayload())
	})
	if err != nil {
		return err
	}
	return srv.SendAndClose(&LoadCachedResponse{Result: CachedLoadRspToProto(result)})
}

// CachedReqToProto encodes CachedReq values into their message, nil into
// nil.
func CachedReqToProto(m *model.CachedReq) *CachedReq {
	if m == nil {
		return nil
	}
	p := new(CachedReq)
	p.Key = m.Key
	p.Value = m.Value
	return p
}

// CachedReqFromProto decodes CachedReq messages into values, nil into nil.
func CachedReqFromProto(p *CachedReq) (*model.CachedReq, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CachedReq)
	m.Key = p.GetKey()
	m.Value = p.GetValue()
	return m, nil
}

// CachedCreateRspToProto encodes CachedCreateRsp values into their message,
// nil into nil.
func CachedCreateRspToProto(m *model.CachedCreateRsp) *CachedCreateRsp {
	if m == nil {
		return nil
	}
	p := new(CachedCreateRsp)
	p.Replica = m.Replica
	p.Key = m.Key
	p.Value = m.Value
	p.Found = m.Found
	return p
}

// CachedCreateRspFromProto decodes CachedCreateRsp messages into values, nil
// into nil.
func CachedCreateRspFromProto(p *CachedCreateRsp) (*model.CachedCreateRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CachedCreateRsp)
	m.Replica = p.GetReplica()
	m.Key = p.GetKey()
	m.Value = p.GetValue()
	m.Found = p.GetFound()
	return m, nil
}

// CachedDeleteRspToProto encodes CachedDeleteRsp values into their message,
// nil into nil.
func CachedDeleteRspToProto(m *model.CachedDeleteRsp) *CachedDeleteRsp {
	if m == nil {
		return nil
	}
	p := new(CachedDeleteRsp)
	p.Replica = m.Replica
	p.Key = m.Key
	return p
}

// CachedDeleteRspFromProto decodes CachedDeleteRsp messages into values, nil
// into nil.
func CachedDeleteRspFromProto(p *CachedDeleteRsp) (*model.CachedDeleteRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CachedDeleteRsp)
	m.Replica = p.GetReplica()
	m.Key = p.GetKey()
	return m, nil
}

// CachedGetRspToProto encodes CachedGetRsp values into their message, nil
// into nil.
func CachedGetRspToProto(m *model.CachedGetRsp) *CachedGetRsp {
	if m == nil {
		return nil
	}
	p := new(CachedGetRsp)
	p.Replica = m.Replica
	p.Key = m.Key
	p.Value = m.Value
	p.Found = m.Found
	return p
}

// CachedGetRspFromProto decodes CachedGetRsp messages into values, nil into
// nil.
func CachedGetRspFromProto(p *CachedGetRsp) (*model.CachedGetRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CachedGetRsp)
	m.Replica = p.GetReplica()
	m.Key = p.GetKey()
	m.Value = p.GetValue()
	m.Found = p.GetFound()
	return m, nil
}

// CachedKeyReqToProto encodes CachedKeyReq values into their message, nil
// into nil.
func CachedKeyReqToProto(m *model.CachedKeyReq) *CachedKeyReq {
	if m == nil {
		return nil
	}
	p := new(CachedKeyReq)
	p.Key = m.Key
	return p
}

// CachedKeyReqFromProto decodes CachedKeyReq messages into values, nil into
// nil.
func CachedKeyReqFromProto(p *CachedKeyReq) (*model.CachedKeyReq, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CachedKeyReq)
	m.Key = p.GetKey()
	return m, nil
}

// CachedExchangeRspToProto encodes CachedExchangeRsp values into their
// message, nil into nil.
func CachedExchangeRspToProto(m *model.CachedExchangeRsp) *CachedExchangeRsp {
	if m == nil {
		return nil
	}
	p := new(CachedExchangeRsp)
	p.Replica = m.Replica
	p.Key = m.Key
	p.Value = m.Value
	p.Found = m.Found
	return p
}

// CachedExchangeRspFromProto decodes CachedExchangeRsp messages into values,
// nil into nil.
func CachedExchangeRspFromProto(p *CachedExchangeRsp) (*model.CachedExchangeRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CachedExchangeRsp)
	m.Replica = p.GetReplica()
	m.Key = p.GetKey()
	m.Value = p.GetValue()
	m.Found = p.GetFound()
	return m, nil
}

// CachedLoadRspToProto encodes CachedLoadRsp values into their message, nil
// into nil.
func CachedLoadRspToProto(m *model.CachedLoadRsp) *CachedLoadRsp {
	if m == nil {
		return nil
	}
	p := new(CachedLoadRsp)
	p.Replica = m.Replica
	p.Count = m.Count
	return p
}

// CachedLoadRspFromProto decodes CachedLoadRsp messages into values, nil
// into nil.
func CachedLoadRspFromProto(p *CachedLoadRsp) (*model.CachedLoadRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CachedLoadRsp)
	m.Replica = p.GetReplica()
	m.Count = p.GetCount()
	return m, nil
}
