// Code generated by gst; DO NOT EDIT.

package pb

import (
	"cluster/model"
	"context"

	"github.com/hydroan/gst/grpc"
)

// counterStepService serves the rpcs of the CounterStepService service
// through the actions of CounterStep: every handler decodes its request
// message into what the action's call takes, runs the call and encodes what
// it answers into the response message.
type counterStepService struct {
	UnimplementedCounterStepServiceServer
}

// The calls of the actions of CounterStep, one per rpc of
// CounterStepService, built once at package initialization.
var (
	listCounterStep  = grpc.ListCall[*model.CounterStep]("/api/counter_steps")
	watchCounterStep = grpc.ServerStreamCall[*model.CounterStep, *model.CounterStepWatchReq, *model.CounterStep]("/api/counter_steps/watch")
)

// ListCounterStep serves the List action of CounterStep on
// /api/counter_steps.
func (counterStepService) ListCounterStep(ctx context.Context, req *ListCounterStepRequest) (*ListCounterStepResponse, error) {
	models, total, err := listCounterStep(ctx, nil, grpc.Query{
		Filters:     grpc.Filters(req.GetFilters()),
		SortBy:      req.GetSortBy(),
		Page:        req.GetPage(),
		Size:        req.GetSize(),
		CursorField: req.GetCursorField(),
		CursorValue: req.GetCursorValue(),
		CursorNext:  req.GetCursorNext(),
		Expand:      req.GetExpand(),
		Depth:       req.GetDepth(),
	})
	if err != nil {
		return nil, err
	}
	items := make([]*CounterStep, len(models))
	for i, m := range models {
		items[i] = CounterStepToProto(m)
	}
	return &ListCounterStepResponse{Items: items, Total: int64(total)}, nil
}

// WatchCounterStep serves the Stream action of CounterStep declared on
// counter_steps/watch, served over gRPC alone.
func (counterStepService) WatchCounterStep(req *WatchCounterStepRequest, srv CounterStepService_WatchCounterStepServer) error {
	payload, err := CounterStepWatchReqFromProto(req.GetPayload())
	if err != nil {
		return err
	}
	return watchCounterStep(srv.Context(), nil, payload, func(rsp *model.CounterStep) error {
		return srv.Send(&WatchCounterStepResponse{Result: CounterStepToProto(rsp)})
	})
}

// CounterStepToProto encodes CounterStep values into their message, nil into
// nil.
func CounterStepToProto(m *model.CounterStep) *CounterStep {
	if m == nil {
		return nil
	}
	p := new(CounterStep)
	p.Id = grpc.UTF8(m.ID)
	p.CreatedBy = grpc.UTF8(m.CreatedBy)
	p.UpdatedBy = grpc.UTF8(m.UpdatedBy)
	p.CreatedAt = grpc.Timestamp(m.CreatedAt)
	p.UpdatedAt = grpc.Timestamp(m.UpdatedAt)
	p.Seq = m.Seq
	p.Tenure = grpc.UTF8(m.Tenure)
	p.Replica = grpc.UTF8(m.Replica)
	return p
}

// CounterStepFromProto decodes CounterStep messages into values, nil into
// nil. A value a field cannot hold, an integer out of its range, a string
// that is no JSON number, a time outside the years 1 to 9999, bytes that are
// no JSON document or a number that is not finite, is refused with
// InvalidArgument.
func CounterStepFromProto(p *CounterStep) (*model.CounterStep, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CounterStep)
	var err error
	m.ID = p.GetId()
	m.CreatedBy = p.GetCreatedBy()
	m.UpdatedBy = p.GetUpdatedBy()
	m.CreatedAt, err = grpc.Time("created_at", p.GetCreatedAt())
	if err != nil {
		return nil, err
	}
	m.UpdatedAt, err = grpc.Time("updated_at", p.GetUpdatedAt())
	if err != nil {
		return nil, err
	}
	m.Seq = p.GetSeq()
	m.Tenure = p.GetTenure()
	m.Replica = p.GetReplica()
	return m, nil
}

// CounterStepWatchReqToProto encodes CounterStepWatchReq values into their
// message, nil into nil.
func CounterStepWatchReqToProto(m *model.CounterStepWatchReq) *CounterStepWatchReq {
	if m == nil {
		return nil
	}
	p := new(CounterStepWatchReq)
	p.After = m.After
	return p
}

// CounterStepWatchReqFromProto decodes CounterStepWatchReq messages into
// values, nil into nil.
func CounterStepWatchReqFromProto(p *CounterStepWatchReq) (*model.CounterStepWatchReq, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.CounterStepWatchReq)
	m.After = p.GetAfter()
	return m, nil
}
