// Code generated by gst; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cluster/counter_step.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CounterStep is one number of the counter the leader work keeps: every second
// the leader appends the next number, in a transaction under its lease. Seq is
// unique, so no number is written twice, and Tenure names the leadership that
// wrote it: the numbers of one tenure form one unbroken run, and the runs
// follow each other, unless two leaderships ever wrote at the same time. The
// counter lives in the database, so a replica taking the leadership over
// continues from the last number.
type CounterStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the record, assigned when it is created.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The id of the user who created the record.
	CreatedBy string `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The id of the user who last updated the record.
	UpdatedBy string `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// When the record was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the record was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Seq       int64                  `protobuf:"varint,11,opt,name=seq,proto3" json:"seq,omitempty"`
	// one id per leadership, drawn as it starts
	Tenure string `protobuf:"bytes,12,opt,name=tenure,proto3" json:"tenure,omitempty"`
	// the replica that led, see helper.Replica
	Replica       string `protobuf:"bytes,13,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterStep) Reset() {
	*x = CounterStep{}
	mi := &file_cluster_counter_step_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterStep) ProtoMessage() {}

func (x *CounterStep) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_counter_step_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterStep.ProtoReflect.Descriptor instead.
func (*CounterStep) Descriptor() ([]byte, []int) {
	return file_cluster_counter_step_proto_rawDescGZIP(), []int{0}
}

func (x *CounterStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CounterStep) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CounterStep) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *CounterStep) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CounterStep) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CounterStep) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CounterStep) GetTenure() string {
	if x != nil {
		return x.Tenure
	}
	return ""
}

func (x *CounterStep) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

// ListCounterStepRequest is the request of CounterStepService.ListCounterStep.
type ListCounterStepRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filters is the filters to apply, each one field[op]=value of the HTTP query.
	Filters []*ListCounterStepRequest_Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	// sort_by is the orderings, as the _sort_by query parameter names them.
	SortBy []string `protobuf:"bytes,2,rep,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// page is the page to list, as the _page query parameter.
	Page uint32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// size is the page size, as the _size query parameter, 20 when unset and at most 100.
	Size uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// cursor_field is the cursor column, as the _cursor_field query parameter.
	CursorField string `protobuf:"bytes,5,opt,name=cursor_field,json=cursorField,proto3" json:"cursor_field,omitempty"`
	// cursor_value is the cursor position, as the _cursor_value query parameter.
	CursorValue string `protobuf:"bytes,6,opt,name=cursor_value,json=cursorValue,proto3" json:"cursor_value,omitempty"`
	// cursor_next is whether to list past the cursor, as the _cursor_next query parameter.
	CursorNext bool `protobuf:"varint,7,opt,name=cursor_next,json=cursorNext,proto3" json:"cursor_next,omitempty"`
	// expand is the associations to expand, as the _expand query parameter names them.
	Expand []string `protobuf:"bytes,8,rep,name=expand,proto3" json:"expand,omitempty"`
	// depth is the depth of the expansion, as the _depth query parameter.
	Depth         uint32 `protobuf:"varint,9,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCounterStepRequest) Reset() {
	*x = ListCounterStepRequest{}
	mi := &file_cluster_counter_step_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCounterStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCounterStepRequest) ProtoMessage() {}

func (x *ListCounterStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_counter_step_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCounterStepRequest.ProtoReflect.Descriptor instead.
func (*ListCounterStepRequest) Descriptor() ([]byte, []int) {
	return file_cluster_counter_step_proto_rawDescGZIP(), []int{1}
}

func (x *ListCounterStepRequest) GetFilters() []*ListCounterStepRequest_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListCounterStepRequest) GetSortBy() []string {
	if x != nil {
		return x.SortBy
	}
	return nil
}

func (x *ListCounterStepRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCounterStepRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListCounterStepRequest) GetCursorField() string {
	if x != nil {
		return x.CursorField
	}
	return ""
}

func (x *ListCounterStepRequest) GetCursorValue() string {
	if x != nil {
		return x.CursorValue
	}
	return ""
}

func (x *ListCounterStepRequest) GetCursorNext() bool {
	if x != nil {
		return x.CursorNext
	}
	return false
}

func (x *ListCounterStepRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *ListCounterStepRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// ListCounterStepResponse is the response of CounterStepService.ListCounterStep.
type ListCounterStepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the CounterStep records of the page.
	Items []*CounterStep `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// total is the number of records the filters match, 0 under cursor pagination.
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCounterStepResponse) Reset() {
	*x = ListCounterStepResponse{}
	mi := &file_cluster_counter_step_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCounterStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCounterStepResponse) ProtoMessage() {}

func (x *ListCounterStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_counter_step_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCounterStepResponse.ProtoReflect.Descriptor instead.
func (*ListCounterStepResponse) Descriptor() ([]byte, []int) {
	return file_cluster_counter_step_proto_rawDescGZIP(), []int{2}
}

func (x *ListCounterStepResponse) GetItems() []*CounterStep {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCounterStepResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// WatchCounterStepRequest is the request of CounterStepService.WatchCounterStep.
type WatchCounterStepRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the CounterStepWatchReq the action takes.
	Payload       *CounterStepWatchReq `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCounterStepRequest) Reset() {
	*x = WatchCounterStepRequest{}
	mi := &file_cluster_counter_step_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCounterStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCounterStepRequest) ProtoMessage() {}

func (x *WatchCounterStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_counter_step_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCounterStepRequest.ProtoReflect.Descriptor instead.
func (*WatchCounterStepRequest) Descriptor() ([]byte, []int) {
	return file_cluster_counter_step_proto_rawDescGZIP(), []int{3}
}

func (x *WatchCounterStepRequest) GetPayload() *CounterStepWatchReq {
	if x != nil {
		return x.Payload
	}
	return nil
}

// WatchCounterStepResponse is the response of CounterStepService.WatchCounterStep.
type WatchCounterStepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the CounterStep the action answers with.
	Result        *CounterStep `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCounterStepResponse) Reset() {
	*x = WatchCounterStepResponse{}
	mi := &file_cluster_counter_step_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCounterStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCounterStepResponse) ProtoMessage() {}

func (x *WatchCounterStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_counter_step_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCounterStepResponse.ProtoReflect.Descriptor instead.
func (*WatchCounterStepResponse) Descriptor() ([]byte, []int) {
	return file_cluster_counter_step_proto_rawDescGZIP(), []int{4}
}

func (x *WatchCounterStepResponse) GetResult() *CounterStep {
	if x != nil {
		return x.Result
	}
	return nil
}

// CounterStepWatchReq says where a watch starts.
type CounterStepWatchReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the numbers after it are streamed, so a client that lost its stream resumes from the last number it saw
	After         int64 `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterStepWatchReq) Reset() {
	*x = CounterStepWatchReq{}
	mi := &file_cluster_counter_step_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterStepWatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterStepWatchReq) ProtoMessage() {}

func (x *CounterStepWatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_counter_step_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterStepWatchReq.ProtoReflect.Descriptor instead.
func (*CounterStepWatchReq) Descriptor() ([]byte, []int) {
	return file_cluster_counter_step_proto_rawDescGZIP(), []int{5}
}

func (x *CounterStepWatchReq) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

// Filter is one filter of filters: field names the column by its query name, op is the operator, none for the equality every model answers, and values is its value, several for in and notin.
type ListCounterStepRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCounterStepRequest_Filter) Reset() {
	*x = ListCounterStepRequest_Filter{}
	mi := &file_cluster_counter_step_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCounterStepRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCounterStepRequest_Filter) ProtoMessage() {}

func (x *ListCounterStepRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_counter_step_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCounterStepRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListCounterStepRequest_Filter) Descriptor() ([]byte, []int) {
	return file_cluster_counter_step_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListCounterStepRequest_Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListCounterStepRequest_Filter) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ListCounterStepRequest_Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_cluster_counter_step_proto protoreflect.FileDescriptor

const file_cluster_counter_step_proto_rawDesc = "" +
	"\n" +
	"\x1acluster/counter_step.proto\x12\acluster\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\vCounterStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x10\n" +
	"\x03seq\x18\v \x01(\x03R\x03seq\x12\x16\n" +
	"\x06tenure\x18\f \x01(\tR\x06tenure\x12\x18\n" +
	"\areplica\x18\r \x01(\tR\areplica\"\xf8\x02\n" +
	"\x16ListCounterStepRequest\x12@\n" +
	"\afilters\x18\x01 \x03(\v2&.cluster.ListCounterStepRequest.FilterR\afilters\x12\x17\n" +
	"\asort_by\x18\x02 \x03(\tR\x06sortBy\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12!\n" +
	"\fcursor_field\x18\x05 \x01(\tR\vcursorField\x12!\n" +
	"\fcursor_value\x18\x06 \x01(\tR\vcursorValue\x12\x1f\n" +
	"\vcursor_next\x18\a \x01(\bR\n" +
	"cursorNext\x12\x16\n" +
	"\x06expand\x18\b \x03(\tR\x06expand\x12\x14\n" +
	"\x05depth\x18\t \x01(\rR\x05depth\x1aF\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"[\n" +
	"\x17ListCounterStepResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.cluster.CounterStepR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"Q\n" +
	"\x17WatchCounterStepRequest\x126\n" +
	"\apayload\x18\x01 \x01(\v2\x1c.cluster.CounterStepWatchReqR\apayload\"H\n" +
	"\x18WatchCounterStepResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.cluster.CounterStepR\x06result\"+\n" +
	"\x13CounterStepWatchReq\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x03R\x05after2\xc5\x01\n" +
	"\x12CounterStepService\x12T\n" +
	"\x0fListCounterStep\x12\x1f.cluster.ListCounterStepRequest\x1a .cluster.ListCounterStepResponse\x12Y\n" +
	"\x10WatchCounterStep\x12 .cluster.WatchCounterStepRequest\x1a!.cluster.WatchCounterStepResponse0\x01B\x0fZ\rcluster/pb;pbb\x06proto3"

var (
	file_cluster_counter_step_proto_rawDescOnce sync.Once
	file_cluster_counter_step_proto_rawDescData []byte
)

func file_cluster_counter_step_proto_rawDescGZIP() []byte {
	file_cluster_counter_step_proto_rawDescOnce.Do(func() {
		file_cluster_counter_step_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_counter_step_proto_rawDesc), len(file_cluster_counter_step_proto_rawDesc)))
	})
	return file_cluster_counter_step_proto_rawDescData
}

var file_cluster_counter_step_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cluster_counter_step_proto_goTypes = []any{
	(*CounterStep)(nil),                   // 0: cluster.CounterStep
	(*ListCounterStepRequest)(nil),        // 1: cluster.ListCounterStepRequest
	(*ListCounterStepResponse)(nil),       // 2: cluster.ListCounterStepResponse
	(*WatchCounterStepRequest)(nil),       // 3: cluster.WatchCounterStepRequest
	(*WatchCounterStepResponse)(nil),      // 4: cluster.WatchCounterStepResponse
	(*CounterStepWatchReq)(nil),           // 5: cluster.CounterStepWatchReq
	(*ListCounterStepRequest_Filter)(nil), // 6: cluster.ListCounterStepRequest.Filter
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
}
var file_cluster_counter_step_proto_depIdxs = []int32{
	7, // 0: cluster.CounterStep.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: cluster.CounterStep.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: cluster.ListCounterStepRequest.filters:type_name -> cluster.ListCounterStepRequest.Filter
	0, // 3: cluster.ListCounterStepResponse.items:type_name -> cluster.CounterStep
	5, // 4: cluster.WatchCounterStepRequest.payload:type_name -> cluster.CounterStepWatchReq
	0, // 5: cluster.WatchCounterStepResponse.result:type_name -> cluster.CounterStep
	1, // 6: cluster.CounterStepService.ListCounterStep:input_type -> cluster.ListCounterStepRequest
	3, // 7: cluster.CounterStepService.WatchCounterStep:input_type -> cluster.WatchCounterStepRequest
	2, // 8: cluster.CounterStepService.ListCounterStep:output_type -> cluster.ListCounterStepResponse
	4, // 9: cluster.CounterStepService.WatchCounterStep:output_type -> cluster.WatchCounterStepResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cluster_counter_step_proto_init() }
func file_cluster_counter_step_proto_init() {
	if File_cluster_counter_step_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_counter_step_proto_rawDesc), len(file_cluster_counter_step_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_counter_step_proto_goTypes,
		DependencyIndexes: file_cluster_counter_step_proto_depIdxs,
		MessageInfos:      file_cluster_counter_step_proto_msgTypes,
	}.Build()
	File_cluster_counter_step_proto = out.File
	file_cluster_counter_step_proto_goTypes = nil
	file_cluster_counter_step_proto_depIdxs = nil
}
