// Code generated by gst; DO NOT EDIT.

package pb

import (
	"cluster/model"
	"context"

	"github.com/hydroan/gst/grpc"
)

// flagService serves the rpcs of the FlagService service through the actions
// of Flag: every handler decodes its request message into what the action's
// call takes, runs the call and encodes what it answers into the response
// message.
type flagService struct {
	UnimplementedFlagServiceServer
}

// The calls of the actions of Flag, one per rpc of FlagService, built once
// at package initialization.
var (
	createFlag     = grpc.CreateCall[*model.Flag]("/api/flags")
	deleteFlag     = grpc.DeleteCall[*model.Flag]("/api/flags/:id")
	updateFlag     = grpc.UpdateCall[*model.Flag]("/api/flags/:id")
	patchFlag      = grpc.PatchCall[*model.Flag]("/api/flags/:id")
	listFlag       = grpc.ListCall[*model.Flag]("/api/flags")
	getFlag        = grpc.GetCall[*model.Flag]("/api/flags/:id")
	createManyFlag = grpc.CreateManyCall[*model.Flag]("/api/flags/batch")
	deleteManyFlag = grpc.DeleteManyCall[*model.Flag]("/api/flags/batch")
	updateManyFlag = grpc.UpdateManyCall[*model.Flag]("/api/flags/batch")
	patchManyFlag  = grpc.PatchManyCall[*model.Flag]("/api/flags/batch")
)

// CreateFlag serves the Create action of Flag on /api/flags.
func (flagService) CreateFlag(ctx context.Context, req *CreateFlagRequest) (*CreateFlagResponse, error) {
	in, err := FlagFromProto(req.GetFlag())
	if err != nil {
		return nil, err
	}
	m, err := createFlag(ctx, nil, in)
	if err != nil {
		return nil, err
	}
	return &CreateFlagResponse{Flag: FlagToProto(m)}, nil
}

// DeleteFlag serves the Delete action of Flag on /api/flags/:id.
func (flagService) DeleteFlag(ctx context.Context, req *DeleteFlagRequest) (*DeleteFlagResponse, error) {
	if err := deleteFlag(ctx, map[string]string{"id": req.GetId()}, req.GetId()); err != nil {
		return nil, err
	}
	return &DeleteFlagResponse{}, nil
}

// UpdateFlag serves the Update action of Flag on /api/flags/:id.
func (flagService) UpdateFlag(ctx context.Context, req *UpdateFlagRequest) (*UpdateFlagResponse, error) {
	in, err := FlagFromProto(req.GetFlag())
	if err != nil {
		return nil, err
	}
	m, err := updateFlag(ctx, map[string]string{"id": req.GetId()}, req.GetId(), in)
	if err != nil {
		return nil, err
	}
	return &UpdateFlagResponse{Flag: FlagToProto(m)}, nil
}

// PatchFlag serves the Patch action of Flag on /api/flags/:id.
func (flagService) PatchFlag(ctx context.Context, req *PatchFlagRequest) (*PatchFlagResponse, error) {
	in, err := FlagFromProto(req.GetFlag())
	if err != nil {
		return nil, err
	}
	m, err := patchFlag(ctx, map[string]string{"id": req.GetId()}, req.GetId(), in, req.GetUpdateMask().GetPaths())
	if err != nil {
		return nil, err
	}
	return &PatchFlagResponse{Flag: FlagToProto(m)}, nil
}

// ListFlag serves the List action of Flag on /api/flags.
func (flagService) ListFlag(ctx context.Context, req *ListFlagRequest) (*ListFlagResponse, error) {
	models, total, err := listFlag(ctx, nil, grpc.Query{
		Filters:     grpc.Filters(req.GetFilters()),
		SortBy:      req.GetSortBy(),
		Page:        req.GetPage(),
		Size:        req.GetSize(),
		CursorField: req.GetCursorField(),
		CursorValue: req.GetCursorValue(),
		CursorNext:  req.GetCursorNext(),
		Expand:      req.GetExpand(),
		Depth:       req.GetDepth(),
	})
	if err != nil {
		return nil, err
	}
	items := make([]*Flag, len(models))
	for i, m := range models {
		items[i] = FlagToProto(m)
	}
	return &ListFlagResponse{Items: items, Total: int64(total)}, nil
}

// GetFlag serves the Get action of Flag on /api/flags/:id.
func (flagService) GetFlag(ctx context.Context, req *GetFlagRequest) (*GetFlagResponse, error) {
	m, err := getFlag(ctx, map[string]string{"id": req.GetId()}, req.GetId(), grpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()})
	if err != nil {
		return nil, err
	}
	return &GetFlagResponse{Flag: FlagToProto(m)}, nil
}

// CreateManyFlag serves the CreateMany action of Flag on /api/flags/batch.
func (flagService) CreateManyFlag(ctx context.Context, req *CreateManyFlagRequest) (*CreateManyFlagResponse, error) {
	models := make([]*model.Flag, len(req.GetItems()))
	for i, item := range req.GetItems() {
		in, err := FlagFromProto(item)
		if err != nil {
			return nil, err
		}
		models[i] = in
	}
	stored, err := createManyFlag(ctx, nil, models)
	if err != nil {
		return nil, err
	}
	items := make([]*Flag, len(stored))
	for i, m := range stored {
		items[i] = FlagToProto(m)
	}
	return &CreateManyFlagResponse{Items: items}, nil
}

// DeleteManyFlag serves the DeleteMany action of Flag on /api/flags/batch.
func (flagService) DeleteManyFlag(ctx context.Context, req *DeleteManyFlagRequest) (*DeleteManyFlagResponse, error) {
	if err := deleteManyFlag(ctx, nil, req.GetIds()); err != nil {
		return nil, err
	}
	return &DeleteManyFlagResponse{}, nil
}

// UpdateManyFlag serves the UpdateMany action of Flag on /api/flags/batch.
func (flagService) UpdateManyFlag(ctx context.Context, req *UpdateManyFlagRequest) (*UpdateManyFlagResponse, error) {
	models := make([]*model.Flag, len(req.GetItems()))
	for i, item := range req.GetItems() {
		in, err := FlagFromProto(item)
		if err != nil {
			return nil, err
		}
		models[i] = in
	}
	stored, err := updateManyFlag(ctx, nil, models)
	if err != nil {
		return nil, err
	}
	items := make([]*Flag, len(stored))
	for i, m := range stored {
		items[i] = FlagToProto(m)
	}
	return &UpdateManyFlagResponse{Items: items}, nil
}

// PatchManyFlag serves the PatchMany action of Flag on /api/flags/batch.
func (flagService) PatchManyFlag(ctx context.Context, req *PatchManyFlagRequest) (*PatchManyFlagResponse, error) {
	models := make([]*model.Flag, len(req.GetItems()))
	masks := make([][]string, len(req.GetItems()))
	for i, item := range req.GetItems() {
		in, err := FlagFromProto(item.GetFlag())
		if err != nil {
			return nil, err
		}
		m, err := grpc.PatchItem(i, nil, nil, item.GetId(), in)
		if err != nil {
			return nil, err
		}
		models[i] = m
		masks[i] = item.GetUpdateMask().GetPaths()
	}
	stored, err := patchManyFlag(ctx, nil, models, masks)
	if err != nil {
		return nil, err
	}
	items := make([]*Flag, len(stored))
	for i, m := range stored {
		items[i] = FlagToProto(m)
	}
	return &PatchManyFlagResponse{Items: items}, nil
}

// FlagToProto encodes Flag values into their message, nil into nil.
func FlagToProto(m *model.Flag) *Flag {
	if m == nil {
		return nil
	}
	p := new(Flag)
	p.Id = grpc.UTF8(m.ID)
	p.CreatedBy = grpc.UTF8(m.CreatedBy)
	p.UpdatedBy = grpc.UTF8(m.UpdatedBy)
	p.CreatedAt = grpc.Timestamp(m.CreatedAt)
	p.UpdatedAt = grpc.Timestamp(m.UpdatedAt)
	p.Name = grpc.UTF8(m.Name)
	p.On = m.On
	p.Percent = int64(m.Percent)
	p.Note = grpc.UTF8(m.Note)
	return p
}

// FlagFromProto decodes Flag messages into values, nil into nil. A value a
// field cannot hold, an integer out of its range, a string that is no JSON
// number, a time outside the years 1 to 9999, bytes that are no JSON
// document or a number that is not finite, is refused with InvalidArgument.
func FlagFromProto(p *Flag) (*model.Flag, error) {
	if p == nil {
		return nil, nil
	}
	m := new(model.Flag)
	var err error
	m.ID = p.GetId()
	m.CreatedBy = p.GetCreatedBy()
	m.UpdatedBy = p.GetUpdatedBy()
	m.CreatedAt, err = grpc.Time("created_at", p.GetCreatedAt())
	if err != nil {
		return nil, err
	}
	m.UpdatedAt, err = grpc.Time("updated_at", p.GetUpdatedAt())
	if err != nil {
		return nil, err
	}
	m.Name = p.GetName()
	m.On = p.GetOn()
	m.Percent = int(p.GetPercent())
	m.Note = p.GetNote()
	return m, nil
}
