// Code generated by gst; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cluster/flag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Flag is a switch every replica reads from the shared database: turned on or
// off through any replica, over HTTP or gRPC, it is what all of them see from
// then on. It declares the whole standard set of actions, the batch ones
// included, so every standard rpc has a table behind it in this project. The
// Create hook in service/flag checks the name and fills in the percent of a
// flag turned on without one: a binding tag would apply to a patch too, which
// carries only the fields it changes.
type Flag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the record, assigned when it is created.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The username of the user who created the record.
	CreatedBy string `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The username of the user who last updated the record.
	UpdatedBy string `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// When the record was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the record was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name      string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	On        bool                   `protobuf:"varint,12,opt,name=on,proto3" json:"on,omitempty"`
	// the share of traffic the flag applies to, 0 to 100
	Percent       int64  `protobuf:"varint,13,opt,name=percent,proto3" json:"percent,omitempty"`
	Note          string `protobuf:"bytes,14,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_cluster_flag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{0}
}

func (x *Flag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flag) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Flag) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Flag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Flag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *Flag) GetPercent() int64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Flag) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// CreateFlagRequest is the request of FlagService.CreateFlag.
type CreateFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// flag is the Flag to create.
	Flag          *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFlagRequest) Reset() {
	*x = CreateFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagRequest) ProtoMessage() {}

func (x *CreateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagRequest.ProtoReflect.Descriptor instead.
func (*CreateFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFlagRequest) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// CreateFlagResponse is the response of FlagService.CreateFlag.
type CreateFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// flag is the Flag created.
	Flag          *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFlagResponse) Reset() {
	*x = CreateFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagResponse) ProtoMessage() {}

func (x *CreateFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagResponse.ProtoReflect.Descriptor instead.
func (*CreateFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// DeleteFlagRequest is the request of FlagService.DeleteFlag.
type DeleteFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the id of the Flag to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlagRequest) Reset() {
	*x = DeleteFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagRequest) ProtoMessage() {}

func (x *DeleteFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagRequest.ProtoReflect.Descriptor instead.
func (*DeleteFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFlagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteFlagResponse is the response of FlagService.DeleteFlag.
type DeleteFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlagResponse) Reset() {
	*x = DeleteFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagResponse) ProtoMessage() {}

func (x *DeleteFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagResponse.ProtoReflect.Descriptor instead.
func (*DeleteFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{4}
}

// UpdateFlagRequest is the request of FlagService.UpdateFlag.
type UpdateFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the id of the Flag to replace.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// flag is the replacement.
	Flag          *Flag `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlagRequest) Reset() {
	*x = UpdateFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlagRequest) ProtoMessage() {}

func (x *UpdateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlagRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFlagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFlagRequest) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// UpdateFlagResponse is the response of FlagService.UpdateFlag.
type UpdateFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// flag is the Flag as stored.
	Flag          *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlagResponse) Reset() {
	*x = UpdateFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlagResponse) ProtoMessage() {}

func (x *UpdateFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlagResponse.ProtoReflect.Descriptor instead.
func (*UpdateFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// PatchFlagRequest is the request of FlagService.PatchFlag and an item of FlagService.PatchManyFlag.
type PatchFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the id of the Flag to patch.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// flag is the values to apply.
	Flag *Flag `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	// update_mask is the fields of flag to apply, named as the message names them.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchFlagRequest) Reset() {
	*x = PatchFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchFlagRequest) ProtoMessage() {}

func (x *PatchFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchFlagRequest.ProtoReflect.Descriptor instead.
func (*PatchFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{7}
}

func (x *PatchFlagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchFlagRequest) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *PatchFlagRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// PatchFlagResponse is the response of FlagService.PatchFlag.
type PatchFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// flag is the Flag as stored.
	Flag          *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchFlagResponse) Reset() {
	*x = PatchFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchFlagResponse) ProtoMessage() {}

func (x *PatchFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchFlagResponse.ProtoReflect.Descriptor instead.
func (*PatchFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{8}
}

func (x *PatchFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// ListFlagRequest is the request of FlagService.ListFlag.
type ListFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filters is the filters to apply, each one field[op]=value of the HTTP query.
	Filters []*ListFlagRequest_Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	// sort_by is the orderings, as the _sort_by query parameter names them.
	SortBy []string `protobuf:"bytes,2,rep,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// page is the page to list, as the _page query parameter.
	Page uint32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// size is the page size, as the _size query parameter, 20 when unset and at most 100.
	Size uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// cursor_field is the cursor column, as the _cursor_field query parameter.
	CursorField string `protobuf:"bytes,5,opt,name=cursor_field,json=cursorField,proto3" json:"cursor_field,omitempty"`
	// cursor_value is the cursor position, as the _cursor_value query parameter.
	CursorValue string `protobuf:"bytes,6,opt,name=cursor_value,json=cursorValue,proto3" json:"cursor_value,omitempty"`
	// cursor_next is whether to list past the cursor, as the _cursor_next query parameter.
	CursorNext bool `protobuf:"varint,7,opt,name=cursor_next,json=cursorNext,proto3" json:"cursor_next,omitempty"`
	// expand is the associations to expand, as the _expand query parameter names them.
	Expand []string `protobuf:"bytes,8,rep,name=expand,proto3" json:"expand,omitempty"`
	// depth is the depth of the expansion, as the _depth query parameter.
	Depth         uint32 `protobuf:"varint,9,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagRequest) Reset() {
	*x = ListFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagRequest) ProtoMessage() {}

func (x *ListFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagRequest.ProtoReflect.Descriptor instead.
func (*ListFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{9}
}

func (x *ListFlagRequest) GetFilters() []*ListFlagRequest_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListFlagRequest) GetSortBy() []string {
	if x != nil {
		return x.SortBy
	}
	return nil
}

func (x *ListFlagRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFlagRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListFlagRequest) GetCursorField() string {
	if x != nil {
		return x.CursorField
	}
	return ""
}

func (x *ListFlagRequest) GetCursorValue() string {
	if x != nil {
		return x.CursorValue
	}
	return ""
}

func (x *ListFlagRequest) GetCursorNext() bool {
	if x != nil {
		return x.CursorNext
	}
	return false
}

func (x *ListFlagRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *ListFlagRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// ListFlagResponse is the response of FlagService.ListFlag.
type ListFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the Flag records of the page.
	Items []*Flag `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// total is the number of records the filters match, 0 under cursor pagination.
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagResponse) Reset() {
	*x = ListFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagResponse) ProtoMessage() {}

func (x *ListFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagResponse.ProtoReflect.Descriptor instead.
func (*ListFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{10}
}

func (x *ListFlagResponse) GetItems() []*Flag {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFlagResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetFlagRequest is the request of FlagService.GetFlag.
type GetFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the id of the Flag.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// expand is the associations to expand, as the _expand query parameter names them.
	Expand []string `protobuf:"bytes,2,rep,name=expand,proto3" json:"expand,omitempty"`
	// depth is the depth of the expansion, as the _depth query parameter.
	Depth         uint32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagRequest) Reset() {
	*x = GetFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagRequest) ProtoMessage() {}

func (x *GetFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagRequest.ProtoReflect.Descriptor instead.
func (*GetFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{11}
}

func (x *GetFlagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetFlagRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *GetFlagRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// GetFlagResponse is the response of FlagService.GetFlag.
type GetFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// flag is the Flag found.
	Flag          *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagResponse) Reset() {
	*x = GetFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagResponse) ProtoMessage() {}

func (x *GetFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagResponse.ProtoReflect.Descriptor instead.
func (*GetFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{12}
}

func (x *GetFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

// CreateManyFlagRequest is the request of FlagService.CreateManyFlag.
type CreateManyFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the Flag records to write.
	Items         []*Flag `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManyFlagRequest) Reset() {
	*x = CreateManyFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManyFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManyFlagRequest) ProtoMessage() {}

func (x *CreateManyFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManyFlagRequest.ProtoReflect.Descriptor instead.
func (*CreateManyFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{13}
}

func (x *CreateManyFlagRequest) GetItems() []*Flag {
	if x != nil {
		return x.Items
	}
	return nil
}

// CreateManyFlagResponse is the response of FlagService.CreateManyFlag.
type CreateManyFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the Flag records as stored.
	Items         []*Flag `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManyFlagResponse) Reset() {
	*x = CreateManyFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManyFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManyFlagResponse) ProtoMessage() {}

func (x *CreateManyFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManyFlagResponse.ProtoReflect.Descriptor instead.
func (*CreateManyFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{14}
}

func (x *CreateManyFlagResponse) GetItems() []*Flag {
	if x != nil {
		return x.Items
	}
	return nil
}

// DeleteManyFlagRequest is the request of FlagService.DeleteManyFlag.
type DeleteManyFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ids is the ids of the Flag records to delete.
	Ids           []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyFlagRequest) Reset() {
	*x = DeleteManyFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyFlagRequest) ProtoMessage() {}

func (x *DeleteManyFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyFlagRequest.ProtoReflect.Descriptor instead.
func (*DeleteManyFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteManyFlagRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// DeleteManyFlagResponse is the response of FlagService.DeleteManyFlag.
type DeleteManyFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyFlagResponse) Reset() {
	*x = DeleteManyFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyFlagResponse) ProtoMessage() {}

func (x *DeleteManyFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyFlagResponse.ProtoReflect.Descriptor instead.
func (*DeleteManyFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{16}
}

// UpdateManyFlagRequest is the request of FlagService.UpdateManyFlag.
type UpdateManyFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the Flag records to write.
	Items         []*Flag `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManyFlagRequest) Reset() {
	*x = UpdateManyFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManyFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyFlagRequest) ProtoMessage() {}

func (x *UpdateManyFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyFlagRequest.ProtoReflect.Descriptor instead.
func (*UpdateManyFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateManyFlagRequest) GetItems() []*Flag {
	if x != nil {
		return x.Items
	}
	return nil
}

// UpdateManyFlagResponse is the response of FlagService.UpdateManyFlag.
type UpdateManyFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the Flag records as stored.
	Items         []*Flag `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManyFlagResponse) Reset() {
	*x = UpdateManyFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManyFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyFlagResponse) ProtoMessage() {}

func (x *UpdateManyFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyFlagResponse.ProtoReflect.Descriptor instead.
func (*UpdateManyFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateManyFlagResponse) GetItems() []*Flag {
	if x != nil {
		return x.Items
	}
	return nil
}

// PatchManyFlagRequest is the request of FlagService.PatchManyFlag.
type PatchManyFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the patches, each a PatchFlagRequest naming the Flag it applies to by its id.
	Items         []*PatchFlagRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchManyFlagRequest) Reset() {
	*x = PatchManyFlagRequest{}
	mi := &file_cluster_flag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchManyFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchManyFlagRequest) ProtoMessage() {}

func (x *PatchManyFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchManyFlagRequest.ProtoReflect.Descriptor instead.
func (*PatchManyFlagRequest) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{19}
}

func (x *PatchManyFlagRequest) GetItems() []*PatchFlagRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

// PatchManyFlagResponse is the response of FlagService.PatchManyFlag.
type PatchManyFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the Flag records as stored.
	Items         []*Flag `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchManyFlagResponse) Reset() {
	*x = PatchManyFlagResponse{}
	mi := &file_cluster_flag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchManyFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchManyFlagResponse) ProtoMessage() {}

func (x *PatchManyFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchManyFlagResponse.ProtoReflect.Descriptor instead.
func (*PatchManyFlagResponse) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{20}
}

func (x *PatchManyFlagResponse) GetItems() []*Flag {
	if x != nil {
		return x.Items
	}
	return nil
}

// Filter is one filter of filters: field names the column by its query name, op is the operator, none for the equality every model answers, and values is its value, several for in and notin.
type ListFlagRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagRequest_Filter) Reset() {
	*x = ListFlagRequest_Filter{}
	mi := &file_cluster_flag_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagRequest_Filter) ProtoMessage() {}

func (x *ListFlagRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_flag_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListFlagRequest_Filter) Descriptor() ([]byte, []int) {
	return file_cluster_flag_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ListFlagRequest_Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListFlagRequest_Filter) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ListFlagRequest_Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_cluster_flag_proto protoreflect.FileDescriptor

const file_cluster_flag_proto_rawDesc = "" +
	"\n" +
	"\x12cluster/flag.proto\x12\acluster\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n" +
	"\x04Flag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12\x0e\n" +
	"\x02on\x18\f \x01(\bR\x02on\x12\x18\n" +
	"\apercent\x18\r \x01(\x03R\apercent\x12\x12\n" +
	"\x04note\x18\x0e \x01(\tR\x04note\"6\n" +
	"\x11CreateFlagRequest\x12!\n" +
	"\x04flag\x18\x01 \x01(\v2\r.cluster.FlagR\x04flag\"7\n" +
	"\x12CreateFlagResponse\x12!\n" +
	"\x04flag\x18\x01 \x01(\v2\r.cluster.FlagR\x04flag\"#\n" +
	"\x11DeleteFlagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteFlagResponse\"F\n" +
	"\x11UpdateFlagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04flag\x18\x02 \x01(\v2\r.cluster.FlagR\x04flag\"7\n" +
	"\x12UpdateFlagResponse\x12!\n" +
	"\x04flag\x18\x01 \x01(\v2\r.cluster.FlagR\x04flag\"\x82\x01\n" +
	"\x10PatchFlagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04flag\x18\x02 \x01(\v2\r.cluster.FlagR\x04flag\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"6\n" +
	"\x11PatchFlagResponse\x12!\n" +
	"\x04flag\x18\x01 \x01(\v2\r.cluster.FlagR\x04flag\"\xea\x02\n" +
	"\x0fListFlagRequest\x129\n" +
	"\afilters\x18\x01 \x03(\v2\x1f.cluster.ListFlagRequest.FilterR\afilters\x12\x17\n" +
	"\asort_by\x18\x02 \x03(\tR\x06sortBy\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12!\n" +
	"\fcursor_field\x18\x05 \x01(\tR\vcursorField\x12!\n" +
	"\fcursor_value\x18\x06 \x01(\tR\vcursorValue\x12\x1f\n" +
	"\vcursor_next\x18\a \x01(\bR\n" +
	"cursorNext\x12\x16\n" +
	"\x06expand\x18\b \x03(\tR\x06expand\x12\x14\n" +
	"\x05depth\x18\t \x01(\rR\x05depth\x1aF\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"M\n" +
	"\x10ListFlagResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.cluster.FlagR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"N\n" +
	"\x0eGetFlagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06expand\x18\x02 \x03(\tR\x06expand\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\rR\x05depth\"4\n" +
	"\x0fGetFlagResponse\x12!\n" +
	"\x04flag\x18\x01 \x01(\v2\r.cluster.FlagR\x04flag\"<\n" +
	"\x15CreateManyFlagRequest\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.cluster.FlagR\x05items\"=\n" +
	"\x16CreateManyFlagResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.cluster.FlagR\x05items\")\n" +
	"\x15DeleteManyFlagRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x18\n" +
	"\x16DeleteManyFlagResponse\"<\n" +
	"\x15UpdateManyFlagRequest\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.cluster.FlagR\x05items\"=\n" +
	"\x16UpdateManyFlagResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.cluster.FlagR\x05items\"G\n" +
	"\x14PatchManyFlagRequest\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.cluster.PatchFlagRequestR\x05items\"<\n" +
	"\x15PatchManyFlagResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.cluster.FlagR\x05items2\xee\x05\n" +
	"\vFlagService\x12E\n" +
	"\n" +
	"CreateFlag\x12\x1a.cluster.CreateFlagRequest\x1a\x1b.cluster.CreateFlagResponse\x12E\n" +
	"\n" +
	"DeleteFlag\x12\x1a.cluster.DeleteFlagRequest\x1a\x1b.cluster.DeleteFlagResponse\x12E\n" +
	"\n" +
	"UpdateFlag\x12\x1a.cluster.UpdateFlagRequest\x1a\x1b.cluster.UpdateFlagResponse\x12B\n" +
	"\tPatchFlag\x12\x19.cluster.PatchFlagRequest\x1a\x1a.cluster.PatchFlagResponse\x12?\n" +
	"\bListFlag\x12\x18.cluster.ListFlagRequest\x1a\x19.cluster.ListFlagResponse\x12<\n" +
	"\aGetFlag\x12\x17.cluster.GetFlagRequest\x1a\x18.cluster.GetFlagResponse\x12Q\n" +
	"\x0eCreateManyFlag\x12\x1e.cluster.CreateManyFlagRequest\x1a\x1f.cluster.CreateManyFlagResponse\x12Q\n" +
	"\x0eDeleteManyFlag\x12\x1e.cluster.DeleteManyFlagRequest\x1a\x1f.cluster.DeleteManyFlagResponse\x12Q\n" +
	"\x0eUpdateManyFlag\x12\x1e.cluster.UpdateManyFlagRequest\x1a\x1f.cluster.UpdateManyFlagResponse\x12N\n" +
	"\rPatchManyFlag\x12\x1d.cluster.PatchManyFlagRequest\x1a\x1e.cluster.PatchManyFlagResponseB\x0fZ\rcluster/pb;pbb\x06proto3"

var (
	file_cluster_flag_proto_rawDescOnce sync.Once
	file_cluster_flag_proto_rawDescData []byte
)

func file_cluster_flag_proto_rawDescGZIP() []byte {
	file_cluster_flag_proto_rawDescOnce.Do(func() {
		file_cluster_flag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_flag_proto_rawDesc), len(file_cluster_flag_proto_rawDesc)))
	})
	return file_cluster_flag_proto_rawDescData
}

var file_cluster_flag_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cluster_flag_proto_goTypes = []any{
	(*Flag)(nil),                   // 0: cluster.Flag
	(*CreateFlagRequest)(nil),      // 1: cluster.CreateFlagRequest
	(*CreateFlagResponse)(nil),     // 2: cluster.CreateFlagResponse
	(*DeleteFlagRequest)(nil),      // 3: cluster.DeleteFlagRequest
	(*DeleteFlagResponse)(nil),     // 4: cluster.DeleteFlagResponse
	(*UpdateFlagRequest)(nil),      // 5: cluster.UpdateFlagRequest
	(*UpdateFlagResponse)(nil),     // 6: cluster.UpdateFlagResponse
	(*PatchFlagRequest)(nil),       // 7: cluster.PatchFlagRequest
	(*PatchFlagResponse)(nil),      // 8: cluster.PatchFlagResponse
	(*ListFlagRequest)(nil),        // 9: cluster.ListFlagRequest
	(*ListFlagResponse)(nil),       // 10: cluster.ListFlagResponse
	(*GetFlagRequest)(nil),         // 11: cluster.GetFlagRequest
	(*GetFlagResponse)(nil),        // 12: cluster.GetFlagResponse
	(*CreateManyFlagRequest)(nil),  // 13: cluster.CreateManyFlagRequest
	(*CreateManyFlagResponse)(nil), // 14: cluster.CreateManyFlagResponse
	(*DeleteManyFlagRequest)(nil),  // 15: cluster.DeleteManyFlagRequest
	(*DeleteManyFlagResponse)(nil), // 16: cluster.DeleteManyFlagResponse
	(*UpdateManyFlagRequest)(nil),  // 17: cluster.UpdateManyFlagRequest
	(*UpdateManyFlagResponse)(nil), // 18: cluster.UpdateManyFlagResponse
	(*PatchManyFlagRequest)(nil),   // 19: cluster.PatchManyFlagRequest
	(*PatchManyFlagResponse)(nil),  // 20: cluster.PatchManyFlagResponse
	(*ListFlagRequest_Filter)(nil), // 21: cluster.ListFlagRequest.Filter
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),  // 23: google.protobuf.FieldMask
}
var file_cluster_flag_proto_depIdxs = []int32{
	22, // 0: cluster.Flag.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: cluster.Flag.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: cluster.CreateFlagRequest.flag:type_name -> cluster.Flag
	0,  // 3: cluster.CreateFlagResponse.flag:type_name -> cluster.Flag
	0,  // 4: cluster.UpdateFlagRequest.flag:type_name -> cluster.Flag
	0,  // 5: cluster.UpdateFlagResponse.flag:type_name -> cluster.Flag
	0,  // 6: cluster.PatchFlagRequest.flag:type_name -> cluster.Flag
	23, // 7: cluster.PatchFlagRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: cluster.PatchFlagResponse.flag:type_name -> cluster.Flag
	21, // 9: cluster.ListFlagRequest.filters:type_name -> cluster.ListFlagRequest.Filter
	0,  // 10: cluster.ListFlagResponse.items:type_name -> cluster.Flag
	0,  // 11: cluster.GetFlagResponse.flag:type_name -> cluster.Flag
	0,  // 12: cluster.CreateManyFlagRequest.items:type_name -> cluster.Flag
	0,  // 13: cluster.CreateManyFlagResponse.items:type_name -> cluster.Flag
	0,  // 14: cluster.UpdateManyFlagRequest.items:type_name -> cluster.Flag
	0,  // 15: cluster.UpdateManyFlagResponse.items:type_name -> cluster.Flag
	7,  // 16: cluster.PatchManyFlagRequest.items:type_name -> cluster.PatchFlagRequest
	0,  // 17: cluster.PatchManyFlagResponse.items:type_name -> cluster.Flag
	1,  // 18: cluster.FlagService.CreateFlag:input_type -> cluster.CreateFlagRequest
	3,  // 19: cluster.FlagService.DeleteFlag:input_type -> cluster.DeleteFlagRequest
	5,  // 20: cluster.FlagService.UpdateFlag:input_type -> cluster.UpdateFlagRequest
	7,  // 21: cluster.FlagService.PatchFlag:input_type -> cluster.PatchFlagRequest
	9,  // 22: cluster.FlagService.ListFlag:input_type -> cluster.ListFlagRequest
	11, // 23: cluster.FlagService.GetFlag:input_type -> cluster.GetFlagRequest
	13, // 24: cluster.FlagService.CreateManyFlag:input_type -> cluster.CreateManyFlagRequest
	15, // 25: cluster.FlagService.DeleteManyFlag:input_type -> cluster.DeleteManyFlagRequest
	17, // 26: cluster.FlagService.UpdateManyFlag:input_type -> cluster.UpdateManyFlagRequest
	19, // 27: cluster.FlagService.PatchManyFlag:input_type -> cluster.PatchManyFlagRequest
	2,  // 28: cluster.FlagService.CreateFlag:output_type -> cluster.CreateFlagResponse
	4,  // 29: cluster.FlagService.DeleteFlag:output_type -> cluster.DeleteFlagResponse
	6,  // 30: cluster.FlagService.UpdateFlag:output_type -> cluster.UpdateFlagResponse
	8,  // 31: cluster.FlagService.PatchFlag:output_type -> cluster.PatchFlagResponse
	10, // 32: cluster.FlagService.ListFlag:output_type -> cluster.ListFlagResponse
	12, // 33: cluster.FlagService.GetFlag:output_type -> cluster.GetFlagResponse
	14, // 34: cluster.FlagService.CreateManyFlag:output_type -> cluster.CreateManyFlagResponse
	16, // 35: cluster.FlagService.DeleteManyFlag:output_type -> cluster.DeleteManyFlagResponse
	18, // 36: cluster.FlagService.UpdateManyFlag:output_type -> cluster.UpdateManyFlagResponse
	20, // 37: cluster.FlagService.PatchManyFlag:output_type -> cluster.PatchManyFlagResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_cluster_flag_proto_init() }
func file_cluster_flag_proto_init() {
	if File_cluster_flag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_flag_proto_rawDesc), len(file_cluster_flag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_flag_proto_goTypes,
		DependencyIndexes: file_cluster_flag_proto_depIdxs,
		MessageInfos:      file_cluster_flag_proto_msgTypes,
	}.Build()
	File_cluster_flag_proto = out.File
	file_cluster_flag_proto_goTypes = nil
	file_cluster_flag_proto_depIdxs = nil
}
