// Code generated by gst; DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cluster/rebuild.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RebuildService_CreateRebuild_FullMethodName = "/cluster.RebuildService/CreateRebuild"
)

// RebuildServiceClient is the client API for RebuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RebuildService serves the actions of Rebuild over gRPC.
type RebuildServiceClient interface {
	// CreateRebuild is the Create action of Rebuild on /api/rebuilds.
	CreateRebuild(ctx context.Context, in *CreateRebuildRequest, opts ...grpc.CallOption) (*CreateRebuildResponse, error)
}

type rebuildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRebuildServiceClient(cc grpc.ClientConnInterface) RebuildServiceClient {
	return &rebuildServiceClient{cc}
}

func (c *rebuildServiceClient) CreateRebuild(ctx context.Context, in *CreateRebuildRequest, opts ...grpc.CallOption) (*CreateRebuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRebuildResponse)
	err := c.cc.Invoke(ctx, RebuildService_CreateRebuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RebuildServiceServer is the server API for RebuildService service.
// All implementations must embed UnimplementedRebuildServiceServer
// for forward compatibility.
//
// RebuildService serves the actions of Rebuild over gRPC.
type RebuildServiceServer interface {
	// CreateRebuild is the Create action of Rebuild on /api/rebuilds.
	CreateRebuild(context.Context, *CreateRebuildRequest) (*CreateRebuildResponse, error)
	mustEmbedUnimplementedRebuildServiceServer()
}

// UnimplementedRebuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRebuildServiceServer struct{}

func (UnimplementedRebuildServiceServer) CreateRebuild(context.Context, *CreateRebuildRequest) (*CreateRebuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRebuild not implemented")
}
func (UnimplementedRebuildServiceServer) mustEmbedUnimplementedRebuildServiceServer() {}
func (UnimplementedRebuildServiceServer) testEmbeddedByValue()                        {}

// UnsafeRebuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RebuildServiceServer will
// result in compilation errors.
type UnsafeRebuildServiceServer interface {
	mustEmbedUnimplementedRebuildServiceServer()
}

func RegisterRebuildServiceServer(s grpc.ServiceRegistrar, srv RebuildServiceServer) {
	// If the following call panics, it indicates UnimplementedRebuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RebuildService_ServiceDesc, srv)
}

func _RebuildService_CreateRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RebuildServiceServer).CreateRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RebuildService_CreateRebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RebuildServiceServer).CreateRebuild(ctx, req.(*CreateRebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RebuildService_ServiceDesc is the grpc.ServiceDesc for RebuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RebuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.RebuildService",
	HandlerType: (*RebuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRebuild",
			Handler:    _RebuildService_CreateRebuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster/rebuild.proto",
}
