// Code generated by gst; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cluster/run.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Run is one piece of work a replica did: a cron round or a run under the
// lock. It is written as the work starts — CreatedAt is the start — and marked
// ended once the work runs to its end, both in a transaction on the work's
// context: a run cut short, by its lease lost or its process stopping, keeps
// no end. Listing the runs across the replicas shows who did what and how
// often, and whether two runs of one job or one lock ever overlapped.
type Run struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the record, assigned when it is created.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The username of the user who created the record.
	CreatedBy string `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The username of the user who last updated the record.
	UpdatedBy string `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// When the record was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the record was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// "cron" or "lock"
	Kind string `protobuf:"bytes,11,opt,name=kind,proto3" json:"kind,omitempty"`
	// the job or the lock
	Name string `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	// the replica that ran it, see helper.Replica
	Replica string `protobuf:"bytes,13,opt,name=replica,proto3" json:"replica,omitempty"`
	// when the work ran to its end; nil while it runs or once it was cut short
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_cluster_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_cluster_run_proto_rawDescGZIP(), []int{0}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Run) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Run) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Run) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Run) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

func (x *Run) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

// ListRunRequest is the request of RunService.ListRun.
type ListRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filters is the filters to apply, each one field[op]=value of the HTTP query.
	Filters []*ListRunRequest_Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	// sort_by is the orderings, as the _sort_by query parameter names them.
	SortBy []string `protobuf:"bytes,2,rep,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// page is the page to list, as the _page query parameter.
	Page uint32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// size is the page size, as the _size query parameter, 20 when unset and at most 100.
	Size uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// cursor_field is the cursor column, as the _cursor_field query parameter.
	CursorField string `protobuf:"bytes,5,opt,name=cursor_field,json=cursorField,proto3" json:"cursor_field,omitempty"`
	// cursor_value is the cursor position, as the _cursor_value query parameter.
	CursorValue string `protobuf:"bytes,6,opt,name=cursor_value,json=cursorValue,proto3" json:"cursor_value,omitempty"`
	// cursor_next is whether to list past the cursor, as the _cursor_next query parameter.
	CursorNext bool `protobuf:"varint,7,opt,name=cursor_next,json=cursorNext,proto3" json:"cursor_next,omitempty"`
	// expand is the associations to expand, as the _expand query parameter names them.
	Expand []string `protobuf:"bytes,8,rep,name=expand,proto3" json:"expand,omitempty"`
	// depth is the depth of the expansion, as the _depth query parameter.
	Depth         uint32 `protobuf:"varint,9,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunRequest) Reset() {
	*x = ListRunRequest{}
	mi := &file_cluster_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunRequest) ProtoMessage() {}

func (x *ListRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunRequest.ProtoReflect.Descriptor instead.
func (*ListRunRequest) Descriptor() ([]byte, []int) {
	return file_cluster_run_proto_rawDescGZIP(), []int{1}
}

func (x *ListRunRequest) GetFilters() []*ListRunRequest_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListRunRequest) GetSortBy() []string {
	if x != nil {
		return x.SortBy
	}
	return nil
}

func (x *ListRunRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRunRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListRunRequest) GetCursorField() string {
	if x != nil {
		return x.CursorField
	}
	return ""
}

func (x *ListRunRequest) GetCursorValue() string {
	if x != nil {
		return x.CursorValue
	}
	return ""
}

func (x *ListRunRequest) GetCursorNext() bool {
	if x != nil {
		return x.CursorNext
	}
	return false
}

func (x *ListRunRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *ListRunRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// ListRunResponse is the response of RunService.ListRun.
type ListRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the Run records of the page.
	Items []*Run `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// total is the number of records the filters match, 0 under cursor pagination.
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunResponse) Reset() {
	*x = ListRunResponse{}
	mi := &file_cluster_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunResponse) ProtoMessage() {}

func (x *ListRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunResponse.ProtoReflect.Descriptor instead.
func (*ListRunResponse) Descriptor() ([]byte, []int) {
	return file_cluster_run_proto_rawDescGZIP(), []int{2}
}

func (x *ListRunResponse) GetItems() []*Run {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRunResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Filter is one filter of filters: field names the column by its query name, op is the operator, none for the equality every model answers, and values is its value, several for in and notin.
type ListRunRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunRequest_Filter) Reset() {
	*x = ListRunRequest_Filter{}
	mi := &file_cluster_run_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunRequest_Filter) ProtoMessage() {}

func (x *ListRunRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_run_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListRunRequest_Filter) Descriptor() ([]byte, []int) {
	return file_cluster_run_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListRunRequest_Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListRunRequest_Filter) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ListRunRequest_Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_cluster_run_proto protoreflect.FileDescriptor

const file_cluster_run_proto_rawDesc = "" +
	"\n" +
	"\x11cluster/run.proto\x12\acluster\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x02\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04kind\x18\v \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x12\x18\n" +
	"\areplica\x18\r \x01(\tR\areplica\x125\n" +
	"\bended_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\xe8\x02\n" +
	"\x0eListRunRequest\x128\n" +
	"\afilters\x18\x01 \x03(\v2\x1e.cluster.ListRunRequest.FilterR\afilters\x12\x17\n" +
	"\asort_by\x18\x02 \x03(\tR\x06sortBy\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12!\n" +
	"\fcursor_field\x18\x05 \x01(\tR\vcursorField\x12!\n" +
	"\fcursor_value\x18\x06 \x01(\tR\vcursorValue\x12\x1f\n" +
	"\vcursor_next\x18\a \x01(\bR\n" +
	"cursorNext\x12\x16\n" +
	"\x06expand\x18\b \x03(\tR\x06expand\x12\x14\n" +
	"\x05depth\x18\t \x01(\rR\x05depth\x1aF\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"K\n" +
	"\x0fListRunResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.cluster.RunR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2J\n" +
	"\n" +
	"RunService\x12<\n" +
	"\aListRun\x12\x17.cluster.ListRunRequest\x1a\x18.cluster.ListRunResponseB\x0fZ\rcluster/pb;pbb\x06proto3"

var (
	file_cluster_run_proto_rawDescOnce sync.Once
	file_cluster_run_proto_rawDescData []byte
)

func file_cluster_run_proto_rawDescGZIP() []byte {
	file_cluster_run_proto_rawDescOnce.Do(func() {
		file_cluster_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_run_proto_rawDesc), len(file_cluster_run_proto_rawDesc)))
	})
	return file_cluster_run_proto_rawDescData
}

var file_cluster_run_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cluster_run_proto_goTypes = []any{
	(*Run)(nil),                   // 0: cluster.Run
	(*ListRunRequest)(nil),        // 1: cluster.ListRunRequest
	(*ListRunResponse)(nil),       // 2: cluster.ListRunResponse
	(*ListRunRequest_Filter)(nil), // 3: cluster.ListRunRequest.Filter
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_cluster_run_proto_depIdxs = []int32{
	4, // 0: cluster.Run.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: cluster.Run.updated_at:type_name -> google.protobuf.Timestamp
	4, // 2: cluster.Run.ended_at:type_name -> google.protobuf.Timestamp
	3, // 3: cluster.ListRunRequest.filters:type_name -> cluster.ListRunRequest.Filter
	0, // 4: cluster.ListRunResponse.items:type_name -> cluster.Run
	1, // 5: cluster.RunService.ListRun:input_type -> cluster.ListRunRequest
	2, // 6: cluster.RunService.ListRun:output_type -> cluster.ListRunResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cluster_run_proto_init() }
func file_cluster_run_proto_init() {
	if File_cluster_run_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_run_proto_rawDesc), len(file_cluster_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_run_proto_goTypes,
		DependencyIndexes: file_cluster_run_proto_depIdxs,
		MessageInfos:      file_cluster_run_proto_msgTypes,
	}.Build()
	File_cluster_run_proto = out.File
	file_cluster_run_proto_goTypes = nil
	file_cluster_run_proto_depIdxs = nil
}
