// Code generated by gst; DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cluster/step_down.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StepDownService_CreateStepDown_FullMethodName = "/cluster.StepDownService/CreateStepDown"
)

// StepDownServiceClient is the client API for StepDownService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StepDownService serves the actions of StepDown over gRPC.
type StepDownServiceClient interface {
	// CreateStepDown is the Create action of StepDown on /api/step-downs.
	CreateStepDown(ctx context.Context, in *CreateStepDownRequest, opts ...grpc.CallOption) (*CreateStepDownResponse, error)
}

type stepDownServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStepDownServiceClient(cc grpc.ClientConnInterface) StepDownServiceClient {
	return &stepDownServiceClient{cc}
}

func (c *stepDownServiceClient) CreateStepDown(ctx context.Context, in *CreateStepDownRequest, opts ...grpc.CallOption) (*CreateStepDownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStepDownResponse)
	err := c.cc.Invoke(ctx, StepDownService_CreateStepDown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepDownServiceServer is the server API for StepDownService service.
// All implementations must embed UnimplementedStepDownServiceServer
// for forward compatibility.
//
// StepDownService serves the actions of StepDown over gRPC.
type StepDownServiceServer interface {
	// CreateStepDown is the Create action of StepDown on /api/step-downs.
	CreateStepDown(context.Context, *CreateStepDownRequest) (*CreateStepDownResponse, error)
	mustEmbedUnimplementedStepDownServiceServer()
}

// UnimplementedStepDownServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStepDownServiceServer struct{}

func (UnimplementedStepDownServiceServer) CreateStepDown(context.Context, *CreateStepDownRequest) (*CreateStepDownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStepDown not implemented")
}
func (UnimplementedStepDownServiceServer) mustEmbedUnimplementedStepDownServiceServer() {}
func (UnimplementedStepDownServiceServer) testEmbeddedByValue()                         {}

// UnsafeStepDownServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepDownServiceServer will
// result in compilation errors.
type UnsafeStepDownServiceServer interface {
	mustEmbedUnimplementedStepDownServiceServer()
}

func RegisterStepDownServiceServer(s grpc.ServiceRegistrar, srv StepDownServiceServer) {
	// If the following call panics, it indicates UnimplementedStepDownServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StepDownService_ServiceDesc, srv)
}

func _StepDownService_CreateStepDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStepDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepDownServiceServer).CreateStepDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepDownService_CreateStepDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepDownServiceServer).CreateStepDown(ctx, req.(*CreateStepDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepDownService_ServiceDesc is the grpc.ServiceDesc for StepDownService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepDownService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.StepDownService",
	HandlerType: (*StepDownServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStepDown",
			Handler:    _StepDownService_CreateStepDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster/step_down.proto",
}
