// Code generated by gst; DO NOT EDIT.

package service

import (
	"demo/service/archive/document"
	"demo/service/archive/document/seal"
	"demo/service/auth/login"
	"demo/service/notice"
	"demo/service/ping"
	"demo/service/record"
	"demo/service/record/item"
	"demo/service/tool/entry"
	"demo/service/trace_probe"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/service"
)

func init() {
	service.Register[*seal.Creator](consts.PHASE_CREATE, "archive/documents/seal")
	service.Register[*document.Creator](consts.PHASE_CREATE, "archive/documents")
	service.Register[*document.Updater](consts.PHASE_UPDATE, "archive/documents/:document")
	service.Register[*document.Lister](consts.PHASE_LIST, "archive/documents")
	service.Register[*login.Login](consts.PHASE_LIST, "auth/login")
	service.Register[*notice.Streamer](consts.PHASE_SSE, "notices")
	service.Register[*ping.Lister](consts.PHASE_LIST, "pings")
	service.Register[*item.Creator](consts.PHASE_CREATE, "records/:rec/items")
	service.Register[*item.Lister](consts.PHASE_LIST, "records/:rec/items")
	service.Register[*item.ManyDeleter](consts.PHASE_DELETE_MANY, "items/batch")
	service.Register[*record.Creator](consts.PHASE_CREATE, "records")
	service.Register[*record.Deleter](consts.PHASE_DELETE, "records/:rec")
	service.Register[*record.Patcher](consts.PHASE_PATCH, "records/:rec")
	service.Register[*record.Lister](consts.PHASE_LIST, "records")
	service.Register[*entry.Merge](consts.PHASE_CREATE, "entries/merge")
	service.Register[*traceprobe.Creator](consts.PHASE_CREATE, "trace-probes")
	service.Register[*traceprobe.Deleter](consts.PHASE_DELETE, "trace-probes/:trace_probe")
	service.Register[*traceprobe.Updater](consts.PHASE_UPDATE, "trace-probes/:trace_probe")
	service.Register[*traceprobe.Patcher](consts.PHASE_PATCH, "trace-probes/:trace_probe")
	service.Register[*traceprobe.Lister](consts.PHASE_LIST, "trace-probes")
	service.Register[*traceprobe.Getter](consts.PHASE_GET, "trace-probes/:trace_probe")
}
