// Code generated by gst; DO NOT EDIT.

package service

import (
	"demo/service/archive/document"
	"demo/service/archive/document/attachment"
	"demo/service/board/feed"
	"demo/service/board/note"
	"demo/service/notice"
	"demo/service/ping"
	"demo/service/record"
	"demo/service/record/item"
	"demo/service/tool"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/service"
)

func init() {
	service.Register[*attachment.Creator](consts.Create, "/api/archive/documents/:document/attachment")
	service.Register[*attachment.Getter](consts.Get, "/api/archive/documents/:document/attachment")
	service.Register[*document.ListByBox](consts.List, "/api/archive/boxes/:box_id/documents")
	service.Register[*document.Importer](consts.Import, "/api/archive/documents/import")
	service.Register[*document.Exporter](consts.Export, "/api/archive/documents/export")
	service.Register[*feed.Chat](consts.Stream, "/api/board/feeds/chat")
	service.Register[*feed.Upload](consts.Stream, "/api/board/feeds/upload")
	service.Register[*feed.Watch](consts.Stream, "/api/board/feeds/watch")
	service.Register[*note.Creator](consts.Create, "/api/board/notes")
	service.Register[*note.Publish](consts.Create, "/api/board/notes/:id/publish")
	service.Register[*notice.Streamer](consts.SSE, "/api/notices")
	service.Register[*ping.Lister](consts.List, "/api/pings")
	service.Register[*item.Creator](consts.Create, "/api/records/:record/items")
	service.Register[*item.Lister](consts.List, "/api/records/:record/items")
	service.Register[*record.Creator](consts.Create, "/api/records")
	service.Register[*record.Lister](consts.List, "/api/records")
	service.Register[*record.Search](consts.List, "/api/records/search")
	service.Register[*record.Summary](consts.List, "/api/records/summary")
	service.Register[*tool.Merge](consts.Create, "/api/entries/merge")
}
