// Code generated by gst; DO NOT EDIT.
package service

import (
	"demo/service/auth/login"
	"demo/service/common/search"
	"demo/service/config/file"
	"demo/service/config/file/encrypt"
	"demo/service/notice"
	"demo/service/ping"
	"demo/service/record"
	"demo/service/record/item"
	"demo/service/trace_probe"

	"github.com/hydroan/gst/service"
	"github.com/hydroan/gst/types/consts"
)

func init() {
	service.Register[*login.Login](consts.PHASE_LIST, "auth/login")
	service.Register[*search.Dedup](consts.PHASE_CREATE, "search-sources/dedup")
	service.Register[*encrypt.Creator](consts.PHASE_CREATE, "config/files/encrypt")
	service.Register[*file.Creator](consts.PHASE_CREATE, "config/files")
	service.Register[*file.Updater](consts.PHASE_UPDATE, "config/files/:file")
	service.Register[*file.Lister](consts.PHASE_LIST, "config/files")
	service.Register[*notice.Streamer](consts.PHASE_SSE, "notices")
	service.Register[*ping.Lister](consts.PHASE_LIST, "pings")
	service.Register[*item.Creator](consts.PHASE_CREATE, "records/:rec/items")
	service.Register[*item.Lister](consts.PHASE_LIST, "records/:rec/items")
	service.Register[*item.ManyDeleter](consts.PHASE_DELETE_MANY, "items/batch")
	service.Register[*record.Creator](consts.PHASE_CREATE, "records")
	service.Register[*record.Deleter](consts.PHASE_DELETE, "records/:rec")
	service.Register[*record.Patcher](consts.PHASE_PATCH, "records/:rec")
	service.Register[*record.Lister](consts.PHASE_LIST, "records")
	service.Register[*traceprobe.Creator](consts.PHASE_CREATE, "trace-probes")
	service.Register[*traceprobe.Deleter](consts.PHASE_DELETE, "trace-probes/:trace_probe")
	service.Register[*traceprobe.Updater](consts.PHASE_UPDATE, "trace-probes/:trace_probe")
	service.Register[*traceprobe.Patcher](consts.PHASE_PATCH, "trace-probes/:trace_probe")
	service.Register[*traceprobe.Lister](consts.PHASE_LIST, "trace-probes")
	service.Register[*traceprobe.Getter](consts.PHASE_GET, "trace-probes/:trace_probe")
}
