// Code generated by gst; DO NOT EDIT.
package service

import (
	"demo/service/auth/login"
	"demo/service/common/search"
	"demo/service/config/file"
	"demo/service/config/file/encrypt"
	"demo/service/conversation"
	"demo/service/conversation/message"
	"demo/service/ping"

	"github.com/hydroan/gst/service"
	"github.com/hydroan/gst/types/consts"
)

func init() {
	service.Register[*login.Login](consts.PHASE_LIST)
	service.Register[*search.Dedup](consts.PHASE_CREATE)
	service.Register[*encrypt.Creator](consts.PHASE_CREATE)
	service.Register[*file.Creator](consts.PHASE_CREATE)
	service.Register[*file.Updater](consts.PHASE_UPDATE)
	service.Register[*file.Lister](consts.PHASE_LIST)
	service.Register[*message.Creator](consts.PHASE_CREATE)
	service.Register[*message.Lister](consts.PHASE_LIST)
	service.Register[*message.ManyDeleter](consts.PHASE_DELETE_MANY)
	service.Register[*conversation.Creator](consts.PHASE_CREATE)
	service.Register[*conversation.Deleter](consts.PHASE_DELETE)
	service.Register[*conversation.Patcher](consts.PHASE_PATCH)
	service.Register[*conversation.Lister](consts.PHASE_LIST)
	service.Register[*ping.Lister](consts.PHASE_LIST)
}
