// Code generated by gst; DO NOT EDIT.

package board

import (
	"demo/model/board"

	"github.com/hydroan/gst/grpc"
)

// feedService serves the rpcs of the FeedService service through the actions
// of Feed: every handler decodes its request message into what the action's
// call takes, runs the call and encodes what it answers into the response
// message.
type feedService struct {
	UnimplementedFeedServiceServer
}

// The calls of the actions of Feed, one per rpc of FeedService, built once
// at package initialization.
var (
	chatFeed   = grpc.BidiStreamCall[*board.Feed, *board.FeedEvent, *board.FeedEvent]("/api/board/feeds/chat")
	uploadFeed = grpc.ClientStreamCall[*board.Feed, *board.FeedEvent, *board.FeedUploadRsp]("/api/board/feeds/upload")
	watchFeed  = grpc.ServerStreamCall[*board.Feed, *board.FeedWatchReq, *board.FeedEvent]("/api/board/feeds/watch")
)

// ChatFeed serves the Stream action of Feed declared on board/feeds/chat,
// served over gRPC alone.
func (feedService) ChatFeed(srv FeedService_ChatFeedServer) error {
	return chatFeed(srv.Context(), nil, func() (*board.FeedEvent, error) {
		msg, recvErr := srv.Recv()
		if recvErr != nil {
			return nil, recvErr
		}
		return FeedEventFromProto(msg.GetPayload())
	}, func(rsp *board.FeedEvent) error {
		return srv.Send(&ChatFeedResponse{Result: FeedEventToProto(rsp)})
	})
}

// UploadFeed serves the Stream action of Feed declared on
// board/feeds/upload, served over gRPC alone.
func (feedService) UploadFeed(srv FeedService_UploadFeedServer) error {
	result, err := uploadFeed(srv.Context(), nil, func() (*board.FeedEvent, error) {
		msg, recvErr := srv.Recv()
		if recvErr != nil {
			return nil, recvErr
		}
		return FeedEventFromProto(msg.GetPayload())
	})
	if err != nil {
		return err
	}
	return srv.SendAndClose(&UploadFeedResponse{Result: FeedUploadRspToProto(result)})
}

// WatchFeed serves the Stream action of Feed declared on board/feeds/watch,
// served over gRPC alone.
func (feedService) WatchFeed(req *WatchFeedRequest, srv FeedService_WatchFeedServer) error {
	payload, err := FeedWatchReqFromProto(req.GetPayload())
	if err != nil {
		return err
	}
	return watchFeed(srv.Context(), nil, payload, func(rsp *board.FeedEvent) error {
		return srv.Send(&WatchFeedResponse{Result: FeedEventToProto(rsp)})
	})
}

// FeedEventToProto encodes FeedEvent values into their message, nil into
// nil.
func FeedEventToProto(m *board.FeedEvent) *FeedEvent {
	if m == nil {
		return nil
	}
	p := new(FeedEvent)
	p.Seq = m.Seq
	p.Body = m.Body
	return p
}

// FeedEventFromProto decodes FeedEvent messages into values, nil into nil.
func FeedEventFromProto(p *FeedEvent) (*board.FeedEvent, error) {
	if p == nil {
		return nil, nil
	}
	m := new(board.FeedEvent)
	m.Seq = p.GetSeq()
	m.Body = p.GetBody()
	return m, nil
}

// FeedUploadRspToProto encodes FeedUploadRsp values into their message, nil
// into nil.
func FeedUploadRspToProto(m *board.FeedUploadRsp) *FeedUploadRsp {
	if m == nil {
		return nil
	}
	p := new(FeedUploadRsp)
	p.Accepted = m.Accepted
	return p
}

// FeedUploadRspFromProto decodes FeedUploadRsp messages into values, nil
// into nil.
func FeedUploadRspFromProto(p *FeedUploadRsp) (*board.FeedUploadRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(board.FeedUploadRsp)
	m.Accepted = p.GetAccepted()
	return m, nil
}

// FeedWatchReqToProto encodes FeedWatchReq values into their message, nil
// into nil.
func FeedWatchReqToProto(m *board.FeedWatchReq) *FeedWatchReq {
	if m == nil {
		return nil
	}
	p := new(FeedWatchReq)
	p.Topic = m.Topic
	return p
}

// FeedWatchReqFromProto decodes FeedWatchReq messages into values, nil into
// nil.
func FeedWatchReqFromProto(p *FeedWatchReq) (*board.FeedWatchReq, error) {
	if p == nil {
		return nil, nil
	}
	m := new(board.FeedWatchReq)
	m.Topic = p.GetTopic()
	return m, nil
}
