// Code generated by gst; DO NOT EDIT.

package board

import (
	"context"
	"demo/model/board"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/grpc"
)

// noteService serves the rpcs of the NoteService service through the actions
// of Note: every handler decodes its request message into what the action's
// call takes, runs the call and encodes what it answers into the response
// message.
type noteService struct {
	UnimplementedNoteServiceServer
}

// The calls of the actions of Note, one per rpc of NoteService, built once
// at package initialization.
var (
	createNote  = grpc.CreateCall[*board.Note]("/api/board/notes")
	deleteNote  = grpc.DeleteCall[*board.Note]("/api/board/notes/:id")
	updateNote  = grpc.UpdateCall[*board.Note]("/api/board/notes/:id")
	patchNote   = grpc.PatchCall[*board.Note]("/api/board/notes/:id")
	listNote    = grpc.ListCall[*board.Note]("/api/board/notes")
	getNote     = grpc.GetCall[*board.Note]("/api/board/notes/:id")
	publishNote = grpc.ServiceCall[*board.Note, *board.NotePublishReq, *board.NotePublishRsp](consts.Create, "/api/board/notes/:id/publish")
)

// CreateNote serves the Create action of Note on /api/board/notes.
func (noteService) CreateNote(ctx context.Context, req *CreateNoteRequest) (*CreateNoteResponse, error) {
	in, err := NoteFromProto(req.GetNote())
	if err != nil {
		return nil, err
	}
	m, err := createNote(ctx, nil, in)
	if err != nil {
		return nil, err
	}
	return &CreateNoteResponse{Note: NoteToProto(m)}, nil
}

// DeleteNote serves the Delete action of Note on /api/board/notes/:id.
func (noteService) DeleteNote(ctx context.Context, req *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	if err := deleteNote(ctx, map[string]string{"id": req.GetId()}, req.GetId()); err != nil {
		return nil, err
	}
	return &DeleteNoteResponse{}, nil
}

// UpdateNote serves the Update action of Note on /api/board/notes/:id.
func (noteService) UpdateNote(ctx context.Context, req *UpdateNoteRequest) (*UpdateNoteResponse, error) {
	in, err := NoteFromProto(req.GetNote())
	if err != nil {
		return nil, err
	}
	m, err := updateNote(ctx, map[string]string{"id": req.GetId()}, req.GetId(), in)
	if err != nil {
		return nil, err
	}
	return &UpdateNoteResponse{Note: NoteToProto(m)}, nil
}

// PatchNote serves the Patch action of Note on /api/board/notes/:id.
func (noteService) PatchNote(ctx context.Context, req *PatchNoteRequest) (*PatchNoteResponse, error) {
	in, err := NoteFromProto(req.GetNote())
	if err != nil {
		return nil, err
	}
	m, err := patchNote(ctx, map[string]string{"id": req.GetId()}, req.GetId(), in, req.GetUpdateMask().GetPaths())
	if err != nil {
		return nil, err
	}
	return &PatchNoteResponse{Note: NoteToProto(m)}, nil
}

// ListNote serves the List action of Note on /api/board/notes.
func (noteService) ListNote(ctx context.Context, req *ListNoteRequest) (*ListNoteResponse, error) {
	models, total, err := listNote(ctx, nil, grpc.Query{
		Filters: grpc.Filters(req.GetFilters()),
	})
	if err != nil {
		return nil, err
	}
	items := make([]*Note, len(models))
	for i, m := range models {
		items[i] = NoteToProto(m)
	}
	return &ListNoteResponse{Items: items, Total: int64(total)}, nil
}

// GetNote serves the Get action of Note on /api/board/notes/:id.
func (noteService) GetNote(ctx context.Context, req *GetNoteRequest) (*GetNoteResponse, error) {
	m, err := getNote(ctx, map[string]string{"id": req.GetId()}, req.GetId(), grpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()})
	if err != nil {
		return nil, err
	}
	return &GetNoteResponse{Note: NoteToProto(m)}, nil
}

// PublishNote serves the Create action of Note on
// /api/board/notes/:id/publish.
func (noteService) PublishNote(ctx context.Context, req *PublishNoteRequest) (*PublishNoteResponse, error) {
	payload, err := NotePublishReqFromProto(req.GetPayload())
	if err != nil {
		return nil, err
	}
	result, err := publishNote(ctx, map[string]string{"id": req.GetId()}, grpc.Query{}, payload)
	if err != nil {
		return nil, err
	}
	return &PublishNoteResponse{Result: NotePublishRspToProto(result)}, nil
}

// NoteToProto encodes Note values into their message, nil into nil.
func NoteToProto(m *board.Note) *Note {
	if m == nil {
		return nil
	}
	p := new(Note)
	p.Id = m.ID
	p.CreatedBy = m.CreatedBy
	p.UpdatedBy = m.UpdatedBy
	p.CreatedAt = grpc.Timestamp(m.CreatedAt)
	p.UpdatedAt = grpc.Timestamp(m.UpdatedAt)
	p.Title = m.Title
	p.Body = m.Body
	p.Published = m.Published
	if m.PublishedAt != nil {
		p.PublishedAt = grpc.Timestamp(*m.PublishedAt)
	}
	return p
}

// NoteFromProto decodes Note messages into values, nil into nil.
func NoteFromProto(p *Note) (*board.Note, error) {
	if p == nil {
		return nil, nil
	}
	m := new(board.Note)
	m.ID = p.GetId()
	m.CreatedBy = p.GetCreatedBy()
	m.UpdatedBy = p.GetUpdatedBy()
	m.CreatedAt = grpc.Time(p.GetCreatedAt())
	m.UpdatedAt = grpc.Time(p.GetUpdatedAt())
	m.Title = p.GetTitle()
	m.Body = p.GetBody()
	m.Published = p.GetPublished()
	if p.GetPublishedAt() != nil {
		x := grpc.Time(p.GetPublishedAt())
		m.PublishedAt = &x
	}
	return m, nil
}

// NotePublishReqToProto encodes NotePublishReq values into their message,
// nil into nil.
func NotePublishReqToProto(m *board.NotePublishReq) *NotePublishReq {
	if m == nil {
		return nil
	}
	p := new(NotePublishReq)
	p.Channel = m.Channel
	return p
}

// NotePublishReqFromProto decodes NotePublishReq messages into values, nil
// into nil.
func NotePublishReqFromProto(p *NotePublishReq) (*board.NotePublishReq, error) {
	if p == nil {
		return nil, nil
	}
	m := new(board.NotePublishReq)
	m.Channel = p.GetChannel()
	return m, nil
}

// NotePublishRspToProto encodes NotePublishRsp values into their message,
// nil into nil.
func NotePublishRspToProto(m *board.NotePublishRsp) *NotePublishRsp {
	if m == nil {
		return nil
	}
	p := new(NotePublishRsp)
	p.Id = m.ID
	p.Channel = m.Channel
	p.PublishedAt = grpc.Timestamp(m.PublishedAt)
	return p
}

// NotePublishRspFromProto decodes NotePublishRsp messages into values, nil
// into nil.
func NotePublishRspFromProto(p *NotePublishRsp) (*board.NotePublishRsp, error) {
	if p == nil {
		return nil, nil
	}
	m := new(board.NotePublishRsp)
	m.ID = p.GetId()
	m.Channel = p.GetChannel()
	m.PublishedAt = grpc.Time(p.GetPublishedAt())
	return m, nil
}
