// Code generated by gst; DO NOT EDIT.
// source: model/archive/document.go

package archive

import (
	"github.com/hydroan/gst"
	"gorm.io/gorm"
)

// DocumentCols are the typed column references of Document.
var DocumentCols = struct {
	BoxID     gst.Column[string]
	Checksum  gst.Column[string]
	Content   gst.Column[string]
	CreatedAt gst.TimeColumn
	CreatedBy gst.Column[string]
	DeletedAt gst.Column[gorm.DeletedAt]
	Format    gst.Column[DocumentFormat]
	ID        gst.Column[string]
	Name      gst.Column[string]
	Size      gst.NumericColumn[int]
	UpdatedAt gst.TimeColumn
	UpdatedBy gst.Column[string]
}{
	BoxID:     gst.NewColumn[*Document, string]("box_id"),
	Checksum:  gst.NewColumn[*Document, string]("checksum"),
	Content:   gst.NewColumn[*Document, string]("content"),
	CreatedAt: gst.NewTimeColumn[*Document]("created_at"),
	CreatedBy: gst.NewColumn[*Document, string]("created_by"),
	DeletedAt: gst.NewColumn[*Document, gorm.DeletedAt]("deleted_at"),
	Format:    gst.NewColumn[*Document, DocumentFormat]("format"),
	ID:        gst.NewColumn[*Document, string]("id"),
	Name:      gst.NewColumn[*Document, string]("name"),
	Size:      gst.NewNumericColumn[*Document, int]("size"),
	UpdatedAt: gst.NewTimeColumn[*Document]("updated_at"),
	UpdatedBy: gst.NewColumn[*Document, string]("updated_by"),
}
