// Code generated by gst; DO NOT EDIT.

package modelregistry

import "github.com/hydroan/gst/apidoc"

func init() {
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "AutoBase", apidoc.StructDoc{
		Comment: "AutoBase implements types.Model for database-backed resources that use an\nauto-increment integer primary key instead of Base's UUIDv7 string key.\nA narrow monotonic primary key keeps the clustered index append-only and\nkeeps every secondary index entry small, which suits high-growth tables.\n\nKey behavior differences from Base:\n  - SetID never generates an ID; the database assigns one on insert.\n  - GetID returns \"\" while the ID is unset (0) so framework emptiness\n    checks such as seeding and not-found detection keep working.\n\nCaveats:\n  - Seed records passed to model.Register must set an explicit ID or rely\n    on a unique index; idempotent seeding depends on conflicting keys.\n  - Updating a record whose ID is unset fails with database.ErrIDRequired;\n    use database.Upsert for insert-or-update semantics.\n\ncreated_at/updated_at follow the same NOT NULL, no-database-default\ncontract as Base: every writer provides both explicitly, in UTC.\n\nThe uuid columns take a size instead of an explicit char type for the same\nreason as Base: postgres blank-pads char values on read. The note belongs\nhere rather than above the field, for the reason Base's comment spells out.",
		Fields: map[string]string{
			"CreatedAt": "Timestamp when the record was created",
			"CreatedBy": "UUIDv7 user ID who created the record",
			"DeletedAt": "Timestamp when the record was deleted",
			"ID":        "Auto-increment identifier assigned by the database",
			"UpdatedAt": "Timestamp when the record was last updated",
			"UpdatedBy": "UUIDv7 user ID who last updated the record",
		},
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "Base", apidoc.StructDoc{
		Comment: "Base implements types.Model for database-backed resources.\nCustom models can override these default methods when needed.\n\nUsually, there are some gorm tags that may be of interest to you.\ngorm:\"unique\"\ngorm:\"foreignKey:ParentID;constraint:-\"\ngorm:\"foreignKey:ParentID;references:ID;constraint:-\"\n\nAssociations are declared so queries can preload them, not to create physical\nforeign keys, so they carry constraint:- and leave referential integrity to\nthe model hooks.\n\nTimestamps: created_at/updated_at are NOT NULL and carry no database\ndefault. The framework always provides both, in UTC via dbruntime.NowUTC\n(Create/Upsert force them, Update refreshes updated_at). A writer that\nbypasses the framework must set both columns itself, in UTC; omitting them\nfails fast under strict SQL mode instead of silently storing NULL, which\nwould break created_at ordering, cursor pagination, and time-range\nfiltering. A database default is ruled out on purpose: CURRENT_TIMESTAMP\nfills in the session-timezone wall clock, which silently diverges from the\nframework's UTC time base. deleted_at stays nullable: NULL marks the live\nrow under soft deletion.\n\nThe uuid columns take a size instead of an explicit char type: postgres\nblank-pads char values, so an id shorter than 36 would come back with\ntrailing spaces there. varchar stores every id verbatim on all dialects.\nThe note belongs here rather than above the field: doc comment extraction\nprefers a field's doc comment over its trailing one, so an implementation\nnote placed above a field becomes that field's API-facing description.",
		Fields: map[string]string{
			"CreatedAt": "Timestamp when the record was created",
			"CreatedBy": "UUIDv7 user ID who created the record",
			"DeletedAt": "Timestamp when the record was deleted",
			"ID":        "UUIDv7 identifier for the record",
			"UpdatedAt": "Timestamp when the record was last updated",
			"UpdatedBy": "UUIDv7 user ID who last updated the record",
		},
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "Cursor", apidoc.StructDoc{
		Comment: "Cursor declares cursor-pagination query parameters for List actions.\n\nCursor owns cursor position and direction only. Ordering for cursor pagination\nis derived from CursorField and CursorNext, so SortBy intentionally remains\noutside this struct to avoid multiple competing order sources. Embedding\nCursor also lets the client tune the batch size via _size (the field lives\nin Pagination; the controller reads it from the URL directly), while _page\nstays rejected: offset paging conflicts with cursor semantics.",
		Fields: map[string]string{
			"CursorField": "CursorField names the single field the cursor orders by.",
			"CursorNext":  "CursorNext chooses the cursor direction; false requests the previous page.",
			"CursorValue": "CursorValue is the current cursor token; it must parse as the cursor column's Go type.",
		},
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "Empty", apidoc.StructDoc{
		Comment: "Empty is a no-op types.Model implementation for non-persistent actions.\n\nKey characteristics:\n  - Structs with an anonymous model.Empty field are never migrated to the database\n  - All interface methods return zero values or no-op implementations\n  - IsEmpty reports true for structs containing only model.Empty markers\n  - IsVirtual reports true for any struct embedding model.Empty, however many\n    other fields it declares\n  - Service hooks are bypassed when AreTypesEqual returns false for Empty types\n  - Commonly used for request/response DTOs that don't require persistence\n\nUsage example:\n\n\ttype LoginRequest struct {\n\t    model.Empty\n\t    Username string `json:\"username\"`\n\t    Password string `json:\"password\"`\n\t}",
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "Index", apidoc.StructDoc{
		Comment: "Index declares one custom index on the model's table.\n\nCustom indexes complement gorm struct tag indexes instead of replacing\nthem: they cover index shapes struct tags cannot express, such as indexes\non columns promoted from the embedded Base or AutoBase. Regular\nbusiness-column indexes should keep using gorm struct tags.",
		Fields: map[string]string{
			"Fields": "Go struct field names; slice order is the index column order",
			"Unique": "Unique makes the index a unique index",
		},
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "IndexPlan", apidoc.StructDoc{
		Comment: "IndexPlan is one resolved custom index: a validated declaration bound to a\nconcrete table with a framework-generated name and database column names.\nThe bootstrap executor and the migration schema dumper both consume\nIndexPlan, so the executed DDL and the desired-schema DDL always stay\nliterally identical.",
		Fields: map[string]string{
			"Columns": "database column names in index order",
			"Name":    "framework-generated index name",
			"Table":   "table the index belongs to",
			"Unique":  "whether the index is unique",
		},
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "Pagination", apidoc.StructDoc{
		Comment: "Pagination declares offset-pagination query parameters for List actions.\n\nEmbedding Pagination only enables _page and _size. It does not imply\nsorting, fuzzy matching, cursor pagination, or any other List query\ncontrols.\n\nLike every framework-owned query parameter, _page and _size live in the\n\"_\" prefix namespace, so bare names such as page and size stay available\nas business filter fields on embedding models.\n\nNeither parameter can be used to retrieve a whole table. A size the client\ndoes not set, or sets to zero or less, becomes the default page size; a size\nabove the cap is clamped to it rather than refused, which is what keeps a\nclient asking for everything from being served everything. Bulk retrieval is\nthe Export action's job, and it is the only one that answers unbounded.",
		Fields: map[string]string{
			"Page": "Page is the one-based page number; non-positive values use the first page.",
			"Size": "Size is the page size; non-positive values use the default page size and oversized ones clamp to the cap.",
		},
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "Query", apidoc.StructDoc{
		Comment: "Query declares framework-owned HTTP query parameters for list-style\ncontroller actions.\n\nEmbedding Query in a model is an explicit opt-in: the model can still expose\nits own fields as query filters through query tags, while Query enables the\nstandard List controls, including offset pagination, cursor pagination,\nsorting, expansion, and field-level operator filters (\"field[op]=value\",\ncovering substring matching via like/notlike and time or numeric ranges via\nthe comparison operators). Query already embeds Pagination and Cursor, so\nmodels that embed Query must not embed those structs again.\n\nQuery covers every framework List control; there is no second opt-in to add.\n\nEvery field is ignored by JSON and GORM. The query tags are intentionally\nkept here because the List controller decodes URL query parameters into the\nrequest model before applying those controls. Database query construction must\nskip this struct so these controller-only values never become WHERE clauses.",
		Fields: map[string]string{
			"Depth":  "Depth controls recursive expansion depth for expandable slice fields.",
			"Expand": "Expand lists model associations to preload, separated by commas.",
			"SortBy": "SortBy is the comma-separated ORDER BY expression; the List controller validates its columns and turns it into typed orders.",
		},
	})
	apidoc.Register("github.com/hydroan/gst/internal/modelregistry", "writeHookOverrides", apidoc.StructDoc{
		Comment: "writeHookOverrides records which write-hook pairs a model type overrides.",
	})
}
