package modelregistry

import (
	"reflect"
	"runtime"
	"sync"

	"github.com/hydroan/gst/types/consts"
)

// Hook override detection.
//
// Every model carries the ten lifecycle hooks of types.Model through the
// embedded framework base, whose implementations are no-ops. Knowing which of
// them a model overrides lets the database layer drop work that exists only
// for the hooks' sake. A write wrapped in a transaction protects the atomicity
// of the hooks around the statement — but when neither hook of the pair is
// overridden there is nothing to keep atomic, and a single-statement write can
// run on the statement's own atomicity instead of paying a BEGIN/COMMIT pair.
// A hook wrapped in a span records where its time went — but a hook that is
// not overridden is the base no-op, and a span timing nothing only adds noise
// to the trace.
//
// Whether a hook is overridden is read off the compiled binary: a method
// declared on a type reports the source file it was written in, while every
// promotion through an embedded field — whether it forwards to the framework
// no-op or to a real implementation on an intermediate type — is a wrapper
// the compiler stamps with "<autogenerated>". A wrapper therefore says
// nothing by itself; the walk descends the embedding tree breadth-first,
// mirroring Go's shallowest-wins promotion rule, until it reaches the type
// that declares the method. Only a declaration owned by a framework base
// (Base, AutoBase, Empty) counts as not overridden. Anything unresolvable
// counts as overridden, which only keeps a transaction or a span that was not
// strictly needed.

// autogeneratedFile is the source position the compiler stamps on the method
// wrappers it synthesizes for embedded-field promotion.
const autogeneratedFile = "<autogenerated>"

// frameworkHookBases are the embeddable framework types whose hooks are the
// canonical no-ops. A hook whose declaration resolves to one of them is not
// an override. Keyed by pointer type because the hooks use pointer receivers.
var frameworkHookBases = map[reflect.Type]struct{}{
	reflect.TypeFor[*Base]():     {},
	reflect.TypeFor[*AutoBase](): {},
	reflect.TypeFor[*Empty]():    {},
}

// Positions of the lifecycle hooks in hookPhases, hookMethodNames and
// hookOverrides, in the order types.Model declares them.
const (
	hookCreateBefore = iota
	hookCreateAfter
	hookDeleteBefore
	hookDeleteAfter
	hookUpdateBefore
	hookUpdateAfter
	hookListBefore
	hookListAfter
	hookGetBefore
	hookGetAfter
	hookCount
)

// hookPhases lists the phases of the lifecycle hooks of types.Model by
// position. It is the set the detection tracks; a phase outside it is not a
// model hook, and OverridesHook fails closed on it.
var hookPhases = [hookCount]consts.Phase{
	hookCreateBefore: consts.PHASE_CREATE_BEFORE,
	hookCreateAfter:  consts.PHASE_CREATE_AFTER,
	hookDeleteBefore: consts.PHASE_DELETE_BEFORE,
	hookDeleteAfter:  consts.PHASE_DELETE_AFTER,
	hookUpdateBefore: consts.PHASE_UPDATE_BEFORE,
	hookUpdateAfter:  consts.PHASE_UPDATE_AFTER,
	hookListBefore:   consts.PHASE_LIST_BEFORE,
	hookListAfter:    consts.PHASE_LIST_AFTER,
	hookGetBefore:    consts.PHASE_GET_BEFORE,
	hookGetAfter:     consts.PHASE_GET_AFTER,
}

// hookMethodNames holds the Go method name of each hook phase, derived once
// at initialization so the detection never repeats the case conversion.
var hookMethodNames = func() (names [hookCount]string) {
	for i, phase := range hookPhases {
		names[i] = phase.MethodName()
	}
	return names
}()

// hookIndex returns the position of phase in hookPhases, or false when the
// phase is not a model hook.
func hookIndex(phase consts.Phase) (int, bool) {
	for i, tracked := range hookPhases {
		if tracked == phase {
			return i, true
		}
	}
	return 0, false
}

// hookOverrides records, by position in hookPhases, which hooks a model type
// overrides.
type hookOverrides [hookCount]bool

// allHooksOverridden is the fail-closed answer for a value whose type cannot
// be inspected.
var allHooksOverridden = func() hookOverrides {
	var all hookOverrides
	for i := range all {
		all[i] = true
	}
	return all
}()

// hookOverridesCache memoizes the detection per model type; the method set of
// a type is fixed for the life of the binary.
var hookOverridesCache sync.Map

// OverridesCreateHooks reports whether the model overrides CreateBefore or
// CreateAfter beyond the framework base's no-op implementations.
func OverridesCreateHooks(m any) bool {
	overrides := hookOverridesOf(m)
	return overrides[hookCreateBefore] || overrides[hookCreateAfter]
}

// OverridesUpdateHooks reports whether the model overrides UpdateBefore or
// UpdateAfter beyond the framework base's no-op implementations.
func OverridesUpdateHooks(m any) bool {
	overrides := hookOverridesOf(m)
	return overrides[hookUpdateBefore] || overrides[hookUpdateAfter]
}

// OverridesDeleteHooks reports whether the model overrides DeleteBefore or
// DeleteAfter beyond the framework base's no-op implementations.
func OverridesDeleteHooks(m any) bool {
	overrides := hookOverridesOf(m)
	return overrides[hookDeleteBefore] || overrides[hookDeleteAfter]
}

// OverridesHook reports whether the model overrides the hook that phase names
// beyond the framework base's no-op implementation. Only the hook phases of
// types.Model are tracked; any other phase reports true, so a caller gating
// work on the answer keeps that work rather than skipping it for a hook the
// detection does not know.
func OverridesHook(m any, phase consts.Phase) bool {
	i, ok := hookIndex(phase)
	if !ok {
		return true
	}
	return hookOverridesOf(m)[i]
}

func hookOverridesOf(m any) hookOverrides {
	typ := reflect.TypeOf(m)
	if typ == nil {
		// No type resolves no methods; fail closed.
		return allHooksOverridden
	}
	if cached, ok := hookOverridesCache.Load(typ); ok {
		return cached.(hookOverrides) //nolint:errcheck
	}

	var overrides hookOverrides
	for i, name := range hookMethodNames {
		overrides[i] = overridesMethod(typ, name)
	}
	hookOverridesCache.Store(typ, overrides)
	return overrides
}

// overridesMethod reports whether the named method of typ resolves to a
// declaration other than a framework base no-op. A method the type does not
// have runs nothing and so overrides nothing; a method declared on typ itself
// is an override unless typ is a framework base; a promoted wrapper defers to
// the declaring type found by walking the embedding tree.
func overridesMethod(typ reflect.Type, name string) bool {
	method, ok := typ.MethodByName(name)
	if !ok {
		return false
	}
	if !isAutogeneratedMethod(method) {
		_, isBase := frameworkHookBases[typ]
		return !isBase
	}
	return promotedDeclarerOverrides(typ, name)
}

// promotedDeclarerOverrides resolves which embedded type declares the
// promoted method and reports whether that declarer is anything but a
// framework base. The walk is breadth-first because Go promotes the
// shallowest declaration; a declaration found at one depth shadows anything
// deeper. Ambiguity and dead ends cannot happen for a method the compiler
// did promote, so both fail closed as overridden.
func promotedDeclarerOverrides(typ reflect.Type, name string) bool {
	structTyp := typ
	if structTyp.Kind() == reflect.Pointer {
		structTyp = structTyp.Elem()
	}
	if structTyp.Kind() != reflect.Struct {
		return true
	}

	depth := []reflect.Type{structTyp}
	for len(depth) > 0 {
		var deeper []reflect.Type
		var declarers []reflect.Type
		for _, st := range depth {
			for field := range st.Fields() {
				if !field.Anonymous {
					continue
				}
				fieldTyp := field.Type
				if fieldTyp.Kind() == reflect.Pointer {
					fieldTyp = fieldTyp.Elem()
				}
				if fieldTyp.Kind() != reflect.Struct {
					continue
				}
				ptrTyp := reflect.PointerTo(fieldTyp)
				method, ok := ptrTyp.MethodByName(name)
				if !ok {
					continue
				}
				if isAutogeneratedMethod(method) {
					deeper = append(deeper, fieldTyp)
					continue
				}
				declarers = append(declarers, ptrTyp)
			}
		}
		if len(declarers) == 1 {
			_, isBase := frameworkHookBases[declarers[0]]
			return !isBase
		}
		if len(declarers) > 1 {
			return true
		}
		depth = deeper
	}
	return true
}

// isAutogeneratedMethod reports whether the method is a compiler-synthesized
// promotion wrapper rather than a declaration written in source. A method
// whose function cannot be resolved reports false, so the caller treats it as
// a declaration and fails closed through the framework-base check.
func isAutogeneratedMethod(method reflect.Method) bool {
	fn := runtime.FuncForPC(method.Func.Pointer())
	if fn == nil {
		return false
	}
	file, _ := fn.FileLine(fn.Entry())
	return file == autogeneratedFile
}
