package modelregistry

import (
	"fmt"
	"hash/fnv"
	"reflect"
	"strings"

	"github.com/cockroachdb/errors"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

// indexNameMaxLen is the identifier length limit shared by the supported
// databases (MySQL enforces 64); generated index names never exceed it.
const indexNameMaxLen = 64

// Index declares one custom index on the model's table.
//
// Custom indexes complement gorm struct tag indexes instead of replacing
// them: they cover index shapes struct tags cannot express, such as indexes
// on columns promoted from the embedded Base or AutoBase. Regular
// business-column indexes should keep using gorm struct tags.
type Index struct {
	Fields []string // Go struct field names; slice order is the index column order
	Unique bool     // Unique makes the index a unique index
}

// Indexer is the optional capability interface for models that declare
// custom indexes beyond gorm struct tags.
//
// Indexes must be a pure declaration: it is invoked on zero-value model
// instances and must not depend on model data. Index names are always
// generated by the framework; declarations that conflict with struct tag
// indexes fail fast at bootstrap and inside gg migrate.
type Indexer interface {
	Indexes() []Index
}

// IndexPlan is one resolved custom index: a validated declaration bound to a
// concrete table with a framework-generated name and database column names.
// The bootstrap executor and the migration schema dumper both consume
// IndexPlan, so the executed DDL and the desired-schema DDL always stay
// literally identical.
type IndexPlan struct {
	Name    string   // framework-generated index name
	Table   string   // table the index belongs to
	Columns []string // database column names in index order
	Unique  bool     // whether the index is unique
}

// CreateSQL renders the CREATE INDEX statement for the plan using the
// dialector's identifier quoting. Every consumer must render statements
// through this single method so DDL text never diverges between the
// database and the migration schema.
func (p IndexPlan) CreateSQL(dialector gorm.Dialector) string {
	var b strings.Builder
	b.WriteString("CREATE ")
	if p.Unique {
		b.WriteString("UNIQUE ")
	}
	b.WriteString("INDEX ")
	dialector.QuoteTo(&b, p.Name)
	b.WriteString(" ON ")
	dialector.QuoteTo(&b, p.Table)
	b.WriteString(" (")
	for i, col := range p.Columns {
		if i > 0 {
			b.WriteString(",")
		}
		dialector.QuoteTo(&b, col)
	}
	b.WriteString(")")
	return b.String()
}

// ParseIndexPlans resolves and validates the custom index declarations of
// model against its gorm schema parsed through db. It returns nil plans when
// the model does not implement Indexer or declares no indexes.
//
// tableName overrides the schema-derived table name; callers should pass the
// model's GetTableName result so names and DDL target the real table.
func ParseIndexPlans(db *gorm.DB, model any, tableName string) ([]IndexPlan, error) {
	indexer, ok := asIndexer(model)
	if !ok {
		return nil, nil
	}
	decls := indexer.Indexes()
	if len(decls) == 0 {
		return nil, nil
	}

	stmt := &gorm.Statement{DB: db}
	if err := stmt.Parse(model); err != nil {
		return nil, errors.Wrapf(err, "failed to parse schema for custom indexes of %T", model)
	}
	sch := stmt.Schema
	if len(tableName) == 0 {
		tableName = sch.Table
	}
	return buildIndexPlans(sch, tableName, decls)
}

// buildIndexPlans validates declarations and resolves them into plans:
// every field must exist, no column repeats inside one index, no two
// declarations share the same column sequence, and no declaration may
// duplicate a struct tag index.
func buildIndexPlans(sch *schema.Schema, tableName string, decls []Index) ([]IndexPlan, error) {
	plans := make([]IndexPlan, 0, len(decls))
	declared := make(map[string]struct{}, len(decls))
	for _, decl := range decls {
		if len(decl.Fields) == 0 {
			return nil, errors.Newf("model %s: custom index must declare at least one field", sch.Name)
		}
		columns := make([]string, 0, len(decl.Fields))
		seenColumns := make(map[string]struct{}, len(decl.Fields))
		for _, name := range decl.Fields {
			field := sch.LookUpField(name)
			if field == nil {
				return nil, errors.Newf("model %s: custom index references unknown field %q", sch.Name, name)
			}
			if _, ok := seenColumns[field.DBName]; ok {
				return nil, errors.Newf("model %s: custom index repeats column %q", sch.Name, field.DBName)
			}
			seenColumns[field.DBName] = struct{}{}
			columns = append(columns, field.DBName)
		}
		key := strings.Join(columns, ",")
		if _, ok := declared[key]; ok {
			return nil, errors.Newf("model %s: duplicate custom index on columns (%s)", sch.Name, key)
		}
		declared[key] = struct{}{}
		plans = append(plans, IndexPlan{
			Name:    indexName(tableName, columns, decl.Unique),
			Table:   tableName,
			Columns: columns,
			Unique:  decl.Unique,
		})
	}
	if err := checkTagIndexConflicts(sch, plans); err != nil {
		return nil, err
	}
	return plans, nil
}

// checkTagIndexConflicts rejects declarations that duplicate a struct tag
// index by name or by column sequence. Duplicated declarations drift apart
// over time, so they fail fast instead of being merged silently.
func checkTagIndexConflicts(sch *schema.Schema, plans []IndexPlan) error {
	for _, tagIndex := range sch.ParseIndexes() {
		columns := make([]string, 0, len(tagIndex.Fields))
		for _, opt := range tagIndex.Fields {
			columns = append(columns, opt.DBName)
		}
		key := strings.Join(columns, ",")
		for _, plan := range plans {
			if plan.Name == tagIndex.Name {
				return errors.Newf("model %s: custom index name %q conflicts with struct tag index", sch.Name, plan.Name)
			}
			if strings.Join(plan.Columns, ",") == key {
				return errors.Newf("model %s: custom index on columns (%s) duplicates struct tag index %q", sch.Name, key, tagIndex.Name)
			}
		}
	}
	return nil
}

// indexName generates the deterministic framework index name: an idx_ (or
// uniq_ for unique) prefix, the table name, and the column names. Names
// beyond the identifier limit keep a readable prefix and end with an fnv-32a
// hash so truncation stays deterministic across runs.
func indexName(table string, columns []string, unique bool) string {
	prefix := "idx_"
	if unique {
		prefix = "uniq_"
	}
	name := prefix + table + "_" + strings.Join(columns, "_")
	if len(name) <= indexNameMaxLen {
		return name
	}
	h := fnv.New32a()
	_, _ = h.Write([]byte(name))
	return fmt.Sprintf("%s_%08x", name[:indexNameMaxLen-9], h.Sum32())
}

// asIndexer reports the Indexer implementation of model, tolerating both
// value and pointer callers because registry snapshots and schema dump
// inputs mix the two forms. Value models are probed through a zero-value
// pointer, which is safe because Indexes must be a pure declaration.
func asIndexer(model any) (Indexer, bool) {
	if indexer, ok := model.(Indexer); ok {
		return indexer, true
	}
	typ := reflect.TypeOf(model)
	if typ == nil || typ.Kind() == reflect.Pointer {
		return nil, false
	}
	indexer, ok := reflect.New(typ).Interface().(Indexer)
	return indexer, ok
}
