package modelregistry

import (
	"reflect"
	"runtime"
	"sync"
)

// Write-hook override detection.
//
// Every model carries the six write hooks through the embedded framework
// base, whose implementations are no-ops. A write wrapped in a transaction
// protects the atomicity of the hooks around the statement — but when none of
// the relevant hooks is overridden there is nothing to keep atomic, and the
// database layer can let a single-statement write run on the statement's own
// atomicity instead of paying a BEGIN/COMMIT pair for it.
//
// Whether a hook is overridden is read off the compiled binary: a method
// declared on a type reports the source file it was written in, while every
// promotion through an embedded field — whether it forwards to the framework
// no-op or to a real implementation on an intermediate type — is a wrapper
// the compiler stamps with "<autogenerated>". A wrapper therefore says
// nothing by itself; the walk descends the embedding tree breadth-first,
// mirroring Go's shallowest-wins promotion rule, until it reaches the type
// that declares the method. Only a declaration owned by a framework base
// (Base, AutoBase, Empty) counts as not overridden. Anything unresolvable
// counts as overridden, which only keeps a transaction that was not strictly
// needed.

// autogeneratedFile is the source position the compiler stamps on the method
// wrappers it synthesizes for embedded-field promotion.
const autogeneratedFile = "<autogenerated>"

// frameworkHookBases are the embeddable framework types whose write hooks are
// the canonical no-ops. A hook whose declaration resolves to one of them is
// not an override. Keyed by pointer type because the hooks use pointer
// receivers.
var frameworkHookBases = map[reflect.Type]struct{}{
	reflect.TypeFor[*Base]():     {},
	reflect.TypeFor[*AutoBase](): {},
	reflect.TypeFor[*Empty]():    {},
}

// writeHookOverrides records which write-hook pairs a model type overrides.
type writeHookOverrides struct {
	create bool
	update bool
	del    bool
}

// writeHookOverridesCache memoizes the detection per model type; the method
// set of a type is fixed for the life of the binary.
var writeHookOverridesCache sync.Map

// OverridesCreateHooks reports whether the model overrides CreateBefore or
// CreateAfter beyond the framework base's no-op implementations.
func OverridesCreateHooks(m any) bool { return writeHookOverridesOf(m).create }

// OverridesUpdateHooks reports whether the model overrides UpdateBefore or
// UpdateAfter beyond the framework base's no-op implementations.
func OverridesUpdateHooks(m any) bool { return writeHookOverridesOf(m).update }

// OverridesDeleteHooks reports whether the model overrides DeleteBefore or
// DeleteAfter beyond the framework base's no-op implementations.
func OverridesDeleteHooks(m any) bool { return writeHookOverridesOf(m).del }

func writeHookOverridesOf(m any) writeHookOverrides {
	typ := reflect.TypeOf(m)
	if typ == nil {
		// No type resolves no methods; fail closed.
		return writeHookOverrides{create: true, update: true, del: true}
	}
	if cached, ok := writeHookOverridesCache.Load(typ); ok {
		return cached.(writeHookOverrides) //nolint:errcheck
	}

	overrides := writeHookOverrides{
		create: overridesMethod(typ, "CreateBefore") || overridesMethod(typ, "CreateAfter"),
		update: overridesMethod(typ, "UpdateBefore") || overridesMethod(typ, "UpdateAfter"),
		del:    overridesMethod(typ, "DeleteBefore") || overridesMethod(typ, "DeleteAfter"),
	}
	writeHookOverridesCache.Store(typ, overrides)
	return overrides
}

// overridesMethod reports whether the named method of typ resolves to a
// declaration other than a framework base no-op. A method the type does not
// have runs nothing and so overrides nothing; a method declared on typ itself
// is an override unless typ is a framework base; a promoted wrapper defers to
// the declaring type found by walking the embedding tree.
func overridesMethod(typ reflect.Type, name string) bool {
	method, ok := typ.MethodByName(name)
	if !ok {
		return false
	}
	if !isAutogeneratedMethod(method) {
		_, isBase := frameworkHookBases[typ]
		return !isBase
	}
	return promotedDeclarerOverrides(typ, name)
}

// promotedDeclarerOverrides resolves which embedded type declares the
// promoted method and reports whether that declarer is anything but a
// framework base. The walk is breadth-first because Go promotes the
// shallowest declaration; a declaration found at one depth shadows anything
// deeper. Ambiguity and dead ends cannot happen for a method the compiler
// did promote, so both fail closed as overridden.
func promotedDeclarerOverrides(typ reflect.Type, name string) bool {
	structTyp := typ
	if structTyp.Kind() == reflect.Pointer {
		structTyp = structTyp.Elem()
	}
	if structTyp.Kind() != reflect.Struct {
		return true
	}

	depth := []reflect.Type{structTyp}
	for len(depth) > 0 {
		var deeper []reflect.Type
		var declarers []reflect.Type
		for _, st := range depth {
			for field := range st.Fields() {
				if !field.Anonymous {
					continue
				}
				fieldTyp := field.Type
				if fieldTyp.Kind() == reflect.Pointer {
					fieldTyp = fieldTyp.Elem()
				}
				if fieldTyp.Kind() != reflect.Struct {
					continue
				}
				ptrTyp := reflect.PointerTo(fieldTyp)
				method, ok := ptrTyp.MethodByName(name)
				if !ok {
					continue
				}
				if isAutogeneratedMethod(method) {
					deeper = append(deeper, fieldTyp)
					continue
				}
				declarers = append(declarers, ptrTyp)
			}
		}
		if len(declarers) == 1 {
			_, isBase := frameworkHookBases[declarers[0]]
			return !isBase
		}
		if len(declarers) > 1 {
			return true
		}
		depth = deeper
	}
	return true
}

// isAutogeneratedMethod reports whether the method is a compiler-synthesized
// promotion wrapper rather than a declaration written in source. A method
// whose function cannot be resolved reports false, so the caller treats it as
// a declaration and fails closed through the framework-base check.
func isAutogeneratedMethod(method reflect.Method) bool {
	fn := runtime.FuncForPC(method.Func.Pointer())
	if fn == nil {
		return false
	}
	file, _ := fn.FileLine(fn.Entry())
	return file == autogeneratedFile
}
