// Code generated by gst; DO NOT EDIT.
package router

import (
	"demo/model"
	"demo/model/auth"
	"demo/model/common"
	"demo/model/config"
	"demo/model/config/file"
	"demo/model/conversation"

	"github.com/hydroan/gst/router"
	"github.com/hydroan/gst/types/consts"

	"github.com/hydroan/gst/types"
)

func Init() error {
	router.Register[*auth.Login, *auth.Login, *auth.LoginRsp](router.Pub(), "auth/login", &types.ControllerConfig[*auth.Login]{}, consts.List)
	router.Register[*common.Search, *common.SearchDedupReq, *common.SearchDedupRsp](router.Auth(), "search-sources/dedup", &types.ControllerConfig[*common.Search]{}, consts.Create)
	router.Register[*file.Encrypt, *file.EncryptReq, *file.EncryptRsp](router.Auth(), "config/files/encrypt", &types.ControllerConfig[*file.Encrypt]{}, consts.Create)
	router.Register[*config.File, *config.File, *config.File](router.Auth(), "config/files", &types.ControllerConfig[*config.File]{}, consts.Create)
	router.Register[*config.File, *config.File, *config.File](router.Auth(), "config/files/:file", &types.ControllerConfig[*config.File]{ParamName: "file"}, consts.Update)
	router.Register[*config.File, *config.File, *config.File](router.Auth(), "config/files/:file", &types.ControllerConfig[*config.File]{ParamName: "file"}, consts.Patch)
	router.Register[*config.File, *config.File, *config.File](router.Auth(), "config/files", &types.ControllerConfig[*config.File]{}, consts.List)
	router.Register[*config.File, *config.File, *config.File](router.Auth(), "config/files/:file", &types.ControllerConfig[*config.File]{ParamName: "file"}, consts.Get)
	router.Register[*config.File, *config.File, *config.File](router.Auth(), "config/namespaces/:namespace/files", &types.ControllerConfig[*config.File]{}, consts.List)
	router.Register[*conversation.Message, *conversation.Message, *conversation.Message](router.Auth(), "conversations/:conv/messages", &types.ControllerConfig[*conversation.Message]{}, consts.Create)
	router.Register[*conversation.Message, *conversation.Message, *conversation.Message](router.Auth(), "conversations/:conv/messages/:id", &types.ControllerConfig[*conversation.Message]{ParamName: "id"}, consts.Patch)
	router.Register[*conversation.Message, *conversation.Message, *conversation.Message](router.Auth(), "conversations/:conv/messages", &types.ControllerConfig[*conversation.Message]{}, consts.List)
	router.Register[*conversation.Message, *conversation.Message, *conversation.Message](router.Auth(), "conversations/:conv/messages/:id", &types.ControllerConfig[*conversation.Message]{ParamName: "id"}, consts.Get)
	router.Register[*conversation.Message, *conversation.Message, *conversation.Message](router.Auth(), "messages/batch", &types.ControllerConfig[*conversation.Message]{}, consts.DeleteMany)
	router.Register[*model.Conversation, *model.Conversation, *model.Conversation](router.Auth(), "conversations", &types.ControllerConfig[*model.Conversation]{}, consts.Create)
	router.Register[*model.Conversation, *model.Conversation, *model.Conversation](router.Auth(), "conversations/:conv", &types.ControllerConfig[*model.Conversation]{ParamName: "conv"}, consts.Delete)
	router.Register[*model.Conversation, *model.Conversation, *model.Conversation](router.Auth(), "conversations/:conv", &types.ControllerConfig[*model.Conversation]{ParamName: "conv"}, consts.Patch)
	router.Register[*model.Conversation, *model.Conversation, *model.Conversation](router.Auth(), "conversations", &types.ControllerConfig[*model.Conversation]{}, consts.List)
	router.Register[*model.Conversation, *model.Conversation, *model.Conversation](router.Auth(), "conversations/:conv", &types.ControllerConfig[*model.Conversation]{ParamName: "conv"}, consts.Get)
	router.Register[*model.Ping, *model.Ping, *model.PingRsp](router.Pub(), "pings", &types.ControllerConfig[*model.Ping]{}, consts.List)
	router.Register[*model.TraceProbe, *model.TraceProbe, *model.TraceProbe](router.Auth(), "trace-probes", &types.ControllerConfig[*model.TraceProbe]{}, consts.Create)
	router.Register[*model.TraceProbe, *model.TraceProbe, *model.TraceProbe](router.Auth(), "trace-probes/:trace_probe", &types.ControllerConfig[*model.TraceProbe]{ParamName: "trace_probe"}, consts.Delete)
	router.Register[*model.TraceProbe, *model.TraceProbe, *model.TraceProbe](router.Auth(), "trace-probes/:trace_probe", &types.ControllerConfig[*model.TraceProbe]{ParamName: "trace_probe"}, consts.Update)
	router.Register[*model.TraceProbe, *model.TraceProbe, *model.TraceProbe](router.Auth(), "trace-probes/:trace_probe", &types.ControllerConfig[*model.TraceProbe]{ParamName: "trace_probe"}, consts.Patch)
	router.Register[*model.TraceProbe, *model.TraceProbe, *model.TraceProbe](router.Auth(), "trace-probes", &types.ControllerConfig[*model.TraceProbe]{}, consts.List)
	router.Register[*model.TraceProbe, *model.TraceProbe, *model.TraceProbe](router.Auth(), "trace-probes/:trace_probe", &types.ControllerConfig[*model.TraceProbe]{ParamName: "trace_probe"}, consts.Get)
	return nil
}
