package openapigen

import (
	"encoding/json"
	"net/http"
	"os"
	"reflect"
	"strings"
	"sync"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/hydroan/gst/config"
	"github.com/hydroan/gst/types"
	"github.com/hydroan/gst/types/consts"
)

var (
	doc = &openapi3.T{
		OpenAPI: "3.0.0",
		Paths:   openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas:       openapi3.Schemas{},
			RequestBodies: openapi3.RequestBodies{},
			Responses:     openapi3.ResponseBodies{},
		},
	}
	// docMutex protects concurrent access to the global doc variable
	docMutex sync.RWMutex
)

func Write(filename string) error {
	docMutex.RLock()
	data, err := json.MarshalIndent(doc, "", "  ")
	docMutex.RUnlock()
	if err != nil {
		return err
	}
	return os.WriteFile(filename, data, 0o600)
}

func Set[M types.Model, REQ types.Request, RSP types.Response](path string, verb ...consts.HTTPVerb) {
	getOrCreate := func(p string) *openapi3.PathItem {
		if v := doc.Paths.Value(p); v != nil {
			return v
		}
		newPathItem := &openapi3.PathItem{}
		doc.Paths.Set(p, newPathItem)
		return newPathItem
	}

	// pathid := path + "/:id"
	path = convertColonParamsToBraces(path)
	pathid := path
	pathbatch := path
	pathipt := path
	pathexpt := path

	docMutex.Lock()
	pathItem := getOrCreate(path)
	pathidItem := getOrCreate(pathid)
	pathbatchItem := getOrCreate(pathbatch)
	pathiptItem := getOrCreate(pathipt)
	pathexptItem := getOrCreate(pathexpt)
	docMutex.Unlock()

	for _, verb := range buildVerbs(verb...) {
		switch verb {
		case consts.Create:
			setCreate[M, REQ, RSP](path, pathItem)
		case consts.Delete:
			setDelete[M, REQ, RSP](pathid, pathidItem)
		case consts.Update:
			setUpdate[M, REQ, RSP](pathid, pathidItem)
		case consts.Patch:
			setPatch[M, REQ, RSP](pathid, pathidItem)
		case consts.List:
			setList[M, REQ, RSP](path, pathItem)
		case consts.Get:
			setGet[M, REQ, RSP](pathid, pathidItem)
		case consts.Import:
			setImport[M, REQ, RSP](pathipt, pathiptItem)
		case consts.Export:
			setExport[M, REQ, RSP](pathexpt, pathexptItem)
		case consts.CreateMany:
			setCreateMany[M, REQ, RSP](pathbatch, pathbatchItem)
		case consts.DeleteMany:
			setDeleteMany[M, REQ, RSP](pathbatch, pathbatchItem)
		case consts.UpdateMany:
			setUpdateMany[M, REQ, RSP](pathbatch, pathbatchItem)
		case consts.PatchMany:
			setPatchMany[M, REQ, RSP](pathbatch, pathbatchItem)
		}
	}

	docMutex.Lock()
	doc.Paths.Set(path, pathItem)
	doc.Paths.Set(pathid, pathidItem)
	doc.Paths.Set(pathbatch, pathbatchItem)
	doc.Paths.Set(pathipt, pathiptItem)
	doc.Paths.Set(pathexpt, pathexptItem)
	docMutex.Unlock()
}

// func Set[M types.Model](path string, verb ...consts.HTTPVerb) {
// 	// doc := &openapi3.T{
// 	// 	OpenAPI: "3.0.0",
// 	// 	Info: &openapi3.Info{
// 	// 		Title:       "User API",
// 	// 		Description: "API for managing users",
// 	// 		Version:     "1.0.0",
// 	// 	},
// 	// 	Paths: openapi3.NewPaths(),
// 	// }
//
// 	// base scheme
//
// 	// TODO: whether to compare and select
// 	// openapi3.NewStringSchema().WithRequired()
//
// 	schema := openapi3.NewObjectSchema().
// 		WithProperty("id", openapi3.NewStringSchema()).
// 		WithProperty("created_at", openapi3.NewStringSchema()).
// 		WithProperty("updated_at", openapi3.NewStringSchema()).
// 		WithProperty("deleted_at", openapi3.NewStringSchema()).
// 		WithProperty("created_by", openapi3.NewStringSchema()).
// 		WithProperty("updated_by", openapi3.NewStringSchema())
// 	_ = schema
//
// 	// userSchema := openapi3.NewObjectSchema().
// 	// 	WithProperty("id", openapi3.NewIntegerSchema()).
// 	// 	WithProperty("name", openapi3.NewStringSchema())
//
// 	respSchema := new(openapi3.Schema)
// 	typ := reflect.TypeOf(*new(M)).Elem()
// 	buildSchema(typ, respSchema)
//
// 	// inputSchema generated by `M` fields that has "schema" tag
//
// 	verbMap := buildVerbMap(verb...)
// 	if verbMap[consts.Create] {
// 	}
// 	if verbMap[consts.Delete] {
// 	}
// 	if verbMap[consts.Update] {
// 	}
// 	if verbMap[consts.UpdatePartial] {
// 	}
// 	if verbMap[consts.List] {
// 		doc.Paths.Set(path, &openapi3.PathItem{
// 			Get: &openapi3.Operation{
// 				OperationID: "list users",
// 				Summary:     "Get list of users",
// 				Responses: func() *openapi3.Responses {
// 					resp := openapi3.NewResponses()
// 					resp.Set("200", &openapi3.ResponseRef{
// 						Value: &openapi3.Response{
// 							Description: util.ValueOf("List of users"),
// 							Content: openapi3.NewContentWithJSONSchema(
// 								openapi3.NewArraySchema().WithItems(respSchema),
// 							),
// 						},
// 					})
// 					return resp
// 				}(),
// 			},
// 		})
// 	}
// 	if verbMap[consts.Get] {
// 	}
// 	if verbMap[consts.Import] {
// 	}
// 	if verbMap[consts.Export] {
// 	}
// 	if verbMap[consts.BatchCreate] {
// 	}
// 	if verbMap[consts.BatchDelete] {
// 	}
// 	if verbMap[consts.BatchUpdate] {
// 	}
// 	if verbMap[consts.BatchUpdatePartial] {
// 	}
// }

// DocumentHandler returns an http.Handler that serves the OpenAPI document
func DocumentHandler() http.Handler {
	docMutex.Lock()
	setDocInfo(doc)
	docMutex.Unlock()
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		docMutex.RLock()
		// data, _ := json.MarshalIndent(doc, "", "  ")
		data, _ := json.Marshal(doc)
		docMutex.RUnlock()
		_, _ = w.Write(data)
	})
}

func setDocInfo(doc *openapi3.T) {
	doc.Info = &openapi3.Info{
		Title:       config.App.AppInfo.Name,
		Description: config.App.AppInfo.Name + " Restful api docs",
		Version:     config.App.AppInfo.Version,
	}
}

func getFieldTag(field reflect.StructField, tagName string) string {
	val := field.Tag.Get(tagName)
	switch val {
	case "-", "":
		return ""
	default:
		parts := strings.Split(val, ",")
		if len(parts) > 0 {
			return parts[0]
		}
		return ""
	}
}

func buildVerbs(verbs ...consts.HTTPVerb) []consts.HTTPVerb {
	verbMap := make(map[consts.HTTPVerb]bool)

	if len(verbs) == 0 {
		return make([]consts.HTTPVerb, 0)
	}
	for _, verb := range verbs {
		verbMap[verb] = true
	}

	vs := make([]consts.HTTPVerb, 0, len(verbMap))
	for verb := range verbMap {
		vs = append(vs, verb)
	}
	return vs
}

// ConvertColonParamsToBraces converts path parameters from :param to {param}.
func convertColonParamsToBraces(path string) string {
	if path == "" {
		return path
	}
	segments := strings.Split(path, "/")
	for i, seg := range segments {
		if strings.HasPrefix(seg, ":") && len(seg) > 1 {
			segments[i] = "{" + seg[1:] + "}"
		}
	}
	return strings.Join(segments, "/")
}
