package modelschema

import (
	"fmt"
	"hash/fnv"
	"reflect"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/hydroan/gst/config"
	"gorm.io/gorm"
	gormschema "gorm.io/gorm/schema"
)

// indexNameLimit returns the longest index name the database of db stores
// as it is: 63 characters on PostgreSQL, which cuts a longer identifier to
// 63 on its own and would then never find the index under its full name
// again, 64 on MySQL, which refuses a longer one, and on SQLite, which
// bounds none, held to MySQL's for the names to agree across the two.
func indexNameLimit(db *gorm.DB) int {
	if db != nil && db.Dialector != nil && strings.EqualFold(db.Dialector.Name(), string(config.DBPostgres)) {
		return 63
	}
	return 64
}

// Index declares one secondary index on the model's table.
//
// Indexes are the single way models declare secondary indexes: gorm struct
// tag indexes (index, uniqueIndex, unique) are banned in business projects
// by gg check, and the declaration also covers index shapes struct tags
// cannot express, such as indexes on columns promoted from the embedded
// Base or AutoBase.
//
// The declaration shape is deliberately minimal: ordered columns plus
// uniqueness cover the index forms whose semantics are identical on every
// supported dialect. Extensions follow real demand, descending columns
// first (identical semantics everywhere), then MySQL prefix lengths
// (dialect-specific, so they need an explicit cross-dialect failure
// contract). Partial, functional and fulltext indexes stay out: their
// semantics diverge per dialect, so hand-written DDL owns them.
type Index struct {
	Fields []string // Go struct field names; slice order is the index column order
	Unique bool     // Unique makes the index a unique index
}

// indexer is the optional capability interface through which models declare
// their secondary indexes.
//
// Indexes must be a pure declaration: it is invoked on zero-value model
// instances and must not depend on model data. Index names are always
// generated by the framework; declarations that conflict with struct tag
// indexes fail fast at bootstrap and inside gg migrate.
type indexer interface {
	Indexes() []Index
}

// IndexPlan is one resolved custom index: a validated declaration bound to a
// concrete table with a framework-generated name and database column names.
// The bootstrap executor and the migration schema dumper both consume
// IndexPlan, so the executed DDL and the desired-schema DDL always stay
// literally identical.
type IndexPlan struct {
	Name    string   // framework-generated index name
	Table   string   // table the index belongs to
	Columns []string // database column names in index order
	Unique  bool     // whether the index is unique
}

// CreateSQL renders the CREATE INDEX statement for the plan using the
// dialector's identifier quoting. Every consumer must render statements
// through this single method so DDL text never diverges between the
// database and the migration schema.
func (p IndexPlan) CreateSQL(dialector gorm.Dialector) string {
	var b strings.Builder
	b.WriteString("CREATE ")
	if p.Unique {
		b.WriteString("UNIQUE ")
	}
	b.WriteString("INDEX ")
	dialector.QuoteTo(&b, p.Name)
	b.WriteString(" ON ")
	dialector.QuoteTo(&b, p.Table)
	b.WriteString(" (")
	for i, col := range p.Columns {
		if i > 0 {
			b.WriteString(",")
		}
		dialector.QuoteTo(&b, col)
	}
	b.WriteString(")")
	return b.String()
}

// ParseIndexPlans resolves and validates the custom index declarations of
// model against its gorm schema parsed through db. It returns nil plans when
// the model declares no indexes (see IndexDeclarations).
//
// The table name comes from the parsed schema, which reads the model's own
// TableName method through gorm's Tabler; a model without an explicit name is
// rejected so no plan ever targets an empty table.
func ParseIndexPlans(db *gorm.DB, model any) ([]IndexPlan, error) {
	decls := IndexDeclarations(model)
	if len(decls) == 0 {
		return nil, nil
	}

	stmt := &gorm.Statement{DB: db}
	if err := stmt.Parse(model); err != nil {
		return nil, errors.Wrapf(err, "failed to parse schema for custom indexes of %T", model)
	}
	sch := stmt.Schema
	if len(sch.Table) == 0 {
		return nil, errors.Newf("model %s must declare an explicit table name by overriding TableName", sch.Name)
	}
	return buildIndexPlans(db, sch, sch.Table, decls)
}

// ValidateIndexes refuses in model's index declarations what ParseIndexPlans
// refuses under the dialect of db, and reports nothing else: the entry point
// of the column inspection gg builds into a project, which asks it against a
// MySQL handle that never connects (see mysql.DryRun) so gg check refuses a
// declaration before any database is touched. The public
// model.ValidateIndexes forwards to it.
func ValidateIndexes(db *gorm.DB, model any) error {
	_, err := ParseIndexPlans(db, model)
	return err
}

// buildIndexPlans validates declarations and resolves them into plans:
// every field must exist, no column repeats inside one index, no two
// declarations share the same column sequence, no declaration may duplicate
// a struct tag index, and every column must be one the dialect of db can
// index (see unindexableColumn). The names are held to the dialect's limit
// (see indexNameLimit).
func buildIndexPlans(db *gorm.DB, sch *gormschema.Schema, tableName string, decls []Index) ([]IndexPlan, error) {
	nameLimit := indexNameLimit(db)
	plans := make([]IndexPlan, 0, len(decls))
	declared := make(map[string]struct{}, len(decls))
	for _, decl := range decls {
		if len(decl.Fields) == 0 {
			return nil, errors.Newf("model %s: custom index must declare at least one field", sch.Name)
		}
		columns := make([]string, 0, len(decl.Fields))
		seenColumns := make(map[string]struct{}, len(decl.Fields))
		for _, name := range decl.Fields {
			// Only Go struct field names resolve, exactly as declared.
			// Database column names are deliberately rejected: accepting both
			// spellings would let the two forms mix across declarations.
			field := sch.FieldsByName[name]
			if field == nil {
				return nil, errors.Newf("model %s: custom index references unknown field %q", sch.Name, name)
			}
			if columnType, fix, ok := unindexableColumn(db, field); ok {
				return nil, errors.Newf("model %s: index field %s is a %s column, which %s", sch.Name, name, columnType, fix)
			}
			if _, ok := seenColumns[field.DBName]; ok {
				return nil, errors.Newf("model %s: custom index repeats column %q", sch.Name, field.DBName)
			}
			seenColumns[field.DBName] = struct{}{}
			columns = append(columns, field.DBName)
		}
		key := strings.Join(columns, ",")
		if _, ok := declared[key]; ok {
			return nil, errors.Newf("model %s: duplicate custom index on columns (%s)", sch.Name, key)
		}
		declared[key] = struct{}{}
		plans = append(plans, IndexPlan{
			Name:    indexName(tableName, columns, decl.Unique, nameLimit),
			Table:   tableName,
			Columns: columns,
			Unique:  decl.Unique,
		})
	}
	if err := checkTagIndexConflicts(sch, plans); err != nil {
		return nil, err
	}
	return plans, nil
}

// mysqlUnindexableTypes maps the MySQL column types an index cannot cover to
// the fix the refusal names. TEXT and BLOB in every size need a key length,
// which the declaration cannot express (see Index); JSON MySQL does not index
// at all. gorm's MySQL dialect stores a string field without a size as
// longtext, so a plain string column lands here unless the field declares a
// size or a bounded type; the dialect's own varchar(191) default covers only
// indexes declared in struct tags, which gg check bans.
var mysqlUnindexableTypes = map[string]string{
	"tinytext": keyLengthFix, "text": keyLengthFix, "mediumtext": keyLengthFix, "longtext": keyLengthFix,
	"tinyblob": keyLengthFix, "blob": keyLengthFix, "mediumblob": keyLengthFix, "longblob": keyLengthFix,
	"json": "MySQL does not index; index a bounded column holding the value or a generated column instead",
}

// keyLengthFix is the fix for a TEXT or BLOB column.
const keyLengthFix = "MySQL cannot index without a key length; give it a size (gorm:\"size:191\") or a bounded type"

// unindexableColumn reports the column type db's dialect gives field, and the
// fix, when that dialect cannot index it. Only MySQL has such types;
// PostgreSQL and SQLite index text columns of any length, so on them nothing
// is reported. The type is gorm's own mapping, FullDataTypeOf, which honors
// the size and type tags and the GormDataType and GormDBDataType methods of
// the field's type alike; its first word is the type, what may follow it (NOT
// NULL, a default, a character set) is not.
func unindexableColumn(db *gorm.DB, field *gormschema.Field) (columnType, fix string, ok bool) {
	if db == nil || db.Dialector == nil || !strings.EqualFold(db.Dialector.Name(), string(config.DBMySQL)) {
		return "", "", false
	}
	columnType, _, _ = strings.Cut(strings.TrimSpace(db.Migrator().FullDataTypeOf(field).SQL), " ")
	columnType = strings.ToLower(columnType)
	base, _, _ := strings.Cut(columnType, "(")
	fix, ok = mysqlUnindexableTypes[base]
	return columnType, fix, ok
}

// checkTagIndexConflicts rejects declarations that duplicate a struct tag
// index by name or by column sequence, and declarations that duplicate a
// bare unique tag — gorm keeps those out of ParseIndexes, so they take their
// own pass, or the same column would silently end up under two unique
// indexes. Duplicated declarations drift apart over time, so they fail fast
// instead of being merged silently.
//
// The guard is permanent, not transitional: gg check bans struct tag indexes
// in business projects, but running gg check is the project's choice, so
// this entry point keeps validating its own input instead of trusting that
// the ban was enforced elsewhere.
func checkTagIndexConflicts(sch *gormschema.Schema, plans []IndexPlan) error {
	for _, tagIndex := range sch.ParseIndexes() {
		columns := make([]string, 0, len(tagIndex.Fields))
		for _, opt := range tagIndex.Fields {
			columns = append(columns, opt.DBName)
		}
		key := strings.Join(columns, ",")
		for _, plan := range plans {
			if plan.Name == tagIndex.Name {
				return errors.Newf("model %s: custom index name %q conflicts with struct tag index", sch.Name, plan.Name)
			}
			if strings.Join(plan.Columns, ",") == key {
				return errors.Newf("model %s: custom index on columns (%s) duplicates struct tag index %q", sch.Name, key, tagIndex.Name)
			}
		}
	}

	for _, field := range sch.Fields {
		if !field.Unique || field.PrimaryKey || field.DBName == "" {
			continue
		}
		for _, plan := range plans {
			if len(plan.Columns) == 1 && plan.Columns[0] == field.DBName {
				return errors.Newf("model %s: custom index on column %q duplicates the unique struct tag on the same column", sch.Name, field.DBName)
			}
		}
	}
	return nil
}

// ModelIndexPlans binds the resolved index plans to the model that declared
// them, so cross-model validation can name both sides of a conflict.
type ModelIndexPlans struct {
	Model string      // display name of the declaring model
	Plans []IndexPlan // the model's resolved plans
}

// CheckCrossModelIndexPlanConflicts rejects conflicting index declarations
// across the models mapping one table. Several models may legitimately share
// a table (a query-shape alias, a copied module next to a business override),
// and each resolves its plans in isolation, so colliding declarations would
// otherwise duplicate silently: the bootstrap executor skips an index that
// already exists, and the schema dumper would render the statement twice.
//
// Two shapes conflict on one table:
//   - two plans covering the same column sequence, whatever their uniqueness:
//     equal declarations are a duplicate, diverging uniqueness would put two
//     indexes over one column sequence;
//   - two plans generating the same name for different definitions, which the
//     deterministic naming only produces through truncation-hash collisions.
func CheckCrossModelIndexPlanConflicts(sets []ModelIndexPlans) error {
	type owner struct {
		model   string
		columns string
	}
	byColumns := make(map[string]owner)
	byName := make(map[string]owner)
	for _, set := range sets {
		for _, plan := range set.Plans {
			columns := strings.Join(plan.Columns, ",")
			columnsKey := plan.Table + "\x00" + columns
			if prev, ok := byColumns[columnsKey]; ok {
				return errors.Newf("index plans conflict on table %q: %s and %s both declare columns (%s)",
					plan.Table, prev.model, set.Model, columns)
			}
			byColumns[columnsKey] = owner{model: set.Model, columns: columns}

			nameKey := plan.Table + "\x00" + plan.Name
			if prev, ok := byName[nameKey]; ok {
				return errors.Newf("index plans conflict on table %q: %s and %s generate the same index name %q for different definitions",
					plan.Table, prev.model, set.Model, plan.Name)
			}
			byName[nameKey] = owner{model: set.Model, columns: columns}
		}
	}
	return nil
}

// indexName generates the deterministic framework index name: an idx_ (or
// uniq_ for unique) prefix, the table name, and the column names,
// idx_samples_kind_created_at for the columns kind and created_at of
// samples. A name beyond limit characters (see indexNameLimit) keeps a
// readable prefix and ends with an fnv-32a hash of the full name, so
// truncation stays deterministic across runs.
func indexName(table string, columns []string, unique bool, limit int) string {
	prefix := "idx_"
	if unique {
		prefix = "uniq_"
	}
	name := prefix + table + "_" + strings.Join(columns, "_")
	if len(name) <= limit {
		return name
	}
	h := fnv.New32a()
	_, _ = h.Write([]byte(name))
	return fmt.Sprintf("%s_%08x", name[:limit-9], h.Sum32())
}

// IndexDeclarations returns the secondary indexes model declares through its
// Indexes method, nil when it declares none. A value and a pointer alike are
// probed, since registry snapshots and schema dump inputs mix the two forms;
// a value is probed through a zero-value pointer, which is safe because
// Indexes must be a pure declaration.
func IndexDeclarations(model any) []Index {
	if declarer, ok := model.(indexer); ok {
		return declarer.Indexes()
	}
	typ := reflect.TypeOf(model)
	if typ == nil || typ.Kind() == reflect.Pointer {
		return nil
	}
	if declarer, ok := reflect.TypeAssert[indexer](reflect.New(typ)); ok {
		return declarer.Indexes()
	}
	return nil
}
