// Package apidoc keeps a registry of Go struct doc comments used to enrich
// the generated OpenAPI document.
//
// Code generated by gg registers struct and field comments at build time so
// the running binary can describe schema fields even when Go source files are
// not available, eg. in a container image that only ships the compiled binary.
package apidoc

import (
	"maps"
	"sync"
)

// StructDoc holds the doc comments of a single struct.
type StructDoc struct {
	// Comment is the doc comment of the struct itself.
	Comment string
	// Fields maps a Go field name to its doc comment.
	Fields map[string]string
}

var (
	mu       sync.RWMutex
	registry = make(map[string]StructDoc)
)

func registryKey(pkgPath, typeName string) string {
	return pkgPath + "." + typeName
}

// Register records the doc comments for the struct identified by pkgPath and
// typeName. Registering the same struct again replaces the previous entry.
// The Fields map is copied, so callers may reuse it after Register returns.
func Register(pkgPath, typeName string, doc StructDoc) {
	doc.Fields = maps.Clone(doc.Fields)

	mu.Lock()
	defer mu.Unlock()
	registry[registryKey(pkgPath, typeName)] = doc
}

// Lookup returns the doc comments registered for the struct identified by
// pkgPath and typeName. The returned StructDoc owns its Fields map, so
// callers may mutate it freely.
func Lookup(pkgPath, typeName string) (StructDoc, bool) {
	mu.RLock()
	defer mu.RUnlock()

	doc, ok := registry[registryKey(pkgPath, typeName)]
	if !ok {
		return StructDoc{}, false
	}
	doc.Fields = maps.Clone(doc.Fields)
	return doc, true
}
