// Package apidoc keeps a registry of Go struct doc comments used to enrich
// the generated OpenAPI document.
//
// Code generated by gg registers struct and field comments at build time so
// the running binary can describe schema fields even when Go source files are
// not available, eg. in a container image that only ships the compiled binary.
package apidoc

import (
	"maps"
	"slices"
	"sync"
)

// StructDoc holds the doc comments of a single struct.
type StructDoc struct {
	// Comment is the doc comment of the struct itself.
	Comment string
	// Fields maps a Go field name to its doc comment.
	Fields map[string]string
}

// EnumValue describes one declared constant of an enum-like named type.
type EnumValue struct {
	// Value is the constant literal as it appears in JSON, eg. "fixed_odds" or 2.
	Value any
	// Comment is the doc comment of the constant.
	Comment string
}

// EnumDoc holds the doc comment and declared values of an enum-like named
// type, eg. `type PayoutRuleType string` with a const block of its values.
type EnumDoc struct {
	// Comment is the doc comment of the type itself.
	Comment string
	// Values lists the declared constants in source order.
	Values []EnumValue
}

var (
	mu           sync.RWMutex
	registry     = make(map[string]StructDoc)
	enumRegistry = make(map[string]EnumDoc)
)

func registryKey(pkgPath, typeName string) string {
	return pkgPath + "." + typeName
}

// Register records the doc comments for the struct identified by pkgPath and
// typeName. Registering the same struct again replaces the previous entry.
// The Fields map is copied, so callers may reuse it after Register returns.
func Register(pkgPath, typeName string, doc StructDoc) {
	doc.Fields = maps.Clone(doc.Fields)

	mu.Lock()
	defer mu.Unlock()
	registry[registryKey(pkgPath, typeName)] = doc
}

// Lookup returns the doc comments registered for the struct identified by
// pkgPath and typeName. The returned StructDoc owns its Fields map, so
// callers may mutate it freely.
func Lookup(pkgPath, typeName string) (StructDoc, bool) {
	mu.RLock()
	defer mu.RUnlock()

	doc, ok := registry[registryKey(pkgPath, typeName)]
	if !ok {
		return StructDoc{}, false
	}
	doc.Fields = maps.Clone(doc.Fields)
	return doc, true
}

// RegisterEnum records the doc comment and declared values of the enum-like
// type identified by pkgPath and typeName. Registering the same type again
// replaces the previous entry. The Values slice is copied, so callers may
// reuse it after RegisterEnum returns.
func RegisterEnum(pkgPath, typeName string, doc EnumDoc) {
	doc.Values = slices.Clone(doc.Values)

	mu.Lock()
	defer mu.Unlock()
	enumRegistry[registryKey(pkgPath, typeName)] = doc
}

// LookupEnum returns the enum doc registered for the type identified by
// pkgPath and typeName. The returned EnumDoc owns its Values slice, so
// callers may mutate it freely.
func LookupEnum(pkgPath, typeName string) (EnumDoc, bool) {
	mu.RLock()
	defer mu.RUnlock()

	doc, ok := enumRegistry[registryKey(pkgPath, typeName)]
	if !ok {
		return EnumDoc{}, false
	}
	doc.Values = slices.Clone(doc.Values)
	return doc, true
}
