package dao

import (
	"github.com/hydroan/gst/database"
	"github.com/hydroan/gst/types"
)

// QueryModelsToMap queries models of type M from the database and returns a map with keys generated by keyFunc.
//
// This function is useful for converting query results into a map for efficient lookups,
// commonly used in scenarios like populating related data in list operations.
//
// Parameters:
//   - ctx: Database context for the query operation
//   - keyFunc: Function to generate map keys from model instances. If nil, defaults to using model.GetID()
//   - queryFunc: Function that returns a model instance used as query conditions. If nil, defaults to an empty query
//     (which will query all records when AllowEmpty is true in QueryConfig)
//
// Returns:
//   - map[string]M: A map where keys are generated by keyFunc and values are the queried model instances
//   - error: Any error encountered during the query operation
//
// Default Behavior:
//   - When keyFunc is nil: Uses model.GetID() as the key
//   - When queryFunc is nil: Uses an empty model instance, which queries all records (AllowEmpty: true is set internally)
//
// Usage Examples:
//
//	// Query all users and map by ID (default keyFunc)
//	userMap, err := QueryModelsToMap(ctx, nil, nil)
//
//	// Query users and map by custom key
//	userMap, err := QueryModelsToMap(ctx, func(u *User) string { return u.Username }, nil)
//
//	// Query users with specific conditions
//	userMap, err := QueryModelsToMap(ctx, func(u *User) string { return u.ID },
//		func() *User { return &User{Status: "active"} })
func QueryModelsToMap[M types.Model](ctx *types.DatabaseContext, keyFunc func(M) string, queryFunc func() M) (map[string]M, error) {
	if keyFunc == nil {
		keyFunc = func(m M) string {
			return m.GetID()
		}
	}
	if queryFunc == nil {
		queryFunc = func() M {
			var m M
			return m
		}
	}

	objs := make([]M, 0)
	if err := database.Database[M](ctx).
		WithQuery(queryFunc(), types.QueryConfig{AllowEmpty: true}).
		List(&objs); err != nil {
		return nil, err
	}

	objMap := make(map[string]M)
	for _, obj := range objs {
		objMap[keyFunc(obj)] = obj
	}

	return objMap, nil
}
