// Code generated by gst; DO NOT EDIT.
// source: model/board/note.go

package board

import (
	"github.com/hydroan/gst"
	"gorm.io/gorm"
)

// NoteCols are the typed column references of Note.
var NoteCols = struct {
	Body        gst.Column[string]
	CreatedAt   gst.TimeColumn
	CreatedBy   gst.Column[string]
	DeletedAt   gst.Column[gorm.DeletedAt]
	ID          gst.Column[string]
	Published   gst.Column[bool]
	PublishedAt gst.TimeColumn
	Title       gst.Column[string]
	UpdatedAt   gst.TimeColumn
	UpdatedBy   gst.Column[string]
}{
	Body:        gst.NewColumn[*Note, string]("body"),
	CreatedAt:   gst.NewTimeColumn[*Note]("created_at"),
	CreatedBy:   gst.NewColumn[*Note, string]("created_by"),
	DeletedAt:   gst.NewColumn[*Note, gorm.DeletedAt]("deleted_at"),
	ID:          gst.NewColumn[*Note, string]("id"),
	Published:   gst.NewColumn[*Note, bool]("published"),
	PublishedAt: gst.NewTimeColumn[*Note]("published_at"),
	Title:       gst.NewColumn[*Note, string]("title"),
	UpdatedAt:   gst.NewTimeColumn[*Note]("updated_at"),
	UpdatedBy:   gst.NewColumn[*Note, string]("updated_by"),
}
