// Code generated by gst; DO NOT EDIT.

package router

import (
	"cluster/model"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/router"

	"github.com/hydroan/gst"
	gstmodel "github.com/hydroan/gst/model"
)

func Init() error {
	router.Register[*model.Cached, *model.CachedReq, *model.CachedRsp](router.Auth(), "/api/caches", &gst.ControllerConfig[*model.Cached]{}, consts.Create)
	router.Register[*model.Cached, *gstmodel.Empty, *model.CachedRsp](router.Auth(), "/api/caches/:id", &gst.ControllerConfig[*model.Cached]{ParamName: "id"}, consts.Delete)
	router.Register[*model.Cached, *gstmodel.Empty, *model.CachedRsp](router.Auth(), "/api/caches/:id", &gst.ControllerConfig[*model.Cached]{ParamName: "id"}, consts.Get)
	router.Register[*model.CounterStep, *model.CounterStep, *model.CounterStep](router.Auth(), "/api/counter_steps", &gst.ControllerConfig[*model.CounterStep]{}, consts.List)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags", &gst.ControllerConfig[*model.Flag]{}, consts.Create)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/:id", &gst.ControllerConfig[*model.Flag]{ParamName: "id"}, consts.Delete)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/:id", &gst.ControllerConfig[*model.Flag]{ParamName: "id"}, consts.Update)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/:id", &gst.ControllerConfig[*model.Flag]{ParamName: "id"}, consts.Patch)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags", &gst.ControllerConfig[*model.Flag]{}, consts.List)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/:id", &gst.ControllerConfig[*model.Flag]{ParamName: "id"}, consts.Get)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/batch", &gst.ControllerConfig[*model.Flag]{}, consts.CreateMany)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/batch", &gst.ControllerConfig[*model.Flag]{}, consts.DeleteMany)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/batch", &gst.ControllerConfig[*model.Flag]{}, consts.UpdateMany)
	router.Register[*model.Flag, *model.Flag, *model.Flag](router.Auth(), "/api/flags/batch", &gst.ControllerConfig[*model.Flag]{}, consts.PatchMany)
	router.Register[*model.Rebuild, *model.RebuildReq, *model.RebuildRsp](router.Auth(), "/api/rebuilds", &gst.ControllerConfig[*model.Rebuild]{}, consts.Create)
	router.Register[*model.Run, *model.Run, *model.Run](router.Auth(), "/api/runs", &gst.ControllerConfig[*model.Run]{}, consts.List)
	router.Register[*model.StepDown, *gstmodel.Empty, *model.StepDownRsp](router.Auth(), "/api/step-downs", &gst.ControllerConfig[*model.StepDown]{}, consts.Create)
	return nil
}
