// Code generated by gst; DO NOT EDIT.

package service

import (
	"cluster/service/cached"
	"cluster/service/rebuild"
	"cluster/service/step_down"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/service"
)

func init() {
	service.Register[*cached.Creator](consts.Create, "/api/caches")
	service.Register[*cached.Deleter](consts.Delete, "/api/caches/:id")
	service.Register[*cached.Getter](consts.Get, "/api/caches/:id")
	service.Register[*rebuild.Creator](consts.Create, "/api/rebuilds")
	service.Register[*stepdown.Creator](consts.Create, "/api/step-downs")
}
