// Code generated by gst; DO NOT EDIT.

package service

import (
	"cluster/service/cached"
	"cluster/service/rebuild"
	"cluster/service/step_down"

	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/service"
)

func init() {
	service.Register[*cached.Creator](consts.PHASE_CREATE, "caches")
	service.Register[*cached.Deleter](consts.PHASE_DELETE, "caches/:id")
	service.Register[*cached.Getter](consts.PHASE_GET, "caches/:id")
	service.Register[*rebuild.Creator](consts.PHASE_CREATE, "rebuilds")
	service.Register[*stepdown.Creator](consts.PHASE_CREATE, "step-downs")
}
