// Package hookoverride tells whether a type overrides a method beyond the
// framework base it embeds, reading the answer off the compiled binary.
//
// Every model and service carries its lifecycle hooks through an embedded
// framework base whose implementations are no-ops. Knowing which of them a
// type overrides lets the framework drop work that exists only for the hooks'
// sake — a transaction around a write, a span around a call.
//
// A method declared on a type reports the source file it was written in,
// while every promotion through an embedded field — whether it forwards to
// the framework no-op or to a real implementation on an intermediate type —
// and every pointer wrapper around a value-receiver method is a wrapper the
// compiler stamps with "<autogenerated>". A wrapper therefore says nothing by
// itself; the walk descends the embedding tree breadth-first, mirroring Go's
// shallowest-wins promotion rule, until it reaches the type that declares the
// method. Only a declaration owned by a framework base counts as not
// overridden, and which types are bases is the caller's to say. Anything
// unresolvable counts as overridden, which only keeps work that was not
// strictly needed.
package hookoverride

import (
	"reflect"
	"runtime"
)

// autogeneratedFile is the source position the compiler stamps on the method
// wrappers it synthesizes for embedded-field promotion and for reaching a
// value-receiver method through a pointer.
const autogeneratedFile = "<autogenerated>"

// Overridden reports whether the method named name that typ carries resolves
// to a declaration on a type other than a framework base. isBase receives the
// declaring struct type, never a pointer to it. A method typ does not have
// runs nothing and so overrides nothing.
func Overridden(typ reflect.Type, name string, isBase func(reflect.Type) bool) bool {
	method, ok := typ.MethodByName(name)
	if !ok {
		return false
	}
	if !isAutogenerated(method) {
		// Declared on typ itself: a pointer receiver on a pointer type, or a
		// value receiver on a value type.
		return !isBase(structOf(typ))
	}
	return promotedDeclarerOverrides(typ, name, isBase)
}

// structOf strips one level of pointer so a declaring type is always reported
// as the struct that carries the declaration.
func structOf(typ reflect.Type) reflect.Type {
	if typ.Kind() == reflect.Pointer {
		return typ.Elem()
	}
	return typ
}

// promotedDeclarerOverrides resolves which type declares the method a
// compiler wrapper forwards to and reports whether that declarer is anything
// but a framework base. The walk is breadth-first because Go promotes the
// shallowest declaration; a declaration found at one depth shadows anything
// deeper. Dead ends fail closed as overridden.
func promotedDeclarerOverrides(typ reflect.Type, name string, isBase func(reflect.Type) bool) bool {
	structTyp := structOf(typ)
	if structTyp.Kind() != reflect.Struct {
		return true
	}
	// A value-receiver declaration on the struct itself is reached through a
	// pointer wrapper too, and shadows anything promoted from below.
	if method, ok := structTyp.MethodByName(name); ok && !isAutogenerated(method) {
		return !isBase(structTyp)
	}

	depth := []reflect.Type{structTyp}
	for len(depth) > 0 {
		var deeper []reflect.Type
		var declarers []reflect.Type
		for _, st := range depth {
			for field := range st.Fields() {
				if !field.Anonymous {
					continue
				}
				fieldTyp := structOf(field.Type)
				if fieldTyp.Kind() != reflect.Struct {
					continue
				}
				// A value-receiver declaration sits in the value method set;
				// a pointer-receiver one only in the pointer method set.
				if method, ok := fieldTyp.MethodByName(name); ok && !isAutogenerated(method) {
					declarers = append(declarers, fieldTyp)
					continue
				}
				method, ok := reflect.PointerTo(fieldTyp).MethodByName(name)
				if !ok {
					continue
				}
				if isAutogenerated(method) {
					deeper = append(deeper, fieldTyp)
					continue
				}
				declarers = append(declarers, fieldTyp)
			}
		}
		if len(declarers) == 1 {
			return !isBase(declarers[0])
		}
		if len(declarers) > 1 {
			return true
		}
		depth = deeper
	}
	return true
}

// isAutogenerated reports whether the method is a compiler-synthesized wrapper
// rather than a declaration written in source. A method whose function cannot
// be resolved reports false, so the caller treats it as a declaration and
// fails closed through the base check.
func isAutogenerated(method reflect.Method) bool {
	fn := runtime.FuncForPC(method.Func.Pointer())
	if fn == nil {
		return false
	}
	file, _ := fn.FileLine(fn.Entry())
	return file == autogeneratedFile
}
