// Code generated by gst; DO NOT EDIT.

package model

import "github.com/hydroan/gst/apidoc"

func init() {
	apidoc.Register("demo/model", "Notice", apidoc.StructDoc{
		Comment: "Notice is a virtual resource demonstrating the SSE streaming action: the\nroute serves a long-lived text/event-stream that a browser consumes through\nan EventSource, or a Go caller through client.Stream.",
	})
	apidoc.Register("demo/model", "Record", apidoc.StructDoc{
		Comment: "Record demonstrates a database-backed resource with custom service hooks.",
		Fields: map[string]string{
			"Username": "Username is returned to clients and is not stored in the database.",
		},
	})
	apidoc.Register("demo/model", "TraceProbe", apidoc.StructDoc{
		Comment: "TraceProbe exercises standard CRUD context propagation through service,\ndatabase, GORM, and model hooks.",
	})
	apidoc.Register("demo/model/auth", "Login", apidoc.StructDoc{
		Comment: "Login demonstrates a public action that is not backed by a database table.",
	})
	apidoc.Register("demo/model/auth", "LoginRsp", apidoc.StructDoc{
		Comment: "LoginRsp contains the URL a client should open to start authentication.",
	})
	apidoc.Register("demo/model/common", "Search", apidoc.StructDoc{
		Comment: "Search demonstrates a non-database utility action.",
	})
	apidoc.Register("demo/model/common", "SearchDedupReq", apidoc.StructDoc{
		Comment: "SearchDedupReq is the request for deduplicating search sources.",
	})
	apidoc.Register("demo/model/common", "SearchDedupRsp", apidoc.StructDoc{
		Comment: "SearchDedupRsp is the response returned after source deduplication.",
	})
	apidoc.Register("demo/model/common", "SearchSource", apidoc.StructDoc{
		Comment: "SearchSource is one candidate source returned by an external search provider.",
	})
	apidoc.Register("demo/model/config", "File", apidoc.StructDoc{
		Comment: "File demonstrates a database resource with custom routes and model hooks.",
	})
	apidoc.Register("demo/model/config/file", "Encrypt", apidoc.StructDoc{
		Comment: "Encrypt demonstrates a custom action model for a configuration file.",
	})
	apidoc.Register("demo/model/config/file", "EncryptReq", apidoc.StructDoc{
		Comment: "EncryptReq is the request for encrypting a configuration file payload.",
	})
	apidoc.Register("demo/model/config/file", "EncryptRsp", apidoc.StructDoc{
		Comment: "EncryptRsp is the response returned after encrypting a configuration file.",
	})
	apidoc.Register("demo/model/record", "Item", apidoc.StructDoc{
		Comment: "Item demonstrates a child resource with nested routes and batch actions.",
	})
	apidoc.Register("demo/model/record", "SearchSource", apidoc.StructDoc{
		Comment: "SearchSource describes an external reference attached to an item.",
	})
	apidoc.RegisterEnum("demo/model", "RecordType", apidoc.EnumDoc{
		Comment: "RecordType identifies the content type handled by a record.",
		Values: []apidoc.EnumValue{
			{Value: "text"},
			{Value: "image"},
		},
	})
	apidoc.RegisterEnum("demo/model/config", "FileFormat", apidoc.EnumDoc{
		Comment: "FileFormat identifies the expected syntax of a configuration file.",
		Values: []apidoc.EnumValue{
			{Value: "text"},
			{Value: "json"},
			{Value: "yaml"},
			{Value: "env"},
		},
	})
	apidoc.RegisterEnum("demo/model/record", "ItemKind", apidoc.EnumDoc{
		Comment: "ItemKind identifies the kind of an item.",
		Values: []apidoc.EnumValue{
			{Value: "input"},
			{Value: "output"},
			{Value: "system"},
		},
	})
}
