// Code generated by gst; DO NOT EDIT.
// source: model/audit.go

package model

import (
	"github.com/hydroan/gst"
	"gorm.io/gorm"
)

// AuditCols are the typed column references of Audit.
var AuditCols = struct {
	Action    gst.Column[string]
	Actor     gst.Column[string]
	CreatedAt gst.TimeColumn
	CreatedBy gst.Column[string]
	DeletedAt gst.Column[gorm.DeletedAt]
	ID        gst.Column[string]
	RecordID  gst.Column[string]
	UpdatedAt gst.TimeColumn
	UpdatedBy gst.Column[string]
}{
	Action:    gst.NewColumn[*Audit, string]("action"),
	Actor:     gst.NewColumn[*Audit, string]("actor"),
	CreatedAt: gst.NewTimeColumn[*Audit]("created_at"),
	CreatedBy: gst.NewColumn[*Audit, string]("created_by"),
	DeletedAt: gst.NewColumn[*Audit, gorm.DeletedAt]("deleted_at"),
	ID:        gst.NewColumn[*Audit, string]("id"),
	RecordID:  gst.NewColumn[*Audit, string]("record_id"),
	UpdatedAt: gst.NewTimeColumn[*Audit]("updated_at"),
	UpdatedBy: gst.NewColumn[*Audit, string]("updated_by"),
}
