// Code generated by gst; DO NOT EDIT.
// source: model/conversation.go

package model

import (
	types "github.com/hydroan/gst/types"
	gorm "gorm.io/gorm"
)

// ConversationCols are the typed column references of Conversation.
var ConversationCols = struct {
	CreatedAt types.TimeColumn
	CreatedBy types.Column[string]
	DeletedAt types.Column[gorm.DeletedAt]
	ID        types.Column[string]
	Title     types.Column[string]
	Type      types.Column[ConversationType]
	UpdatedAt types.TimeColumn
	UpdatedBy types.Column[string]
	UserID    types.Column[string]
}{
	CreatedAt: types.NewTimeColumn("created_at"),
	CreatedBy: types.NewColumn[string]("created_by"),
	DeletedAt: types.NewColumn[gorm.DeletedAt]("deleted_at"),
	ID:        types.NewColumn[string]("id"),
	Title:     types.NewColumn[string]("title"),
	Type:      types.NewColumn[ConversationType]("type"),
	UpdatedAt: types.NewTimeColumn("updated_at"),
	UpdatedBy: types.NewColumn[string]("updated_by"),
	UserID:    types.NewColumn[string]("user_id"),
}
