// Code generated by gst; DO NOT EDIT.

package model

import (
	"demo/model/archive"
	"demo/model/board"
	"demo/model/record"

	"github.com/hydroan/gst/model"
)

func init() {
	model.Register[*archive.Document]()
	model.Register[*Audit]()
	model.Register[*board.Note]()
	model.Register[*record.Item]()
	model.Register[*Record]()
}
