// Code generated by gst; DO NOT EDIT.
// source: model/record.go

package model

import (
	types "github.com/hydroan/gst/types"
	gorm "gorm.io/gorm"
)

// RecordCols are the typed column references of Record.
var RecordCols = struct {
	CreatedAt types.TimeColumn
	CreatedBy types.Column[string]
	DeletedAt types.Column[gorm.DeletedAt]
	ID        types.Column[string]
	Title     types.Column[string]
	Type      types.Column[RecordType]
	UpdatedAt types.TimeColumn
	UpdatedBy types.Column[string]
	UserID    types.Column[string]
}{
	CreatedAt: types.NewTimeColumn[*Record]("created_at"),
	CreatedBy: types.NewColumn[*Record, string]("created_by"),
	DeletedAt: types.NewColumn[*Record, gorm.DeletedAt]("deleted_at"),
	ID:        types.NewColumn[*Record, string]("id"),
	Title:     types.NewColumn[*Record, string]("title"),
	Type:      types.NewColumn[*Record, RecordType]("type"),
	UpdatedAt: types.NewTimeColumn[*Record]("updated_at"),
	UpdatedBy: types.NewColumn[*Record, string]("updated_by"),
	UserID:    types.NewColumn[*Record, string]("user_id"),
}
