// Code generated by gst; DO NOT EDIT.
// source: model/trace_probe.go

package model

import (
	gst "github.com/hydroan/gst"
	gorm "gorm.io/gorm"
)

// TraceProbeCols are the typed column references of TraceProbe.
var TraceProbeCols = struct {
	CreatedAt gst.TimeColumn
	CreatedBy gst.Column[string]
	DeletedAt gst.Column[gorm.DeletedAt]
	Hook      gst.Column[string]
	ID        gst.Column[string]
	Name      gst.Column[string]
	Note      gst.Column[string]
	UpdatedAt gst.TimeColumn
	UpdatedBy gst.Column[string]
}{
	CreatedAt: gst.NewTimeColumn[*TraceProbe]("created_at"),
	CreatedBy: gst.NewColumn[*TraceProbe, string]("created_by"),
	DeletedAt: gst.NewColumn[*TraceProbe, gorm.DeletedAt]("deleted_at"),
	Hook:      gst.NewColumn[*TraceProbe, string]("hook"),
	ID:        gst.NewColumn[*TraceProbe, string]("id"),
	Name:      gst.NewColumn[*TraceProbe, string]("name"),
	Note:      gst.NewColumn[*TraceProbe, string]("note"),
	UpdatedAt: gst.NewTimeColumn[*TraceProbe]("updated_at"),
	UpdatedBy: gst.NewColumn[*TraceProbe, string]("updated_by"),
}
