package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hydroan/gst/consts"
)

func TestGenTypeScriptRunWritesTheDeclarationsOfTheRoutes(t *testing.T) {
	projectDir := newGenProject(t)
	writeTypeScriptProject(t, projectDir, typeScriptSampleModel)

	runGenTypeScript(t)

	if _, err := os.Stat(filepath.Join(projectDir, "generated", "typescript", "gst.ts")); err != nil {
		t.Fatalf("gst.ts was not generated: %v", err)
	}
	declarations := readTypeScriptFile(t, projectDir, "model.ts")
	for _, want := range []string{
		"export interface Sample {",
		// model.Base reaches the generator through the public alias.
		"  id: string;",
		"  status: SampleStatus | \"\";",
		"export type SampleStatus = \"active\" | \"archived\";",
		"export interface SampleArchiveReq {",
		"export interface SampleArchiveRsp {",
	} {
		if !strings.Contains(declarations, want) {
			t.Errorf("model.ts is missing %q:\n%s", want, declarations)
		}
	}
	// The route ignored in gst.yaml behaves as if it were never declared, so
	// the type only it answers with is not generated.
	if strings.Contains(declarations, "SampleListRsp") {
		t.Errorf("model.ts declares the result of the ignored route:\n%s", declarations)
	}
}

func TestGenTypeScriptRunReplacesTheFilesOfAnEarlierRun(t *testing.T) {
	projectDir := newGenProject(t)
	writeTypeScriptProject(t, projectDir, typeScriptSampleModel)
	runGenTypeScript(t)

	outputDir := filepath.Join(projectDir, "generated", "typescript")
	stale := filepath.Join(outputDir, "model", "gone", "stale.ts")
	writeCheckFile(t, stale, consts.CodeGeneratedComment()+"\n\nexport type Stale = string;\n")
	handwritten := filepath.Join(outputDir, "notes.ts")
	writeCheckFile(t, handwritten, "export type Note = string;\n")

	output := runGenTypeScript(t)

	if !strings.Contains(output, filepath.Join("generated", "typescript", "model.ts")) || !strings.Contains(output, "SKIP") {
		t.Errorf("the unchanged model.ts should be skipped:\n%s", output)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("the generated file no route needs should be removed, stat error = %v", err)
	}
	if _, err := os.Stat(filepath.Dir(stale)); !os.IsNotExist(err) {
		t.Errorf("the directory the removal left empty should be removed, stat error = %v", err)
	}
	if _, err := os.Stat(handwritten); err != nil {
		t.Errorf("a file gg did not generate should be kept: %v", err)
	}
}

func TestGenTypeScriptRunRefusesToOverwriteAFileItDidNotGenerate(t *testing.T) {
	projectDir := newGenProject(t)
	writeTypeScriptProject(t, projectDir, typeScriptSampleModel)
	target := filepath.Join(projectDir, "generated", "typescript", "gst.ts")
	const handwritten = "export type Handwritten = string;\n"
	writeCheckFile(t, target, handwritten)

	var err error
	captureStdout(t, func() { err = genTypeScriptRun() })

	if err == nil || !strings.Contains(err.Error(), "was not generated by gg") {
		t.Fatalf("genTypeScriptRun() error = %v, want the refusal to overwrite gst.ts", err)
	}
	content, readErr := os.ReadFile(target)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(content) != handwritten {
		t.Errorf("gst.ts was overwritten:\n%s", content)
	}
}

func TestGenTypeScriptRunWritesNothingWhenATypeCannotBeDescribed(t *testing.T) {
	projectDir := newGenProject(t)
	rejected := strings.Replace(typeScriptSampleModel, `Reason string 'json:"reason"'`, `Updates chan int 'json:"updates"'`, 1)
	writeTypeScriptProject(t, projectDir, rejected)

	var err error
	captureStdout(t, func() { err = genTypeScriptRun() })

	if err == nil || !strings.Contains(err.Error(), "tmpapp/model.SampleArchiveReq.updates") {
		t.Fatalf("genTypeScriptRun() error = %v, want a diagnostic for SampleArchiveReq.updates", err)
	}
	if _, statErr := os.Stat(filepath.Join(projectDir, "generated", "typescript")); !os.IsNotExist(statErr) {
		t.Errorf("a failed run must write no file, stat error = %v", statErr)
	}
}

// typeScriptSampleModel is the model file of the TypeScript generation tests,
// with its struct tags quoted by ' instead of backquotes. gst.yaml ignores its
// List route.
const typeScriptSampleModel = `package model

import (
	"github.com/hydroan/gst/dsl"
	"github.com/hydroan/gst/model"
)

type Sample struct {
	Name   string       'json:"name"'
	Status SampleStatus 'json:"status"'

	model.Base
}

// SampleStatus is the lifecycle state of a sample.
type SampleStatus string

const (
	SampleStatusActive   SampleStatus = "active"
	SampleStatusArchived SampleStatus = "archived"
)

type SampleArchiveReq struct {
	Reason string 'json:"reason"'
}

type SampleArchiveRsp struct {
	Archived bool 'json:"archived"'
}

type SampleListRsp struct {
	Total int 'json:"total"'
}

func (Sample) TableName() string { return "samples" }

func (Sample) Design() {
	dsl.Migrate()
	dsl.Route("samples", func() {
		dsl.Create(func() {})
		dsl.Get(func() {})
		dsl.List(func() {
			dsl.Result[*SampleListRsp]()
		})
	})
	dsl.Route("samples/archive", func() {
		dsl.Create(func() {
			dsl.Payload[*SampleArchiveReq]()
			dsl.Result[*SampleArchiveRsp]()
		})
	})
}
`

// writeTypeScriptProject writes the model file modelSource describes and a
// gst.yaml ignoring the List route of the samples.
func writeTypeScriptProject(t *testing.T, projectDir, modelSource string) {
	t.Helper()

	writeCheckFile(t, filepath.Join(projectDir, "gst.yaml"), "version: 1\ngen:\n  routes:\n    ignore:\n      /api/samples: [GET]\n")
	writeCheckFile(t, filepath.Join(projectDir, "model", "sample.go"), strings.ReplaceAll(modelSource, "'", "`"))
}

// runGenTypeScript runs gg gen ts, failing the test on an error, and returns
// what it printed.
func runGenTypeScript(t *testing.T) string {
	t.Helper()

	var err error
	output := captureStdout(t, func() { err = genTypeScriptRun() })
	if err != nil {
		t.Fatalf("genTypeScriptRun() error = %v\n%s", err, output)
	}
	return output
}

// readTypeScriptFile reads a file gg gen ts generated.
func readTypeScriptFile(t *testing.T, projectDir, name string) string {
	t.Helper()

	content, err := os.ReadFile(filepath.Join(projectDir, "generated", "typescript", filepath.FromSlash(name)))
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}
