package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/hydroan/gst/internal/clioutput"
	"github.com/spf13/cobra"
)

// releaseCmd represents the release command
var releaseCmd = &cobra.Command{
	Use:   "release",
	Short: "Build and release packages using goreleaser",
	Long: `Build and release packages using goreleaser.

This command will:
- Check if goreleaser is installed
- Generate .goreleaser.yml configuration if not exists
- Build release packages for multiple platforms
- Support different release modes (snapshot, release)

Examples:
  gg release                    # Build snapshot release
  gg release --publish          # Build and publish release
  gg release --init             # Generate .goreleaser.yml config
  gg release --check            # Check goreleaser installation`,
	RunE: releaseRun,
}

var (
	releaseInit     bool
	releasePublish  bool
	releaseCheck    bool
	releaseSnapshot bool
	releaseClean    bool
	releaseSkipSign bool
)

func init() {
	releaseCmd.Flags().BoolVar(&releaseInit, "init", false, "Generate .goreleaser.yml configuration file")
	releaseCmd.Flags().BoolVar(&releasePublish, "publish", false, "Publish release (requires GITHUB_TOKEN)")
	releaseCmd.Flags().BoolVar(&releaseCheck, "check", false, "Check goreleaser installation and configuration")
	releaseCmd.Flags().BoolVar(&releaseSnapshot, "snapshot", true, "Build snapshot release (default)")
	releaseCmd.Flags().BoolVar(&releaseClean, "clean", false, "Clean dist directory before build")
	releaseCmd.Flags().BoolVar(&releaseSkipSign, "skip-sign", true, "Skip signing artifacts")
}

func releaseRun(cmd *cobra.Command, args []string) error {
	clioutput.Section("Release Management")

	// Handle init flag
	if releaseInit {
		return initGoreleaserConfig()
	}

	// Handle check flag
	if releaseCheck {
		return checkGoreleaserSetup()
	}

	// Check goreleaser installation
	if !isGoreleaserInstalled() {
		clioutput.Error("", "goreleaser is not installed")
		clioutput.Item("", "Install goreleaser:")
		clioutput.Line(clioutput.StyleMuted, "# Using Homebrew (macOS/Linux)")
		clioutput.Line(clioutput.StyleInfo, "brew install goreleaser")
		clioutput.Line(clioutput.StyleMuted, "# Using Go install")
		clioutput.Line(clioutput.StyleInfo, "go install github.com/goreleaser/goreleaser@latest")
		clioutput.Line(clioutput.StyleMuted, "# Using curl (Linux/macOS)")
		clioutput.Line(clioutput.StyleInfo, "curl -sfL https://goreleaser.com/static/run | bash")
		return errors.New("goreleaser not found")
	}

	clioutput.Success("", "goreleaser is installed")

	// Check configuration file and auto-create if not exists
	configFile := ".goreleaser.yml"
	if !fileExists(configFile) {
		configFile = ".goreleaser.yaml"
		if !fileExists(configFile) {
			clioutput.Item("", "No .goreleaser.yml found, creating default configuration")
			if err := initGoreleaserConfig(); err != nil {
				return fmt.Errorf("failed to generate config: %w", err)
			}
			clioutput.Success("", "Configuration file created automatically")
			configFile = ".goreleaser.yml"
		}
	}

	clioutput.Success("", "Using configuration: %s", configFile)

	// Clean dist directory if requested
	if releaseClean {
		if err := cleanDistDirectory(); err != nil {
			clioutput.Warn("", "Failed to clean dist directory: %v", err)
		}
	}

	// Build release
	if releasePublish {
		return buildRelease(false)
	}
	return buildRelease(true)
}

// isGoreleaserInstalled checks if goreleaser is installed
func isGoreleaserInstalled() bool {
	cmd := exec.Command("goreleaser", "--version")
	err := cmd.Run()
	return err == nil
}

// initGoreleaserConfig generates a default .goreleaser.yml configuration
func initGoreleaserConfig() error {
	clioutput.Item("", "Generating .goreleaser.yml configuration")

	// Get module name for binary name
	moduleName, err := getModuleName()
	if err != nil {
		return fmt.Errorf("failed to get module name: %w", err)
	}
	binaryName := filepath.Base(moduleName)

	config := fmt.Sprintf(`# .goreleaser.yml
# Generated by gg release --init

version: 2

project_name: %s

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: %s
    binary: %s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -tags=netgo
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
      - -X 'main.commit={{.Commit}}'
      - -X 'main.branch={{.Branch}}'
      - -X 'main.buildTime={{.Date}}'

archives:
  - id: %s
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}'
    files:
      - README*
      - LICENSE*
      - CHANGELOG*
      - "*.md"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

# Uncomment and configure for GitHub releases
# release:
#   github:
#     owner: your-username
#     name: your-repo
#   draft: false
#   prerelease: auto

# Uncomment for Docker images
# dockers:
#   - image_templates:
#       - "your-registry/{{.ProjectName}}:{{.Version}}"
#       - "your-registry/{{.ProjectName}}:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
`, binaryName, binaryName, binaryName, binaryName)

	if err := os.WriteFile(".goreleaser.yml", []byte(config), 0o600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	clioutput.Success("", "Generated .goreleaser.yml configuration")
	clioutput.Item("", "Edit the configuration file to customize your release settings")

	return nil
}

// checkGoreleaserSetup checks goreleaser installation and configuration
func checkGoreleaserSetup() error {
	clioutput.Item("", "Checking goreleaser setup")

	// Check installation
	if !isGoreleaserInstalled() {
		clioutput.Error("", "goreleaser is not installed")
		return errors.New("goreleaser not found")
	}
	clioutput.Success("", "goreleaser is installed")

	// Get version
	cmd := exec.Command("goreleaser", "--version")
	output, err := cmd.Output()
	if err != nil {
		clioutput.Warn("", "Failed to get goreleaser version: %v", err)
	} else {
		version := strings.TrimSpace(string(output))
		clioutput.Item("", "Version: %s", version)
	}

	// Check configuration
	configFiles := []string{".goreleaser.yml", ".goreleaser.yaml"}
	configFound := false
	for _, configFile := range configFiles {
		if fileExists(configFile) {
			clioutput.Success("", "Configuration found: %s", configFile)
			configFound = true
			break
		}
	}

	if !configFound {
		clioutput.Warn("", "No configuration file found")
		clioutput.Item("", "Run 'gg release --init' to generate default configuration")
	}

	// Check git repository
	if !isGitRepository() {
		clioutput.Error("", "Not a git repository")
		return errors.New("git repository required")
	}
	clioutput.Success("", "Git repository detected")

	// Check for uncommitted changes
	if hasUncommittedChanges() {
		clioutput.Warn("", "Uncommitted changes detected")
		clioutput.Item("", "Commit changes before creating a release")
	} else {
		clioutput.Success("", "Working directory is clean")
	}

	// Check GITHUB_TOKEN for publishing
	if os.Getenv("GITHUB_TOKEN") != "" {
		clioutput.Success("", "GITHUB_TOKEN is set")
	} else {
		clioutput.Warn("", "GITHUB_TOKEN not set (required for publishing)")
		clioutput.Item("", "Set GITHUB_TOKEN environment variable for GitHub releases")
	}

	clioutput.Success("", "Setup check completed")
	return nil
}

// buildRelease builds the release using goreleaser
func buildRelease(snapshot bool) error {
	var args []string

	if snapshot {
		clioutput.Item("", "Building snapshot release")
		args = append(args, "release", "--snapshot")
	} else {
		clioutput.Item("", "Building and publishing release")
		args = append(args, "release")
	}

	args = append(args, "--clean")

	// Note: --skip-sign is not supported in newer versions of goreleaser
	// Signing can be disabled in the .goreleaser.yml configuration file

	cmd := exec.Command("goreleaser", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		clioutput.Error("", "Release build failed: %v", err)
		return fmt.Errorf("goreleaser failed: %w", err)
	}

	if snapshot {
		clioutput.Success("", "Snapshot release completed")
		clioutput.Item("", "Artifacts available in ./dist directory")
	} else {
		clioutput.Success("", "Release published successfully")
	}

	return nil
}

// cleanDistDirectory removes the dist directory
func cleanDistDirectory() error {
	clioutput.Item("", "Cleaning dist directory")
	if err := os.RemoveAll("./dist"); err != nil {
		return fmt.Errorf("failed to remove dist directory: %w", err)
	}
	clioutput.Success("", "Dist directory cleaned")
	return nil
}

// isGitRepository checks if current directory is a git repository
func isGitRepository() bool {
	cmd := exec.Command("git", "rev-parse", "--git-dir")
	err := cmd.Run()
	return err == nil
}

// hasUncommittedChanges checks if there are uncommitted changes
func hasUncommittedChanges() bool {
	cmd := exec.Command("git", "status", "--porcelain")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	return len(strings.TrimSpace(string(output))) > 0
}
