package consts

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/stoewer/go-strcase"
)

const FrameworkName = "gst"

// apiPathPrefix is the base every business API route is served under. It
// leaves this package only through APIPath, the one place it is added.
const apiPathPrefix = "/api"

// APIPath returns the path a route is served at, the route under the API
// prefix: /api/records/:id for records/:id, and for /records/:id,
// api/records/:id and /api/records/:id alike, since a leading or trailing
// slash and a prefix already written are dropped first; a blank route, or
// the prefix alone, names the root of the prefix, /api/. It is the one rule
// of the path of a route and the only place the prefix is added, and
// nothing takes it off again: gg gen writes every route by it, the router
// registers, the service registry keys and the modules register routes by
// it, and the gg commands list routes as it spells them. A route may thus
// be written with or without the prefix and names the same path either way.
func APIPath(route string) string {
	route = strings.Trim(route, "/")
	if prefix := strings.TrimPrefix(apiPathPrefix, "/"); route == prefix || strings.HasPrefix(route, prefix+"/") {
		route = strings.TrimPrefix(strings.TrimPrefix(route, prefix), "/")
	}
	return apiPathPrefix + "/" + route
}

func CodeGeneratedComment() string {
	return fmt.Sprintf("// Code generated by %s; DO NOT EDIT.", FrameworkName)
}

type AppSide string

const (
	Server AppSide = "server"
	Client AppSide = "client"
)

const (
	// CTX_ROUTE names the matched route pattern ("/api/users/:id") and
	// CTX_PATH the concrete request path ("/api/users/42"). Both identify the
	// same request: the pattern has low cardinality and groups every request
	// of one endpoint together, the path pins down a single request. Log
	// aggregation and alerting must key on the route, never on the path.
	// CTX_METHOD names the request verb, which separates the actions one
	// route pattern serves.
	CTX_ROUTE         = "route"
	CTX_PATH          = "path"
	CTX_METHOD        = "method"
	CTX_USERNAME      = "username"
	CTX_USER_ID       = "user_id"
	CTX_SESSION_ID    = "session_id"
	CTX_TENANT_ID     = "tenant_id"
	CTX_REQUIRES_AUTH = "requires_auth"
	CTX_RESPONSE_CODE = "response_code"
)

// Framework-owned URL query parameters all live in the "_" prefix namespace,
// so bare query keys always belong to model filter fields and never collide
// with framework controls.
const (
	QUERY_PAGE         = "_page"
	QUERY_SIZE         = "_size"
	QUERY_LIMIT        = "_limit"
	QUERY_EXPAND       = "_expand"
	QUERY_DEPTH        = "_depth"
	QUERY_SORT_BY      = "_sort_by"
	QUERY_FORMAT       = "_format"
	QUERY_CURSOR_VALUE = "_cursor_value"
	QUERY_CURSOR_FIELD = "_cursor_field"
	QUERY_CURSOR_NEXT  = "_cursor_next"

	PARAM_ID   = "id"
	PARAM_FILE = "file"

	VALUE_ALL = "all"

	TRACE_ID = "trace_id"
	SPAN_ID  = "span_id"
	SEQ      = "seq"
	CRONJOB  = "cronjob"
	LEADER   = "leader"
	// INSTANCE is the log field naming the process that wrote the entry,
	// the identity every logger stamps; see internal/instance.
	INSTANCE = "instance"

	HEADER_TRACE_ID = "X-Trace-ID"
	HEADER_SPAN_ID  = "X-Span-ID"

	FIELD_ID = "ID"

	PHASE  = "phase"
	PARAMS = "params"
	QUERY  = "query"

	// LOG_DURATION reports how long an operation took as integer nanoseconds,
	// LOG_DURATION_HUMAN the same value rendered for reading ("2.12ms"). Every
	// elapsed time the framework logs goes through util.LogDuration, which is
	// the only writer of this pair, so one query reaches the timing of any
	// operation regardless of which component produced it.
	LOG_DURATION       = "duration"
	LOG_DURATION_HUMAN = "duration_human"

	USER_SYSTEM = "system"
	USER_ROOT   = "root"

	TAG_JSON  = "json"
	TAG_QUERY = "query"
)

// The phases of an action: the action itself, Create and its kind, Import,
// Export, SSE and Stream, and, for the CRUD and batch actions, the hooks run
// before and after it, CreateBefore and CreateAfter. The value is the snake
// case name the service registry keys by and the logs carry.
const (
	Create Phase = create
	Delete Phase = delete_
	Update Phase = update
	Patch  Phase = patch
	List   Phase = list
	Get    Phase = get

	CreateMany Phase = create_many
	DeleteMany Phase = delete_many
	UpdateMany Phase = update_many
	PatchMany  Phase = patch_many

	CreateBefore Phase = create_before
	CreateAfter  Phase = create_after
	DeleteBefore Phase = delete_before
	DeleteAfter  Phase = delete_after
	UpdateBefore Phase = update_before
	UpdateAfter  Phase = update_after
	PatchBefore  Phase = patch_before
	PatchAfter   Phase = patch_after
	ListBefore   Phase = list_before
	ListAfter    Phase = list_after
	GetBefore    Phase = get_before
	GetAfter     Phase = get_after

	CreateManyBefore Phase = create_many_before
	CreateManyAfter  Phase = create_many_after
	DeleteManyBefore Phase = delete_many_before
	DeleteManyAfter  Phase = delete_many_after
	UpdateManyBefore Phase = update_many_before
	UpdateManyAfter  Phase = update_many_after
	PatchManyBefore  Phase = patch_many_before
	PatchManyAfter   Phase = patch_many_after

	Import Phase = import_
	Export Phase = export

	SSE Phase = sse

	Stream Phase = stream
)

type Phase string

// Name returns the name of the phase, the identifier its constant is
// declared with, which is the DSL keyword declaring the action and the
// service method serving it: the value in UpperCamelCase, SSE kept as the
// initialism. Generated code refers to a phase by it. Examples:
//
//	Create       -> "Create"
//	CreateBefore -> "CreateBefore"
//	UpdateMany   -> "UpdateMany"
//	SSE          -> "SSE"
func (p Phase) Name() string {
	if p == SSE {
		return "SSE"
	}
	return strcase.UpperCamelCase(string(p))
}

// Filename returns the Phase generated filename converted to lower case format.
// Example:
//
//	Create       -> "create.go"
//	CreateBefore -> "create.go"
//	UpdateMany   -> "update_many.go"
func (p Phase) Filename() string {
	return string(p.action()) + ".go"
}

// action returns the phase of the action p belongs to: p itself for an
// action phase, the action of a hook phase, Create for CreateBefore and
// CreateMany for CreateManyAfter.
func (p Phase) action() Phase {
	s := strings.TrimSuffix(string(p), "_before")
	return Phase(strings.TrimSuffix(s, "_after"))
}

// hook reports whether p is a hook phase, one run before or after its
// action.
func (p Phase) hook() bool {
	return p.action() != p
}

// RoleName returns the associated role name for the Phase in human-readable form.
// It maps CRUD and ManyCRUD phases (including "_before" and "_after") to specific
// role names. Hook phases map to the role that hosts them: the list_before
// and list_after hooks are generated as methods on the Lister, so both map
// to "Lister".
// Unrecognized phases return an empty string.
//
// Examples:
//
//	Create          -> "Creator"
//	CreateBefore    -> "Creator"
//	UpdateMany      -> "ManyUpdater"
//	UpdateManyAfter -> "ManyUpdater"
func (p Phase) RoleName() string {
	s := string(p.action())
	isMany := strings.HasSuffix(s, "_many")
	s = strings.TrimSuffix(s, "_many")

	var role string
	switch s {
	case create:
		role = "Creator"
	case update:
		role = "Updater"
	case delete_:
		role = "Deleter"
	case patch:
		role = "Patcher"
	case list:
		role = "Lister"
	case get:
		role = "Getter"
	case import_:
		role = "Importer"
	case export:
		role = "Exporter"
	case sse:
		role = "Streamer"
	default:
		return ""
	}

	if isMany {
		role = "Many" + role
	}
	return role
}

// Before returns the corresponding "_before" Phase for CRUD or ManyCRUD operations.
// If the current Phase already contains "_before" or "_after", or is not CRUD/MANYCRUD, it returns itself without modification.
func (p Phase) Before() Phase {
	if p.hook() {
		return p
	}
	s := string(p)

	// Only handle standard CRUD actions
	parts := strings.Split(s, "_")
	if len(parts) == 0 {
		return p
	}

	switch parts[0] {
	case create, update, delete_, patch, list, get:
		// Keep "_many" before "_before"
		if strings.Contains(s, "_many") {
			return Phase(strings.TrimSuffix(s, "_many") + "_many_before")
		}
		return Phase(s + "_before")
	default:
		return p
	}
}

// After returns the corresponding "_after" Phase for CRUD or ManyCRUD operations.
// If the current Phase already contains "_before" or "_after", or is not CRUD/MANYCRUD, it returns itself without modification.
func (p Phase) After() Phase {
	if p.hook() {
		return p
	}
	s := string(p)

	// Only handle standard CRUD actions
	parts := strings.Split(s, "_")
	if len(parts) == 0 {
		return p
	}

	switch parts[0] {
	case create, update, delete_, patch, list, get:
		// Keep "_many" before "_after"
		if strings.Contains(s, "_many") {
			return Phase(strings.TrimSuffix(s, "_many") + "_many_after")
		}
		return Phase(s + "_after")
	default:
		return p
	}
}

// HTTPMethod returns the HTTP method of the route the phase's action is
// registered under, a hook phase answering for its action: Create,
// CreateMany, Import and CreateBefore map to "POST", Delete and DeleteMany
// to "DELETE", Update and UpdateMany to "PUT", Patch and PatchMany to
// "PATCH", and List, Get, Export and SSE to "GET". Stream, served over gRPC
// alone, and any other phase map to "". It is the one table of methods: the
// framework router registers routes by it, and gg reads route methods from
// it.
func (p Phase) HTTPMethod() string {
	switch p.action() {
	case Create, CreateMany, Import:
		return http.MethodPost
	case Delete, DeleteMany:
		return http.MethodDelete
	case Update, UpdateMany:
		return http.MethodPut
	case Patch, PatchMany:
		return http.MethodPatch
	case List, Get, Export, SSE:
		return http.MethodGet
	}
	return ""
}

const (
	ROOT  = "root"
	ADMIN = "admin"
)

// LayoutTimeEncoder is the timestamp layout of every log entry, and the only
// one: no logger may override it, or its file alone would become unorderable
// against the rest.
//
// RFC3339 with nanoseconds is what makes an entry's own timestamp usable. Whole
// seconds cannot order the entries of a single request, which pushes readers
// onto whatever ingest time their log pipeline stamps on, and that measures the
// pipeline rather than the work. Entries are rendered in UTC (see the zap
// encoder): the framework stores the UTC wall clock on every dialect, so a log
// line reads on the same clock as the rows it describes, entries from hosts in
// different zones order lexicographically, and no host zone leaks into the
// stream. Log stores recognize this layout as a date without being told, so the
// field is sortable and range-filterable on arrival.
const LayoutTimeEncoder = time.RFC3339Nano

// LockMode represents the lock mode for database row-level locking
type LockMode string

const (
	// LockUpdate represents FOR UPDATE lock mode
	LockUpdate LockMode = "UPDATE"
	// LockShare represents FOR SHARE lock mode
	LockShare LockMode = "SHARE"
	// LockUpdateNoWait represents FOR UPDATE NOWAIT lock mode
	LockUpdateNoWait LockMode = "UPDATE_NOWAIT"
	// LockShareNoWait represents FOR SHARE NOWAIT lock mode
	LockShareNoWait LockMode = "SHARE_NOWAIT"
	// LockUpdateSkipLocked represents FOR UPDATE SKIP LOCKED lock mode
	LockUpdateSkipLocked LockMode = "UPDATE_SKIP_LOCKED"
	// LockShareSkipLocked represents FOR SHARE SKIP LOCKED lock mode
	LockShareSkipLocked LockMode = "SHARE_SKIP_LOCKED"
)

type OP string

const (
	OP_CREATE OP = create
	OP_DELETE OP = delete_
	OP_UPDATE OP = update
	OP_PATCH  OP = patch
	OP_LIST   OP = list
	OP_GET    OP = get
	OP_EXPORT OP = export
	OP_IMPORT OP = import_

	OP_CREATE_MANY OP = create_many
	OP_DELETE_MANY OP = delete_many
	OP_UPDATE_MANY OP = update_many
	OP_PATCH_MANY  OP = patch_many
)

const (
	// AUTHZ_USER_ROOT is the built-in root user's ID (subject), not a role name.
	AUTHZ_USER_ROOT = "root"

	// AUTHZ_ROLE_ADMIN is the tenant-scoped admin role, granted via g(subject, role, tenant).
	// The Casbin matcher grants this role unconditional access to every object/action
	// inside the tenant, bypassing explicit permission policies entirely.
	AUTHZ_ROLE_ADMIN = "admin"
	// AUTHZ_SYSTEM_ROLE_ROOT is the system-level super-admin role, granted via g2(subject, role)
	// outside any tenant. AUTHZ_USER_ROOT is assigned this role by default during RBAC Init.
	AUTHZ_SYSTEM_ROLE_ROOT = "system_root"
	// AUTHZ_ROLE_AUTHENTICATED is the implicit role every authenticated subject
	// carries. No grouping rule ever assigns it, and no role may claim it as an
	// ID: the Casbin matcher grants policies written for it without consulting
	// role membership or tenant, so they reach subjects that hold no role at all.
	//
	// Use it for routes that answer only about the caller and already narrow
	// their result to what the caller may see. It is not "public": unauthenticated
	// requests are rejected before authorization runs.
	AUTHZ_ROLE_AUTHENTICATED = "authenticated"
)

// GrantSource names the kind of rule that allowed a request. An allowed request
// has exactly one source: a subject may satisfy several authorization rules at
// once, and the source reports the strongest of them, because removing a weaker
// grant would leave the request allowed anyway.
type GrantSource string

const (
	// GrantSourceSystemRoot is the system-level super-admin role, which allows
	// every request in every tenant without consulting a policy.
	GrantSourceSystemRoot GrantSource = "system_root"
	// GrantSourceTenantAdmin is the built-in admin role, which allows every
	// request inside its own tenant without consulting a policy.
	GrantSourceTenantAdmin GrantSource = "tenant_admin"
	// GrantSourceAuthenticated is a policy written for the implicit
	// authenticated role, which allows the request for every authenticated
	// subject regardless of the roles it holds.
	GrantSourceAuthenticated GrantSource = "authenticated"
	// GrantSourceRole is a policy granted to a role the subject holds in the
	// request tenant.
	GrantSourceRole GrantSource = "role"
)

// DenyReason names why a request was not allowed.
//
// A denial has no granting rule, so it cannot be explained the way an allow is,
// by naming one. What is left to say is which of the two steps behind every
// grant did not happen: the subject was never given a role here, or it holds
// roles and none of their permissions covers the request. Those lead to
// opposite repairs — a role binding, or a permission — and the request tuple
// alone does not say which.
//
// The values are few and fixed, so denials can be counted by reason without the
// label set growing with the deployment.
type DenyReason string

const (
	// DenyReasonUnauthenticated is a request carrying no authenticated subject.
	// Authorization runs after authentication, so such a request is refused
	// before any policy is consulted.
	DenyReasonUnauthenticated DenyReason = "unauthenticated"
	// DenyReasonNoRole is a subject holding no role in the request tenant.
	// Nothing tenant-scoped can grant it, whatever permissions exist, so the
	// missing step is a role binding.
	DenyReasonNoRole DenyReason = "no_role"
	// DenyReasonNoPolicy is a subject holding roles whose permissions do not
	// cover this object and action. The binding is in place, so the missing
	// step is a permission.
	DenyReasonNoPolicy DenyReason = "no_policy"
	// DenyReasonNotInitialized is a process holding no policy set at all, which
	// denies every request it decides. It reports a deployment that never
	// initialized authorization rather than a rule somebody forgot to write.
	DenyReasonNotInitialized DenyReason = "not_initialized"
)

type Effect string

const (
	EffectAllow Effect = "allow"
	EffectDeny  Effect = "deny"
)
