package pb

import (
	"go/ast"
	"go/token"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/hydroan/gst/internal/consts"
	"github.com/hydroan/gst/internal/dsl"
	"github.com/hydroan/gst/internal/ggconst"
	"github.com/hydroan/gst/internal/goast"
	"github.com/hydroan/gst/internal/modelinfo"
	"github.com/stoewer/go-strcase"
)

// This file builds the Go file generated beside every definition: for each
// service the definition declares, the type serving it, the calls of its
// actions and the handlers of its rpcs, then the conversions of the
// definition's messages (see convert.go).

// handlerFile builds the Go file generated beside the definition f, named
// after it with the .gen.go suffix, pb/record.gen.go for pb/record.proto, in
// the package the definition's go_package names. For every service f
// declares it holds the type serving the service (see serviceType), the
// calls of the actions the rpcs run (see actionCalls) and one handler per
// rpc (see handler); then, for every project type f gives a message, the
// two conversion functions (see conversionFuncs).
//
// The definition report.proto of the golden fixture, whose Report model
// declares GRPC() and one custom Get on reports/summary answering with a
// ReportRsp, gets pb/report.gen.go (the module tmpapp of the fixture has no
// dot in its path, so the formatter groups its imports with the standard
// library's):
//
//	// Code generated by gst; DO NOT EDIT.
//
//	package pb
//
//	import (
//		"context"
//		"tmpapp/model"
//
//		"github.com/hydroan/gst/consts"
//		"github.com/hydroan/gst/grpc"
//		gstmodel "github.com/hydroan/gst/model"
//	)
//
//	// reportService serves the rpcs of the ReportService service through the
//	// actions of Report: every handler decodes its request message into what the
//	// action's call takes, runs the call and encodes what it answers into the
//	// response message.
//	type reportService struct {
//		UnimplementedReportServiceServer
//	}
//
//	// The calls of the actions of Report, one per rpc of ReportService, built
//	// once at package initialization.
//	var getReport = grpc.ServiceCall[*model.Report, *gstmodel.Empty, *model.ReportRsp](consts.Get, "/api/reports/summary")
//
//	// GetReport serves the Get action of Report on /api/reports/summary.
//	func (reportService) GetReport(ctx context.Context, req *GetReportRequest) (*GetReportResponse, error) {
//		result, err := getReport(ctx, nil, grpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()}, new(gstmodel.Empty))
//		if err != nil {
//			return nil, err
//		}
//		return &GetReportResponse{Result: ReportRspToProto(result)}, nil
//	}
//
//	// ReportRspToProto encodes ReportRsp values into their message, nil into
//	// nil.
//	func ReportRspToProto(m *model.ReportRsp) *ReportRsp {
//		if m == nil {
//			return nil
//		}
//		p := new(ReportRsp)
//		p.Total = m.Total
//		return p
//	}
//
//	// ReportRspFromProto decodes ReportRsp messages into values, nil into nil.
//	func ReportRspFromProto(p *ReportRsp) (*model.ReportRsp, error) {
//		if p == nil {
//			return nil, nil
//		}
//		m := new(model.ReportRsp)
//		m.Total = p.GetTotal()
//		return m, nil
//	}
func (g *generator) handlerFile(f *protoFile) (File, error) {
	w := g.newFileWriter(f)
	var services []string
	rpcs := make(map[string][]*rpc)
	for _, r := range f.rpcs {
		if _, seen := rpcs[r.service]; !seen {
			services = append(services, r.service)
		}
		rpcs[r.service] = append(rpcs[r.service], r)
	}
	for _, service := range services {
		w.serviceType(service, rpcs[service][0].model)
		w.actionCalls(service, rpcs[service])
		for _, r := range rpcs[service] {
			if r.streaming() {
				w.streamHandler(r)
			} else {
				w.handler(r)
			}
		}
	}
	for _, msg := range f.typed {
		w.conversionFuncs(msg)
	}
	name := strings.TrimSuffix(f.name, ".proto") + ggconst.SuffixGenGo
	source, err := w.out.source()
	if err != nil {
		return File{}, errors.Wrapf(err, "print %s", name)
	}
	return File{Path: ggconst.DirPB + "/" + name, Content: source}, nil
}

// serviceTypeName names the type serving service, recordService for
// RecordService and httpService for HTTPService: unexported, so that nothing
// outside the generated package can register the handlers on a server of
// its own, past the listener and its chain; the package's registration file
// is the one place they are registered (see registrationFiles).
func serviceTypeName(service string) string {
	return strcase.LowerCamelCase(service)
}

// serviceType declares the type serving service, the service of model (see
// serviceTypeName): it embeds the Unimplemented server the protobuf plugin
// generated, which answers Unimplemented for any rpc added later, and the
// handlers are its methods (see handler and streamHandler).
//
//	// recordService serves the rpcs of the RecordService service through the
//	// actions of Record: every handler decodes its request message into what the
//	// action's call takes, runs the call and encodes what it answers into the
//	// response message.
//	type recordService struct {
//		UnimplementedRecordServiceServer
//	}
func (w *fileWriter) serviceType(service string, model *modelinfo.Model) {
	w.out.add(serviceTypeName(service)+" serves the rpcs of the "+service+" service through the actions of "+model.ModelName+
		": every handler decodes its request message into what the action's call takes, runs the call and encodes what it answers into the response message.",
		&ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
			Name: ident(serviceTypeName(service)),
			Type: &ast.StructType{Fields: &ast.FieldList{List: []*ast.Field{{Type: ident("Unimplemented" + service + "Server")}}}},
		}}}, nil)
}

// actionCalls declares the calls of the actions the rpcs of service run,
// one variable per rpc named after it, built once at package initialization
// through the call functions of the framework's grpc package: the call of
// the model's standard action, CreateCall and its kind, on the route the
// router registers the action under, or ServiceCall for an action with a
// payload or result of its own, on its phase and route.
//
// The Item model of the golden fixture, with its Create, Get and PatchMany
// on records/:record/items, a Service("seal") Create on items/:id/seal and
// a Service("merge") Create on items/merge taking a MergeReq and answering
// a MergedItemRsp, gets
//
//	// The calls of the actions of Item, one per rpc of ItemService, built once
//	// at package initialization.
//	var (
//		createItem    = grpc.CreateCall[*record.Item]("/api/records/:record/items")
//		getItem       = grpc.GetCall[*record.Item]("/api/records/:record/items/:id")
//		patchManyItem = grpc.PatchManyCall[*record.Item]("/api/records/:record/items/batch")
//		sealItem      = grpc.CreateCall[*record.Item]("/api/items/:id/seal")
//		mergeItem     = grpc.ServiceCall[*record.Item, *record.MergeReq, *record.MergedItemRsp](consts.Create, "/api/items/merge")
//	)
func (w *fileWriter) actionCalls(service string, rpcs []*rpc) {
	model := rpcs[0].model
	specs := make([]ast.Spec, 0, len(rpcs))
	for _, r := range rpcs {
		modelType := star(w.modelPkgType(model, model.ModelName))
		var value ast.Expr
		switch {
		case r.standard:
			value = call(index(w.grpc(r.action.Phase.Name()+"Call"), modelType), strLit(r.registered))
		case r.streaming():
			value = call(
				&ast.IndexListExpr{X: w.grpc(streamKind(r.action) + "StreamCall"), Indices: []ast.Expr{modelType, w.actionType(model, r.action.Payload), w.actionType(model, r.action.Result)}},
				strLit(r.registered),
			)
		default:
			value = call(
				&ast.IndexListExpr{X: w.grpc("ServiceCall"), Indices: []ast.Expr{modelType, w.actionType(model, r.action.Payload), w.actionType(model, r.action.Result)}},
				sel(w.out.imports.fixedRef(ggconst.ImportPathConsts), r.action.Phase.Name()),
				strLit(r.registered),
			)
		}
		specs = append(specs, &ast.ValueSpec{Names: []*ast.Ident{ident(callName(r))}, Values: []ast.Expr{value}})
	}
	w.out.add("The calls of the actions of "+model.ModelName+", one per rpc of "+service+", built once at package initialization.",
		&ast.GenDecl{Tok: token.VAR, Specs: specs}, nil)
}

// callName names the variable holding the call of the rpc r: createRecord
// for CreateRecord.
func callName(r *rpc) string { return lowerFirst(r.name) }

// firstMessage returns the statements a client or bidirectional stream
// handler on a route with parameters opens with: the first message read
// ahead of the call (see grpc.FirstMessage), the parameters it carries
// named params for the call and for the later messages to be held to, and
// the count of the messages, n, which the later ones advance.
func firstMessage(w *fileWriter, srv ast.Expr, params ast.Expr) []ast.Stmt {
	return []ast.Stmt{
		define([]string{"first", "err"}, call(w.grpc("FirstMessage"), sel(srv, "Recv"))),
		ifStmt(nil, notNil(ident("err")), returns(ident("err"))),
		define([]string{"params"}, params),
		define([]string{"n"}, &ast.BasicLit{Kind: token.INT, Value: "1"}),
	}
}

// streamKind names the kind of stream of a Stream action, the prefix of the
// call and the stream type of the framework serving it: Server for a
// streaming result, Client for a streaming payload, Bidi for both.
func streamKind(action *dsl.Action) string {
	switch {
	case action.StreamingPayload && action.StreamingResult:
		return "Bidi"
	case action.StreamingPayload:
		return "Client"
	default:
		return "Server"
	}
}

// modelPkgType refers to the type typeName of the package of model.
func (w *fileWriter) modelPkgType(model *modelinfo.Model, typeName string) ast.Expr {
	return sel(w.out.imports.ref(model.ImportPath(), model.ModelPkgName), typeName)
}

// actionType spells the Payload or Result type of an action of model as
// ServiceCall takes it: the type as declared, *record.MergeReq for
// Payload[*MergeReq], and the framework's *gstmodel.Empty for a side the
// action does not declare.
func (w *fileWriter) actionType(model *modelinfo.Model, typeName string) ast.Expr {
	if typeName == "" || typeName == dsl.PayloadEmpty {
		return star(sel(w.out.imports.fixedRef(ggconst.ImportPathModel), "Empty"))
	}
	name, pointer := strings.CutPrefix(typeName, "*")
	if pointer {
		return star(w.modelPkgType(model, name))
	}
	return w.modelPkgType(model, name)
}

// handler builds the handler of the rpc r, a method of the type serving its
// service: it reads the route parameters, the id, the query, the record or
// the items and the update masks off the request message, runs the call of
// the action on them and answers the response message holding what the
// call answered. A record, an item or a payload is decoded first, and the
// refusal of one its conversion function answers is the call's answer, an
// item's naming the item (see grpc.ItemError).
//
// The rpcs of the Record model of the golden fixture on records, with the
// parameter record, and the PatchMany of the Item model under
// records/:record get, among others,
//
//	// CreateRecord serves the Create action of Record on /api/records.
//	func (recordService) CreateRecord(ctx context.Context, req *CreateRecordRequest) (*CreateRecordResponse, error) {
//		in, err := RecordFromProto(req.GetRecord())
//		if err != nil {
//			return nil, err
//		}
//		m, err := createRecord(ctx, nil, in)
//		if err != nil {
//			return nil, err
//		}
//		return &CreateRecordResponse{Record: RecordToProto(m)}, nil
//	}
//
// the Patch action, taking the paths of the update_mask field,
//
//	// PatchRecord serves the Patch action of Record on /api/records/:record.
//	func (recordService) PatchRecord(ctx context.Context, req *PatchRecordRequest) (*PatchRecordResponse, error) {
//		in, err := RecordFromProto(req.GetRecord())
//		if err != nil {
//			return nil, err
//		}
//		m, err := patchRecord(ctx, map[string]string{"record": req.GetId()}, req.GetId(), in, req.GetUpdateMask().GetPaths())
//		if err != nil {
//			return nil, err
//		}
//		return &PatchRecordResponse{Record: RecordToProto(m)}, nil
//	}
//
// the List action, taking the query fields of the request,
//
//	// ListRecord serves the List action of Record on /api/records.
//	func (recordService) ListRecord(ctx context.Context, req *ListRecordRequest) (*ListRecordResponse, error) {
//		models, total, err := listRecord(ctx, nil, grpc.Query{
//			Filters:     grpc.Filters(req.GetFilters()),
//			SortBy:      req.GetSortBy(),
//			Page:        req.GetPage(),
//			Size:        req.GetSize(),
//			CursorField: req.GetCursorField(),
//			CursorValue: req.GetCursorValue(),
//			CursorNext:  req.GetCursorNext(),
//			Expand:      req.GetExpand(),
//			Depth:       req.GetDepth(),
//		})
//		if err != nil {
//			return nil, err
//		}
//		items := make([]*Record, len(models))
//		for i, m := range models {
//			items[i] = RecordToProto(m)
//		}
//		return &ListRecordResponse{Items: items, Total: int64(total)}, nil
//	}
//
// and the PatchMany of Item, each item decoded and patched by its id,
//
//	// PatchManyItem serves the PatchMany action of Item on
//	// /api/records/:record/items/batch.
//	func (itemService) PatchManyItem(ctx context.Context, req *PatchManyItemRequest) (*PatchManyItemResponse, error) {
//		params := map[string]string{"record": req.GetRecord()}
//		models := make([]*record.Item, len(req.GetItems()))
//		masks := make([][]string, len(req.GetItems()))
//		for i, item := range req.GetItems() {
//			in, err := ItemFromProto(item.GetItem())
//			if err != nil {
//				return nil, grpc.ItemError(i, err)
//			}
//			m, err := grpc.PatchItem(i, params, map[string]string{"record": item.GetRecord()}, item.GetId(), in)
//			if err != nil {
//				return nil, err
//			}
//			models[i] = m
//			masks[i] = item.GetUpdateMask().GetPaths()
//		}
//		stored, err := patchManyItem(ctx, params, models, masks)
//		if err != nil {
//			return nil, err
//		}
//		items := make([]*Item, len(stored))
//		for i, m := range stored {
//			items[i] = ItemToProto(m)
//		}
//		return &PatchManyItemResponse{Items: items}, nil
//	}
//
// and the Service("merge") Create of Item on items/merge, taking a MergeReq
// as its payload and answering a MergedItemRsp,
//
//	// MergeItem serves the Create action of Item on /api/items/merge.
//	func (itemService) MergeItem(ctx context.Context, req *MergeItemRequest) (*MergeItemResponse, error) {
//		payload, err := MergeReqFromProto(req.GetPayload())
//		if err != nil {
//			return nil, err
//		}
//		result, err := mergeItem(ctx, nil, grpc.Query{}, payload)
//		if err != nil {
//			return nil, err
//		}
//		return &MergeItemResponse{Result: MergeRspToProto(result)}, nil
//	}
func (w *fileWriter) handler(r *rpc) {
	w.resetFuncTemps()
	requestFields, responseFields := goFieldNames(r.request), goFieldNames(r.response)
	req := func(name string) ast.Expr { return call(sel(ident("req"), "Get"+requestFields[name])) }
	callee := ident(callName(r))
	failing := func() ast.Stmt { return ifNotNil(ident("err"), returns(ident("nil"), ident("err"))) }
	respond := func(elts ...ast.Expr) ast.Stmt {
		return returns(addr(compositeLit(ident(r.response.GetName()), elts...)), ident("nil"))
	}
	run := func(args ...ast.Expr) ast.Expr { return call(callee, append([]ast.Expr{ident("ctx")}, args...)...) }
	// params are the route parameters the message carries, keyed as the
	// route names them; id is the one naming the record of an item action.
	params := ast.Expr(ident("nil"))
	var id ast.Expr
	if len(r.params) > 0 {
		lit := compositeLit(&ast.MapType{Key: ident("string"), Value: ident("string")})
		for _, p := range r.params {
			lit.Elts = append(lit.Elts, &ast.KeyValueExpr{Key: strLit(p.param), Value: req(p.name)})
			if p.param == r.param {
				id = req(p.name)
			}
		}
		params = lit
	}
	has := func(name string) bool { _, ok := requestFields[name]; return ok }
	query, layout := w.query(r.action.Phase, req, has)

	var body []ast.Stmt
	if r.standard {
		x := modelFieldName(r.model)
		// decoded decodes the message expression into the variable name
		// through the model's FromProto, the handler answering a refusal;
		// decodedItem decodes the item at index i of a batch the same way,
		// the refusal naming the item (see grpc.ItemError).
		decoded := func(name string, message ast.Expr) []ast.Stmt {
			return []ast.Stmt{define([]string{name, "err"}, call(w.conversionFunc(r.message, "FromProto"), message)), failing()}
		}
		decodedItem := func(name string, message ast.Expr) []ast.Stmt {
			return []ast.Stmt{
				define([]string{name, "err"}, call(w.conversionFunc(r.message, "FromProto"), message)),
				ifNotNil(ident("err"), returns(ident("nil"), call(w.grpc("ItemError"), ident("i"), ident("err")))),
			}
		}
		toProto := func(m ast.Expr) ast.Expr { return call(w.conversionFunc(r.message, "ToProto"), m) }
		// single runs the call answering one record and answers it.
		single := func(args ...ast.Expr) []ast.Stmt {
			return []ast.Stmt{define([]string{"m", "err"}, run(args...)), failing(), respond(keyValue(responseFields[x], toProto(ident("m"))))}
		}
		// itemsOf encodes the records the variable from holds into items.
		itemsOf := func(from string) []ast.Stmt {
			return []ast.Stmt{
				define([]string{"items"}, makeCall(&ast.ArrayType{Elt: star(w.messageType(r.message))}, lenCall(ident(from)))),
				rangeStmt("i", "m", ident(from), assign(index(ident("items"), ident("i")), toProto(ident("m")))),
			}
		}
		// modelsOf decodes the items of the request into models.
		modelsOf := func() []ast.Stmt {
			return []ast.Stmt{
				define([]string{"models"}, makeCall(&ast.ArrayType{Elt: star(w.modelPkgType(r.model, r.model.ModelName))}, lenCall(req("items")))),
				rangeStmt("i", "item", req("items"), append(decodedItem("in", ident("item")), assign(index(ident("models"), ident("i")), ident("in")))...),
			}
		}
		switch r.action.Phase {
		case consts.Create:
			body = append(decoded("in", req(x)), single(params, ident("in"))...)
		case consts.Get:
			body = single(params, id, query)
		case consts.Update:
			body = append(decoded("in", req(x)), single(params, id, ident("in"))...)
		case consts.Patch:
			body = append(decoded("in", req(x)), single(params, id, ident("in"), call(sel(req("update_mask"), "GetPaths")))...)
		case consts.Delete:
			body = []ast.Stmt{ifStmt(define([]string{"err"}, run(params, id)), notNil(ident("err")), returns(ident("nil"), ident("err"))), respond()}
		case consts.List:
			body = append([]ast.Stmt{define([]string{"models", "total", "err"}, run(params, query)), failing()}, itemsOf("models")...)
			body = append(body, respond(keyValue(responseFields["items"], ident("items")), keyValue(responseFields["total"], call(ident("int64"), ident("total")))))
		case consts.CreateMany, consts.UpdateMany:
			body = append(modelsOf(), define([]string{"stored", "err"}, run(params, ident("models"))), failing())
			body = append(body, itemsOf("stored")...)
			body = append(body, respond(keyValue(responseFields["items"], ident("items"))))
		case consts.PatchMany:
			// The items are the requests of the model's Patch (see
			// standardMessages), each readied through PatchItem: its id
			// names the record and its parameters must agree with the
			// request's, which the handler names once when there are any.
			// The items field is found by name: the committed definition
			// may number it ahead of a parameter the route took later, and
			// the fields are printed in the order of their numbers.
			var itemsType string
			for _, f := range r.request.Field {
				if f.GetName() == "items" {
					itemsType = f.GetTypeName()
				}
			}
			itemFields := goFieldNames(w.file.messageNamed(strings.TrimPrefix(itemsType, "."+w.file.pkg+".")))
			itemParams := ast.Expr(ident("nil"))
			if len(r.params) > 0 {
				body = append(body, define([]string{"params"}, params))
				params = ident("params")
				lit := compositeLit(&ast.MapType{Key: ident("string"), Value: ident("string")})
				for _, p := range r.params {
					lit.Elts = append(lit.Elts, &ast.KeyValueExpr{Key: strLit(p.param), Value: call(sel(ident("item"), "Get"+itemFields[p.name]))})
				}
				itemParams = lit
			}
			body = append(body,
				define([]string{"models"}, makeCall(&ast.ArrayType{Elt: star(w.modelPkgType(r.model, r.model.ModelName))}, lenCall(req("items")))),
				define([]string{"masks"}, makeCall(&ast.ArrayType{Elt: &ast.ArrayType{Elt: ident("string")}}, lenCall(req("items")))),
				rangeStmt("i", "item", req("items"), append(decodedItem("in", call(sel(ident("item"), "Get"+itemFields[x]))),
					define([]string{"m", "err"}, call(w.grpc("PatchItem"), ident("i"), params, itemParams, call(sel(ident("item"), "Get"+itemFields["id"])), ident("in"))),
					failing(),
					assign(index(ident("models"), ident("i")), ident("m")),
					assign(index(ident("masks"), ident("i")), call(sel(call(sel(ident("item"), "Get"+itemFields["update_mask"])), "GetPaths"))),
				)...),
				define([]string{"stored", "err"}, run(params, ident("models"), ident("masks"))), failing())
			body = append(body, itemsOf("stored")...)
			body = append(body, respond(keyValue(responseFields["items"], ident("items"))))
		case consts.DeleteMany:
			body = []ast.Stmt{ifStmt(define([]string{"err"}, run(params, req("ids"))), notNil(ident("err")), returns(ident("nil"), ident("err"))), respond()}
		}
	} else {
		// The payload is decoded first, the handler answering a refusal;
		// an action declaring none takes the empty request. With no result
		// the call binds err alone, assigned when the decoding declared it
		// and declared otherwise; result is new either way.
		var payload ast.Expr
		var checked ast.Stmt
		if r.payload == nil {
			payload = newCall(sel(w.out.imports.fixedRef(ggconst.ImportPathModel), "Empty"))
			checked = ifStmt(define([]string{"_", "err"}, run(params, query, payload)), notNil(ident("err")), returns(ident("nil"), ident("err")))
		} else {
			body = append(body, define([]string{"payload", "err"}, call(w.conversionFunc(r.payload, "FromProto"), req("payload"))), failing())
			payload = ident("payload")
			checked = ifStmt(&ast.AssignStmt{Lhs: []ast.Expr{ident("_"), ident("err")}, Tok: token.ASSIGN, Rhs: []ast.Expr{run(params, query, payload)}}, notNil(ident("err")), returns(ident("nil"), ident("err")))
		}
		if r.result == nil {
			body = append(body, checked, respond())
		} else {
			body = append(body,
				define([]string{"result", "err"}, run(params, query, payload)),
				failing(),
				respond(keyValue(responseFields["result"], call(w.conversionFunc(r.result, "ToProto"), ident("result")))),
			)
		}
	}

	w.out.add(r.name+" serves the "+r.action.Phase.Name()+" action of "+r.model.ModelName+" on "+consts.APIPath(r.registered)+".", &ast.FuncDecl{
		Recv: &ast.FieldList{List: []*ast.Field{{Type: ident(serviceTypeName(r.service))}}},
		Name: ident(r.name),
		Type: &ast.FuncType{
			Params: &ast.FieldList{List: []*ast.Field{
				{Names: []*ast.Ident{ident("ctx")}, Type: sel(w.out.imports.fixedRef(importPathContext), "Context")},
				{Names: []*ast.Ident{ident("req")}, Type: star(ident(r.request.GetName()))},
			}},
			Results: &ast.FieldList{List: []*ast.Field{{Type: star(ident(r.response.GetName()))}, {Type: ident("error")}}},
		},
		Body: block(body...),
	}, layout)
}

// query builds the Query the call of an action of phase takes, read off the
// request through req, has reporting the fields the request declares: the
// filters and the fields of the controls the model reads (see queryFields)
// of a List, laid out one field per line by the layout returned; the
// expansion of a Get; and the zero Query for any other phase, which takes
// no query.
func (w *fileWriter) query(phase consts.Phase, req func(string) ast.Expr, has func(string) bool) (ast.Expr, func(*goast.LineSet)) {
	lit := compositeLit(w.grpc("Query"))
	switch phase {
	case consts.List:
		lit.Elts = []ast.Expr{keyValue("Filters", call(w.grpc("Filters"), req("filters")))}
		for _, control := range []struct{ field, name string }{
			{"SortBy", "sort_by"},
			{"Page", "page"},
			{"Size", "size"},
			{"CursorField", "cursor_field"},
			{"CursorValue", "cursor_value"},
			{"CursorNext", "cursor_next"},
			{"Expand", "expand"},
			{"Depth", "depth"},
		} {
			if has(control.name) {
				lit.Elts = append(lit.Elts, keyValue(control.field, req(control.name)))
			}
		}
		return lit, func(lines *goast.LineSet) { layoutLiteral(lit, lines) }
	case consts.Get:
		lit.Elts = []ast.Expr{keyValue("Expand", req("expand")), keyValue("Depth", req("depth"))}
	}
	return lit, nil
}

// streamHandler builds the handler of the streaming rpc r, a method of the
// type serving its service taking, as the protobuf plugin typed it, the
// request message and the stream of responses of a server stream, or the
// stream of requests and responses of a client or bidirectional one. It
// reads the route parameters off the request message, the first message of
// a request stream, and runs the stream call of the action (see
// actionCalls) with functions moving the messages of the stream converted
// to the action's types: the request the message carries as payload, its
// decoding answering the refusal of a message a field cannot hold, each
// response encoded into a response message; a client stream answers its
// response with SendAndClose.
//
// The Feed model of the golden fixture, each of whose streams carries
// FeedEvent messages under a name of its own, gets for its Service("watch")
// Stream on feeds/watch, a Payload with a streaming Result,
//
//	// WatchFeed serves the Stream action of Feed declared on feeds/watch, served
//	// over gRPC alone.
//	func (feedService) WatchFeed(req *WatchFeedRequest, srv FeedService_WatchFeedServer) error {
//		payload, err := FeedWatchReqFromProto(req.GetPayload())
//		if err != nil {
//			return err
//		}
//		return watchFeed(srv.Context(), nil, payload, func(rsp *model.FeedWatchRsp) error {
//			return srv.Send(&WatchFeedResponse{Result: FeedEventToProto(rsp)})
//		})
//	}
//
// for its Service("upload") Stream on feeds/:feed/upload, a streaming
// Payload with a Result, whose first message carries the route parameter,
// which every later message may leave empty or repeat,
//
//	// UploadFeedByFeed serves the Stream action of Feed declared on
//	// feeds/:feed/upload, served over gRPC alone.
//	func (feedService) UploadFeedByFeed(srv FeedService_UploadFeedByFeedServer) error {
//		first, err := grpc.FirstMessage(srv.Recv)
//		if err != nil {
//			return err
//		}
//		params := map[string]string{"feed": first.GetFeed()}
//		n := 1
//		result, err := uploadFeedByFeed(srv.Context(), params, func() (*model.FeedUploadReq, error) {
//			if msg := first; msg != nil {
//				first = nil
//				return FeedEventFromProto(msg.GetPayload())
//			}
//			msg, recvErr := srv.Recv()
//			if recvErr != nil {
//				return nil, recvErr
//			}
//			n++
//			if err := grpc.SameParams(n, params, map[string]string{"feed": msg.GetFeed()}); err != nil {
//				return nil, err
//			}
//			return FeedEventFromProto(msg.GetPayload())
//		})
//		if err != nil {
//			return err
//		}
//		return srv.SendAndClose(&UploadFeedByFeedResponse{Result: FeedUploadRspToProto(result)})
//	}
//
// and for its Service("chat") Stream on feeds/chat, both sides streaming,
//
//	// ChatFeed serves the Stream action of Feed declared on feeds/chat, served
//	// over gRPC alone.
//	func (feedService) ChatFeed(srv FeedService_ChatFeedServer) error {
//		return chatFeed(srv.Context(), nil, func() (*model.FeedChatReq, error) {
//			msg, recvErr := srv.Recv()
//			if recvErr != nil {
//				return nil, recvErr
//			}
//			return FeedEventFromProto(msg.GetPayload())
//		}, func(rsp *model.FeedChatRsp) error {
//			return srv.Send(&ChatFeedResponse{Result: FeedEventToProto(rsp)})
//		})
//	}
func (w *fileWriter) streamHandler(r *rpc) {
	w.resetFuncTemps()
	requestFields, responseFields := goFieldNames(r.request), goFieldNames(r.response)
	srv, callee := ident("srv"), ident(callName(r))
	get := func(m ast.Expr, name string) ast.Expr { return call(sel(m, "Get"+requestFields[name])) }
	// paramsOf reads the route parameters off the request message m, nil
	// for a route without any.
	paramsOf := func(m ast.Expr) ast.Expr {
		if len(r.params) == 0 {
			return ident("nil")
		}
		lit := compositeLit(&ast.MapType{Key: ident("string"), Value: ident("string")})
		for _, p := range r.params {
			lit.Elts = append(lit.Elts, &ast.KeyValueExpr{Key: strLit(p.param), Value: get(m, p.name)})
		}
		return lit
	}
	// payloadOf decodes the payload the request message m carries, a call
	// that may refuse the message; empty is the request of an action
	// declaring no payload.
	payloadOf := func(m ast.Expr) ast.Expr { return call(w.conversionFunc(r.payload, "FromProto"), get(m, "payload")) }
	empty := func() ast.Expr { return newCall(sel(w.out.imports.fixedRef(ggconst.ImportPathModel), "Empty")) }
	// returnPayload returns the payload of m from a receiving function: what
	// the decoding answers, the payload or its refusal, or the empty request
	// and no error.
	returnPayload := func(m ast.Expr) ast.Stmt {
		if r.payload == nil {
			return returns(empty(), ident("nil"))
		}
		return returns(payloadOf(m))
	}
	// responseOf encodes the response rsp into the response message, empty
	// for an action declaring no Result.
	responseOf := func(rsp ast.Expr) ast.Expr {
		if r.result == nil {
			return addr(compositeLit(ident(r.response.GetName())))
		}
		return addr(compositeLit(ident(r.response.GetName()), keyValue(responseFields["result"], call(w.conversionFunc(r.result, "ToProto"), rsp))))
	}
	reqType, rspType := w.actionType(r.model, r.action.Payload), w.actionType(r.model, r.action.Result)
	// send is the function sending one response on the stream.
	send := funcLit([]*ast.Field{{Names: []*ast.Ident{ident("rsp")}, Type: rspType}}, []*ast.Field{{Type: ident("error")}},
		returns(call(sel(srv, "Send"), responseOf(ident("rsp")))))
	// recv is the function receiving the next request off the stream, the
	// first message first when it was read for the route parameters, every
	// later message then held to the parameters it carried (see
	// grpc.SameParams), counted by n.
	recv := func(withFirst bool) ast.Expr {
		var body []ast.Stmt
		if withFirst {
			body = append(body, ifStmt(define([]string{"msg"}, ident("first")), notNil(ident("msg")),
				assign(ident("first"), ident("nil")),
				returnPayload(ident("msg")),
			))
		}
		body = append(body,
			define([]string{"msg", "recvErr"}, call(sel(srv, "Recv"))),
			ifStmt(nil, notNil(ident("recvErr")), returns(ident("nil"), ident("recvErr"))),
		)
		if withFirst {
			body = append(body,
				&ast.IncDecStmt{X: ident("n"), Tok: token.INC},
				ifStmt(define([]string{"err"}, call(w.grpc("SameParams"), ident("n"), ident("params"), paramsOf(ident("msg")))), notNil(ident("err")), returns(ident("nil"), ident("err"))),
			)
		}
		body = append(body, returnPayload(ident("msg")))
		return funcLit(nil, []*ast.Field{{Type: reqType}, {Type: ident("error")}}, body...)
	}
	run := func(args ...ast.Expr) ast.Expr {
		return call(callee, append([]ast.Expr{call(sel(srv, "Context"))}, args...)...)
	}
	params := []*ast.Field{{Names: []*ast.Ident{srv}, Type: ident(r.service + "_" + r.name + "Server")}}
	var body []ast.Stmt
	switch streamKind(r.action) {
	case "Server":
		params = append([]*ast.Field{{Names: []*ast.Ident{ident("req")}, Type: star(ident(r.request.GetName()))}}, params...)
		if r.payload == nil {
			body = []ast.Stmt{returns(run(paramsOf(ident("req")), empty(), send))}
		} else {
			body = []ast.Stmt{
				define([]string{"payload", "err"}, payloadOf(ident("req"))),
				ifStmt(nil, notNil(ident("err")), returns(ident("err"))),
				returns(run(paramsOf(ident("req")), ident("payload"), send)),
			}
		}
	case "Client":
		withFirst := len(r.params) > 0
		params := paramsOf(ident("first"))
		if withFirst {
			body, params = append(body, firstMessage(w, srv, params)...), ident("params")
		}
		// With no Result declared the call answers nothing to encode, and
		// the response message is sent empty.
		if r.result == nil {
			body = append(body, ifStmt(define([]string{"_", "err"}, run(params, recv(withFirst))), notNil(ident("err")), returns(ident("err"))))
		} else {
			body = append(body,
				define([]string{"result", "err"}, run(params, recv(withFirst))),
				ifStmt(nil, notNil(ident("err")), returns(ident("err"))),
			)
		}
		body = append(body, returns(call(sel(srv, "SendAndClose"), responseOf(ident("result")))))
	default:
		withFirst := len(r.params) > 0
		params := paramsOf(ident("first"))
		if withFirst {
			body, params = append(body, firstMessage(w, srv, params)...), ident("params")
		}
		body = append(body, returns(run(params, recv(withFirst), send)))
	}
	w.out.add(r.name+" serves the "+r.action.Phase.Name()+" action of "+r.model.ModelName+" declared on "+r.route+", served over gRPC alone.", &ast.FuncDecl{
		Recv: &ast.FieldList{List: []*ast.Field{{Type: ident(serviceTypeName(r.service))}}},
		Name: ident(r.name),
		Type: &ast.FuncType{Params: &ast.FieldList{List: params}, Results: &ast.FieldList{List: []*ast.Field{{Type: ident("error")}}}},
		Body: block(body...),
	}, nil)
}
