package pb

import (
	"go/ast"
	"go/token"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/hydroan/gst/consts"
	"github.com/hydroan/gst/dsl"
	"github.com/hydroan/gst/internal/ggconst"
	"github.com/hydroan/gst/internal/goast"
	"github.com/hydroan/gst/internal/modelinfo"
)

// This file builds the Go file generated beside every definition: for each
// service the definition declares, the type serving it, the calls of its
// actions and the handlers of its rpcs, then the conversions of the
// definition's messages (see convert.go).

// handlerFile builds the Go file generated beside the definition f, named
// after it with the .gen.go suffix, pb/record.gen.go for pb/record.proto, in
// the package the definition's go_package names. For every service f
// declares it holds the type serving the service (see serviceType), the
// calls of the actions the rpcs run (see actionCalls) and one handler per
// rpc (see handler); then, for every project type f gives a message, the
// two conversion functions (see conversionFuncs).
//
// The definition report.proto of the golden fixture, whose Report model
// declares GRPC() and one custom Get on reports/summary answering with a
// ReportRsp, gets pb/report.gen.go (the module tmpapp of the fixture has no
// dot in its path, so the formatter groups its imports with the standard
// library's):
//
//	// Code generated by gst; DO NOT EDIT.
//
//	package pb
//
//	import (
//		"context"
//		"tmpapp/model"
//
//		"github.com/hydroan/gst/consts"
//		"github.com/hydroan/gst/grpc"
//		gstmodel "github.com/hydroan/gst/model"
//	)
//
//	// ReportService serves the rpcs of the ReportService service through the
//	// actions of Report: every handler decodes its request message into what the
//	// action's call takes, runs the call and encodes what it answers into the
//	// response message.
//	type ReportService struct {
//		UnimplementedReportServiceServer
//	}
//
//	// The calls of the actions of Report, one per rpc of ReportService, built
//	// once at package initialization.
//	var getReport = grpc.ServiceCall[*model.Report, *gstmodel.Empty, *model.ReportRsp](consts.PHASE_GET, "reports/summary")
//
//	// GetReport serves the Get action of Report on reports/summary.
//	func (ReportService) GetReport(ctx context.Context, req *GetReportRequest) (*GetReportResponse, error) {
//		result, err := getReport(ctx, nil, grpc.Query{Expand: req.GetExpand(), Depth: req.GetDepth()}, new(gstmodel.Empty))
//		if err != nil {
//			return nil, err
//		}
//		return &GetReportResponse{Result: ReportRspToProto(result)}, nil
//	}
//
//	// ReportRspToProto encodes ReportRsp values into their message, nil into
//	// nil.
//	func ReportRspToProto(m *model.ReportRsp) *ReportRsp {
//		if m == nil {
//			return nil
//		}
//		p := new(ReportRsp)
//		p.Total = m.Total
//		return p
//	}
//
//	// ReportRspFromProto decodes ReportRsp messages into values, nil into nil.
//	func ReportRspFromProto(p *ReportRsp) *model.ReportRsp {
//		if p == nil {
//			return nil
//		}
//		m := new(model.ReportRsp)
//		m.Total = p.GetTotal()
//		return m
//	}
func (g *generator) handlerFile(f *protoFile) (File, error) {
	w := g.newFileWriter(f)
	var services []string
	rpcs := make(map[string][]*rpc)
	for _, r := range f.rpcs {
		if _, seen := rpcs[r.service]; !seen {
			services = append(services, r.service)
		}
		rpcs[r.service] = append(rpcs[r.service], r)
	}
	for _, service := range services {
		w.serviceType(service, rpcs[service][0].model)
		w.actionCalls(service, rpcs[service])
		for _, r := range rpcs[service] {
			w.handler(r)
		}
	}
	for _, msg := range f.typed {
		w.conversionFuncs(msg)
	}
	name := strings.TrimSuffix(f.name, ".proto") + ggconst.SuffixGenGo
	source, err := w.out.source()
	if err != nil {
		return File{}, errors.Wrapf(err, "print %s", name)
	}
	return File{Path: ggconst.DirPB + "/" + name, Content: source}, nil
}

// serviceType declares the type serving service, the service of model: it
// embeds the Unimplemented server the protobuf plugin generated, which
// answers Unimplemented for any rpc added later, and the handlers are its
// methods (see handler).
//
//	// RecordService serves the rpcs of the RecordService service through the
//	// actions of Record: every handler decodes its request message into what the
//	// action's call takes, runs the call and encodes what it answers into the
//	// response message.
//	type RecordService struct {
//		UnimplementedRecordServiceServer
//	}
func (w *fileWriter) serviceType(service string, model *modelinfo.Model) {
	w.out.add(service+" serves the rpcs of the "+service+" service through the actions of "+model.ModelName+
		": every handler decodes its request message into what the action's call takes, runs the call and encodes what it answers into the response message.",
		&ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
			Name: ident(service),
			Type: &ast.StructType{Fields: &ast.FieldList{List: []*ast.Field{{Type: ident("Unimplemented" + service + "Server")}}}},
		}}}, nil)
}

// actionCalls declares the calls of the actions the rpcs of service run,
// one variable per rpc named after it, built once at package initialization
// through the call functions of the framework's grpc package: the call of
// the model's standard action, CreateCall and its kind, on the route the
// router registers the action under, or ServiceCall for an action with a
// payload or result of its own, on its phase and route.
//
// The Item model of the golden fixture, with its two standard actions on
// records/:record/items, a Filename("seal") Create on items/:id/seal and a
// Filename("merge") Create on items/merge taking a MergeReq and answering a
// MergedItemRsp, gets
//
//	// The calls of the actions of Item, one per rpc of ItemService, built once
//	// at package initialization.
//	var (
//		createItem = grpc.CreateCall[*record.Item]("records/:record/items")
//		getItem    = grpc.GetCall[*record.Item]("records/:record/items/:id")
//		sealItem   = grpc.CreateCall[*record.Item]("items/:id/seal")
//		mergeItem  = grpc.ServiceCall[*record.Item, *record.MergeReq, *record.MergedItemRsp](consts.PHASE_CREATE, "items/merge")
//	)
func (w *fileWriter) actionCalls(service string, rpcs []*rpc) {
	model := rpcs[0].model
	specs := make([]ast.Spec, 0, len(rpcs))
	for _, r := range rpcs {
		modelType := star(w.modelPkgType(model, model.ModelName))
		var value ast.Expr
		if r.standard {
			value = call(index(w.grpc(r.action.Phase.MethodName()+"Call"), modelType), strLit(r.registered))
		} else {
			value = call(
				&ast.IndexListExpr{X: w.grpc("ServiceCall"), Indices: []ast.Expr{modelType, w.actionType(model, r.action.Payload), w.actionType(model, r.action.Result)}},
				sel(w.out.imports.fixedRef(ggconst.ImportPathConsts), "PHASE_"+strings.ToUpper(string(r.action.Phase))),
				strLit(r.registered),
			)
		}
		specs = append(specs, &ast.ValueSpec{Names: []*ast.Ident{ident(callName(r))}, Values: []ast.Expr{value}})
	}
	w.out.add("The calls of the actions of "+model.ModelName+", one per rpc of "+service+", built once at package initialization.",
		&ast.GenDecl{Tok: token.VAR, Specs: specs}, nil)
}

// callName names the variable holding the call of the rpc r: createRecord
// for CreateRecord.
func callName(r *rpc) string { return lowerFirst(r.name) }

// modelPkgType refers to the type typeName of the package of model.
func (w *fileWriter) modelPkgType(model *modelinfo.Model, typeName string) ast.Expr {
	return sel(w.out.imports.ref(model.ImportPath(), model.ModelPkgName), typeName)
}

// actionType spells the Payload or Result type of an action of model as
// ServiceCall takes it: the type as declared, *record.MergeReq for
// Payload[*MergeReq], and the framework's *gstmodel.Empty for a side the
// action does not declare.
func (w *fileWriter) actionType(model *modelinfo.Model, typeName string) ast.Expr {
	if typeName == "" || typeName == dsl.PayloadEmpty {
		return star(sel(w.out.imports.fixedRef(ggconst.ImportPathModel), "Empty"))
	}
	name, pointer := strings.CutPrefix(typeName, "*")
	if pointer {
		return star(w.modelPkgType(model, name))
	}
	return w.modelPkgType(model, name)
}

// handler builds the handler of the rpc r, a method of the type serving its
// service: it reads the route parameters, the id, the query, the record or
// the items and the update masks off the request message, runs the call of
// the action on them and answers the response message holding what the
// call answered.
//
// The rpcs of the Record model of the golden fixture on records, with the
// parameter record, get, among others,
//
//	// CreateRecord serves the Create action of Record on records.
//	func (RecordService) CreateRecord(ctx context.Context, req *CreateRecordRequest) (*CreateRecordResponse, error) {
//		m, err := createRecord(ctx, nil, RecordFromProto(req.GetRecord()))
//		if err != nil {
//			return nil, err
//		}
//		return &CreateRecordResponse{Record: RecordToProto(m)}, nil
//	}
//
//	// PatchRecord serves the Patch action of Record on records.
//	func (RecordService) PatchRecord(ctx context.Context, req *PatchRecordRequest) (*PatchRecordResponse, error) {
//		m, err := patchRecord(ctx, map[string]string{"record": req.GetId()}, req.GetId(), RecordFromProto(req.GetRecord()), req.GetUpdateMask().GetPaths())
//		if err != nil {
//			return nil, err
//		}
//		return &PatchRecordResponse{Record: RecordToProto(m)}, nil
//	}
//
//	// ListRecord serves the List action of Record on records.
//	func (RecordService) ListRecord(ctx context.Context, req *ListRecordRequest) (*ListRecordResponse, error) {
//		models, total, err := listRecord(ctx, nil, grpc.Query{
//			Filters:     grpc.Filters(req.GetFilters()),
//			SortBy:      req.GetSortBy(),
//			Page:        req.GetPage(),
//			Size:        req.GetSize(),
//			CursorField: req.GetCursorField(),
//			CursorValue: req.GetCursorValue(),
//			CursorNext:  req.GetCursorNext(),
//			Expand:      req.GetExpand(),
//			Depth:       req.GetDepth(),
//		})
//		if err != nil {
//			return nil, err
//		}
//		items := make([]*Record, len(models))
//		for i, m := range models {
//			items[i] = RecordToProto(m)
//		}
//		return &ListRecordResponse{Items: items, Total: int64(total)}, nil
//	}
//
//	// PatchManyRecord serves the PatchMany action of Record on records.
//	func (RecordService) PatchManyRecord(ctx context.Context, req *PatchManyRecordRequest) (*PatchManyRecordResponse, error) {
//		models := make([]*model.Record, len(req.GetItems()))
//		masks := make([][]string, len(req.GetItems()))
//		for i, item := range req.GetItems() {
//			models[i] = RecordFromProto(item.GetRecord())
//			masks[i] = item.GetUpdateMask().GetPaths()
//		}
//		stored, err := patchManyRecord(ctx, nil, models, masks)
//		if err != nil {
//			return nil, err
//		}
//		items := make([]*Record, len(stored))
//		for i, m := range stored {
//			items[i] = RecordToProto(m)
//		}
//		return &PatchManyRecordResponse{Items: items}, nil
//	}
//
// and the Filename("merge") Create of Item on items/merge, taking a MergeReq
// as its payload and answering a MergedItemRsp,
//
//	// MergeItem serves the Create action of Item on items/merge.
//	func (ItemService) MergeItem(ctx context.Context, req *MergeItemRequest) (*MergeItemResponse, error) {
//		result, err := mergeItem(ctx, nil, grpc.Query{}, MergeReqFromProto(req.GetPayload()))
//		if err != nil {
//			return nil, err
//		}
//		return &MergeItemResponse{Result: MergeRspToProto(result)}, nil
//	}
func (w *fileWriter) handler(r *rpc) {
	w.resetTemps()
	requestFields, responseFields := goFieldNames(r.request), goFieldNames(r.response)
	req := func(name string) ast.Expr { return call(sel(ident("req"), "Get"+requestFields[name])) }
	callee := ident(callName(r))
	failing := func() ast.Stmt { return ifNotNil(ident("err"), returns(ident("nil"), ident("err"))) }
	respond := func(elts ...ast.Expr) ast.Stmt {
		return returns(addr(compositeLit(ident(r.response.GetName()), elts...)), ident("nil"))
	}
	run := func(args ...ast.Expr) ast.Expr { return call(callee, append([]ast.Expr{ident("ctx")}, args...)...) }
	// params are the route parameters the message carries, keyed as the
	// route names them; id is the one naming the record of an item action.
	params := ast.Expr(ident("nil"))
	var id ast.Expr
	if len(r.params) > 0 {
		lit := compositeLit(&ast.MapType{Key: ident("string"), Value: ident("string")})
		for _, p := range r.params {
			lit.Elts = append(lit.Elts, &ast.KeyValueExpr{Key: strLit(p.param), Value: req(p.name)})
			if p.param == r.param {
				id = req(p.name)
			}
		}
		params = lit
	}
	query, layout := w.query(r.action.Phase, req)

	var body []ast.Stmt
	if r.standard {
		x := modelFieldName(r.model)
		fromProto := func(message ast.Expr) ast.Expr { return call(w.conversionFunc(r.message, "FromProto"), message) }
		toProto := func(m ast.Expr) ast.Expr { return call(w.conversionFunc(r.message, "ToProto"), m) }
		// single runs the call answering one record and answers it.
		single := func(args ...ast.Expr) []ast.Stmt {
			return []ast.Stmt{define([]string{"m", "err"}, run(args...)), failing(), respond(keyValue(responseFields[x], toProto(ident("m"))))}
		}
		// itemsOf encodes the records the variable from holds into items.
		itemsOf := func(from string) []ast.Stmt {
			return []ast.Stmt{
				define([]string{"items"}, makeCall(&ast.ArrayType{Elt: star(w.messageType(r.message))}, lenCall(ident(from)))),
				rangeStmt("i", "m", ident(from), assign(index(ident("items"), ident("i")), toProto(ident("m")))),
			}
		}
		// modelsOf decodes the items of the request into models, each
		// through item; more decodes what else an item carries.
		modelsOf := func(item func(ast.Expr) ast.Expr, more ...ast.Stmt) []ast.Stmt {
			return []ast.Stmt{
				define([]string{"models"}, makeCall(&ast.ArrayType{Elt: star(w.modelPkgType(r.model, r.model.ModelName))}, lenCall(req("items")))),
				rangeStmt("i", "item", req("items"), append([]ast.Stmt{assign(index(ident("models"), ident("i")), fromProto(item(ident("item"))))}, more...)...),
			}
		}
		switch r.action.Phase {
		case consts.PHASE_CREATE:
			body = single(params, fromProto(req(x)))
		case consts.PHASE_GET:
			body = single(params, id, query)
		case consts.PHASE_UPDATE:
			body = single(params, id, fromProto(req(x)))
		case consts.PHASE_PATCH:
			body = single(params, id, fromProto(req(x)), call(sel(req("update_mask"), "GetPaths")))
		case consts.PHASE_DELETE:
			body = []ast.Stmt{ifStmt(define([]string{"err"}, run(params, id)), notNil(ident("err")), returns(ident("nil"), ident("err"))), respond()}
		case consts.PHASE_LIST:
			body = append([]ast.Stmt{define([]string{"models", "total", "err"}, run(params, query)), failing()}, itemsOf("models")...)
			body = append(body, respond(keyValue(responseFields["items"], ident("items")), keyValue(responseFields["total"], call(ident("int64"), ident("total")))))
		case consts.PHASE_CREATE_MANY, consts.PHASE_UPDATE_MANY:
			body = append(modelsOf(func(item ast.Expr) ast.Expr { return item }), define([]string{"stored", "err"}, run(params, ident("models"))), failing())
			body = append(body, itemsOf("stored")...)
			body = append(body, respond(keyValue(responseFields["items"], ident("items"))))
		case consts.PHASE_PATCH_MANY:
			itemFields := goFieldNames(r.request.GetNestedType()[0])
			masks := define([]string{"masks"}, makeCall(&ast.ArrayType{Elt: &ast.ArrayType{Elt: ident("string")}}, lenCall(req("items"))))
			models := modelsOf(func(item ast.Expr) ast.Expr { return call(sel(item, "Get"+itemFields[x])) },
				assign(index(ident("masks"), ident("i")), call(sel(call(sel(ident("item"), "Get"+itemFields["update_mask"])), "GetPaths"))))
			body = append([]ast.Stmt{models[0], masks, models[1]}, define([]string{"stored", "err"}, run(params, ident("models"), ident("masks"))), failing())
			body = append(body, itemsOf("stored")...)
			body = append(body, respond(keyValue(responseFields["items"], ident("items"))))
		case consts.PHASE_DELETE_MANY:
			body = []ast.Stmt{ifStmt(define([]string{"err"}, run(params, req("ids"))), notNil(ident("err")), returns(ident("nil"), ident("err"))), respond()}
		}
	} else {
		var payload ast.Expr
		if r.payload != nil {
			payload = call(w.conversionFunc(r.payload, "FromProto"), req("payload"))
		} else {
			payload = newCall(sel(w.out.imports.fixedRef(ggconst.ImportPathModel), "Empty"))
		}
		if r.result == nil {
			body = []ast.Stmt{ifStmt(define([]string{"_", "err"}, run(params, query, payload)), notNil(ident("err")), returns(ident("nil"), ident("err"))), respond()}
		} else {
			body = []ast.Stmt{
				define([]string{"result", "err"}, run(params, query, payload)),
				failing(),
				respond(keyValue(responseFields["result"], call(w.conversionFunc(r.result, "ToProto"), ident("result")))),
			}
		}
	}

	w.out.add(r.name+" serves the "+r.action.Phase.MethodName()+" action of "+r.model.ModelName+" on "+r.route+".", &ast.FuncDecl{
		Recv: &ast.FieldList{List: []*ast.Field{{Type: ident(r.service)}}},
		Name: ident(r.name),
		Type: &ast.FuncType{
			Params: &ast.FieldList{List: []*ast.Field{
				{Names: []*ast.Ident{ident("ctx")}, Type: sel(w.out.imports.fixedRef(importPathContext), "Context")},
				{Names: []*ast.Ident{ident("req")}, Type: star(ident(r.request.GetName()))},
			}},
			Results: &ast.FieldList{List: []*ast.Field{{Type: star(ident(r.response.GetName()))}, {Type: ident("error")}}},
		},
		Body: block(body...),
	}, layout)
}

// query builds the Query the call of an action of phase takes, read off the
// request through req: the filters, orderings, pagination, cursor and
// expansion of a List, laid out one field per line by the layout returned;
// the expansion of a Get; and the zero Query for any other phase, which
// takes no query.
func (w *fileWriter) query(phase consts.Phase, req func(string) ast.Expr) (ast.Expr, func(*goast.LineSet)) {
	lit := compositeLit(w.grpc("Query"))
	switch phase {
	case consts.PHASE_LIST:
		lit.Elts = []ast.Expr{
			keyValue("Filters", call(w.grpc("Filters"), req("filters"))),
			keyValue("SortBy", req("sort_by")),
			keyValue("Page", req("page")),
			keyValue("Size", req("size")),
			keyValue("CursorField", req("cursor_field")),
			keyValue("CursorValue", req("cursor_value")),
			keyValue("CursorNext", req("cursor_next")),
			keyValue("Expand", req("expand")),
			keyValue("Depth", req("depth")),
		}
		return lit, func(lines *goast.LineSet) { layoutLiteral(lit, lines) }
	case consts.PHASE_GET:
		lit.Elts = []ast.Expr{keyValue("Expand", req("expand")), keyValue("Depth", req("depth"))}
	}
	return lit, nil
}
