package pb

import (
	"go/ast"
	"maps"
	"net/http"
	"slices"

	"github.com/cockroachdb/errors"
	"github.com/hydroan/gst/internal/ggconst"
	"github.com/hydroan/gst/internal/goast"
)

// This file builds pb/pb.gen.go, the file registering the services on the
// listener.

// httpMethodConsts names the net/http constant of each HTTP method the
// registration describes an rpc by.
var httpMethodConsts = map[string]string{
	http.MethodGet:    "MethodGet",
	http.MethodPost:   "MethodPost",
	http.MethodPut:    "MethodPut",
	http.MethodPatch:  "MethodPatch",
	http.MethodDelete: "MethodDelete",
}

// registrationFile builds pb/pb.gen.go, which registers the service of
// every model declaring GRPC() on the listener at package initialization,
// the way router/router.gen.go registers the routes: one grpc.Register call
// per service, definition by definition, handing over the registration
// function the protobuf plugin generated and the type serving the service
// (see serviceType) under the server interface the plugin generated, and
// describing each rpc by its full method name, the constant the plugin
// generated for it, the HTTP method and route the same action is served
// at, which the interceptors of the modules judge a call by, and whether
// its action declares Public(). A service of a package under pb/ is
// registered through an import of the package.
//
// The golden fixture, whose Note and Record models are declared in model/
// and whose Item model in model/record/, gets, the Feed, Report and Shape
// services left out,
//
//	// Code generated by gst; DO NOT EDIT.
//
//	package pb
//
//	import (
//		"net/http"
//		"tmpapp/pb/record"
//
//		"github.com/hydroan/gst/grpc"
//	)
//
//	func init() {
//		grpc.Register[NoteServiceServer](RegisterNoteServiceServer, NoteService{},
//			grpc.Method{Name: NoteService_CreateNote_FullMethodName, HTTPMethod: http.MethodPost, Route: "/api/notes"},
//			grpc.Method{Name: NoteService_GetNote_FullMethodName, HTTPMethod: http.MethodGet, Route: "/api/notes/:id"},
//		)
//		grpc.Register[RecordServiceServer](RegisterRecordServiceServer, RecordService{},
//			grpc.Method{Name: RecordService_CreateRecord_FullMethodName, HTTPMethod: http.MethodPost, Route: "/api/records"},
//			grpc.Method{Name: RecordService_DeleteRecord_FullMethodName, HTTPMethod: http.MethodDelete, Route: "/api/records/:record"},
//			...
//			grpc.Method{Name: RecordService_ListRecordByOwner_FullMethodName, HTTPMethod: http.MethodGet, Route: "/api/owners/:owner/records"},
//		)
//		grpc.Register[record.ItemServiceServer](record.RegisterItemServiceServer, record.ItemService{},
//			grpc.Method{Name: record.ItemService_CreateItem_FullMethodName, HTTPMethod: http.MethodPost, Route: "/api/records/:record/items"},
//			grpc.Method{Name: record.ItemService_GetItem_FullMethodName, HTTPMethod: http.MethodGet, Route: "/api/records/:record/items/:id"},
//			grpc.Method{Name: record.ItemService_SealItem_FullMethodName, HTTPMethod: http.MethodPost, Route: "/api/items/:id/seal"},
//			grpc.Method{Name: record.ItemService_MergeItem_FullMethodName, HTTPMethod: http.MethodPost, Route: "/api/items/merge"},
//		)
//		...
//	}
func (g *generator) registrationFile() (File, error) {
	out := newGoFile(ggconst.DirPB)
	var body []ast.Stmt
	var calls []*ast.CallExpr
	for _, name := range slices.Sorted(maps.Keys(g.files)) {
		f := g.files[name]
		// qualify refers to a name of the package the definition's Go files
		// belong to: the file's own package for a definition at the root of
		// pb/, an imported one below it.
		qualify := func(name string) ast.Expr {
			if f.dir() == "." {
				return ident(name)
			}
			return sel(out.imports.ref(f.goImportPath(), f.goPackageName()), name)
		}
		var services []string
		rpcs := make(map[string][]*rpc)
		for _, r := range f.rpcs {
			if _, seen := rpcs[r.service]; !seen {
				services = append(services, r.service)
			}
			rpcs[r.service] = append(rpcs[r.service], r)
		}
		for _, service := range services {
			args := []ast.Expr{qualify("Register" + service + "Server"), compositeLit(qualify(service))}
			for _, r := range rpcs[service] {
				elts := []ast.Expr{keyValue("Name", qualify(service+"_"+r.name+"_FullMethodName"))}
				// A streaming rpc, served over gRPC alone, is described by
				// the stream word in place of an HTTP method.
				method := ast.Expr(sel(out.imports.fixedRef(ggconst.ImportPathGRPC), "MethodStream"))
				if !r.streaming() {
					method = sel(out.imports.fixedRef(importPathHTTP), httpMethodConsts[r.action.Phase.HTTPMethod()])
				}
				elts = append(elts, keyValue("HTTPMethod", method), keyValue("Route", strLit(r.registered)))
				if r.action.Public {
					elts = append(elts, keyValue("Public", ident("true")))
				}
				args = append(args, compositeLit(sel(out.imports.fixedRef(ggconst.ImportPathGRPC), "Method"), elts...))
			}
			register := call(index(sel(out.imports.fixedRef(ggconst.ImportPathGRPC), "Register"), qualify(service+"Server")), args...)
			body = append(body, exprStmt(register))
			calls = append(calls, register)
		}
	}
	out.add("", &ast.FuncDecl{
		Name: ident(ggconst.FuncInit),
		Type: &ast.FuncType{Params: &ast.FieldList{}},
		Body: block(body...),
	}, func(lines *goast.LineSet) {
		// Each registration opens with the registration function and the
		// server on the line of the call, then one rpc per line, then the
		// closing parenthesis on a line of its own.
		for _, register := range calls {
			line := lines.Next()
			setExprPos(register.Fun, line)
			setExprPos(register.Args[0], line)
			setExprPos(register.Args[1], line)
			for _, arg := range register.Args[2:] {
				setExprPos(arg, lines.Next())
			}
			register.Rparen = lines.Next()
		}
	})
	source, err := out.source()
	if err != nil {
		return File{}, errors.Wrapf(err, "print %s", ggconst.FilePBGen)
	}
	return File{Path: ggconst.DirPB + "/" + ggconst.FilePBGen, Content: source}, nil
}
